package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var (
	scanDir = flag.String("dir", ".", "扫描目录（相对于 go.mod）")
	outFile = flag.String("out", "imports_gen.go", "输出文件")
	pkgName = flag.String("pkg", "main", "生成包名")
)

func main() {
	flag.Parse()

	goModPath, err := findGoMod()
	if err != nil {
		panic(err)
	}

	goModDir := filepath.Dir(goModPath)

	moduleName, err := getModuleName(goModPath)
	if err != nil {
		panic(err)
	}

	rootAbs := filepath.Join(goModDir, *scanDir)

	var imports []string

	err = filepath.Walk(rootAbs, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}

		if !info.IsDir() {
			return nil
		}

		// ❌ 跳过无关目录
		if shouldSkipDir(path) {
			return filepath.SkipDir
		}

		// ❌ 跳过扫描根目录本身
		if filepath.Clean(path) == filepath.Clean(rootAbs) {
			return nil
		}

		// ❌ 没有 go 文件的目录直接跳过
		if !hasGoFiles(path) {
			return nil
		}

		rel, err := filepath.Rel(rootAbs, path)
		if err != nil {
			return nil
		}

		// ❌ 过滤非法路径
		if rel == "." || rel == "" {
			return nil
		}

		parts := strings.Split(rel, string(os.PathSeparator))

		// ❌ 关键：禁止导入 scanDir 第一层（cmd / tools / scripts 等）
		// 例如 orm-crud/gorm/cmd → parts[0] = cmd
		if len(parts) > 0 {
			if isIgnoredTopDir(parts[0]) {
				return nil
			}
		}

		fullRel := filepath.ToSlash(filepath.Join(*scanDir, rel))
		importPath := moduleName + "/" + fullRel

		imports = append(imports, importPath)

		return nil
	})

	if err != nil {
		panic(err)
	}

	sort.Strings(imports)

	if len(imports) == 0 {
		fmt.Println("⚠️ 没有找到任何可导入 package:", rootAbs)
	}

	if err := writeFile(*outFile, *pkgName, imports); err != nil {
		panic(err)
	}

	fmt.Println("✅ generated:", *outFile)
}

func findGoMod() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		path := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(path); err == nil {
			return path, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return "", fmt.Errorf("go.mod not found")
}

func getModuleName(goModPath string) (string, error) {
	f, err := os.Open(goModPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}

	return "", fmt.Errorf("module not found")
}

func hasGoFiles(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}

	for _, e := range entries {
		if e.IsDir() {
			continue
		}

		name := e.Name()

		if strings.HasSuffix(name, ".go") &&
			!strings.HasSuffix(name, "_test.go") {
			return true
		}
	}

	return false
}

func shouldSkipDir(path string) bool {
	base := filepath.Base(path)

	if base == "vendor" ||
		base == "testdata" ||
		base == ".git" ||
		base == ".idea" ||
		base == ".vscode" {
		return true
	}

	if strings.HasPrefix(base, ".") {
		return true
	}

	return false
}

func isIgnoredTopDir(name string) bool {
	// ❌ 关键：禁止工具型顶层目录被 import
	switch name {
	case "cmd", "tools", "scripts", "example":
		return true
	default:
		return false
	}
}

func writeFile(filename, pkg string, imports []string) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	w := bufio.NewWriter(f)

	fmt.Fprintln(w, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "package %s\n\n", pkg)

	fmt.Fprintln(w, "import (")

	for _, imp := range imports {
		fmt.Fprintf(w, "\t_ %q\n", imp)
	}

	fmt.Fprintln(w, ")")

	return w.Flush()
}
