shellEmulator: true

trustPolicy: no-downgrade

packages:
  - front/apps/*
  - front/packages/*
allowBuilds:
  unrs-resolver: false

overrides:
  vite: "catalog:dev"
  vitest: "catalog:dev"
catalogs:
  build:
    "@ant-design/cssinjs": latest
    "@ant-design/icons": latest
    "@ant-design/pro-components": ^3.1.12-0
    "@emotion/css": latest
    "@fontsource-variable/geist": latest
    "@preact/signals-react": latest
    "@t3-oss/env-core": latest
    "@tanstack/react-router": latest
    "@tanstack/react-router-devtools": latest
    "@tanstack/react-start": latest
    "@tanstack/react-store": latest
    ahooks: latest
    alova: latest
    antd: ^6
    antd-style: latest
    class-variance-authority: latest
    clsx: latest
    i18next: latest
    i18next-browser-languagedetector: latest
    immer: latest
    js-cookie: latest
    lodash: latest
    lucide-react: latest
    motion: latest
    nprogress: latest
    preact-render-to-string: latest
    react: latest
    react-dom: latest
    react-i18next: latest
    zod: latest
    zustand: latest
  dev:
    "@antfu/eslint-config": ^7
    "@eslint-react/eslint-plugin": ^2
    "@faker-js/faker": latest
    "@playwright/experimental-ct-react": latest
    "@playwright/test": latest
    "@tailwindcss/typography": latest
    "@tailwindcss/vite": latest
    "@tanstack/devtools-vite": latest
    "@tanstack/eslint-config": ^0.3
    "@tanstack/react-devtools": latest
    "@tanstack/router-plugin": latest
    "@types/js-cookie": latest
    "@types/lodash": latest
    "@types/node": ^24
    "@types/nprogress": latest
    "@types/react": ^19
    "@types/react-dom": ^19
    "@typescript/native-preview": 7.0.0-dev.20260316.1
    "@vitejs/devtools": latest
    "@vitejs/plugin-react": latest
    "@vitejs/plugin-react-swc": latest
    bumpp: ^11
    eslint: ^9
    eslint-plugin-cypress: latest
    eslint-plugin-format: latest
    eslint-plugin-react-hooks: latest
    eslint-plugin-react-refresh: latest
    msw: latest
    nitro: latest
    tailwind-merge: latest
    tailwindcss: latest
    taze: latest
    tw-animate-css: latest
    typescript: ^5
    unplugin-auto-import: latest
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vite-plugin-inspect: v12.0.0-beta.1
    vite-plugin-pwa: latest
    vite-plus: latest
    vitest: npm:@voidzero-dev/vite-plus-test@latest

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
