/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AccountApi: typeof import('./api/account').AccountApi
  const Activity: typeof import('react').Activity
  const DictApi: typeof import('./api/dict').DictApi
  const EncryptApi: typeof import('./api/encrypt').EncryptApi
  const ErrorComponent: typeof import('./components/error').ErrorComponent
  const Fragment: typeof import('react').Fragment
  const Header: typeof import('./domains/constant').Header
  const HttpCode: typeof import('./domains/constant').HttpCode
  const HttpCodeChaeck: typeof import('./domains/constant').HttpCodeChaeck
  const HttpCodeCheck: typeof import('./domains/constant').HttpCodeCheck
  const NotFoundComponent: typeof import('./components/notFound').NotFoundComponent
  const RoleApi: typeof import('./api/role').RoleApi
  const Suspense: typeof import('react').Suspense
  const XHeader: typeof import('./domains/constant').Header
  const aesDecrypt: typeof import('./utils/encrypt').aesDecrypt
  const aesDecryptCiphertextAndTag: typeof import('./utils/encrypt').aesDecryptCiphertextAndTag
  const aesEncrypt: typeof import('./utils/encrypt').aesEncrypt
  const antd: typeof import('./utils/antd').default
  const api: typeof import('./api/index').default
  const arrayBufferToBase64: typeof import('./utils/encrypt').arrayBufferToBase64
  const base64ToArrayBuffer: typeof import('./utils/encrypt').base64ToArrayBuffer
  const buildMenuItems: typeof import('./utils/menu').buildMenuItems
  const buildMenuTree: typeof import('./utils/menu').buildMenuTree
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const changePwdModal: typeof import('./components/business/account/changePwdModal').default
  const cn: typeof import('./components/lib/utils').cn
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const defaultZodValidator: typeof import('./utils/zod').defaultZodValidator
  const fieldZodValidator: typeof import('./utils/zod').fieldZodValidator
  const filterValidMenu: typeof import('./utils/menu').filterValidMenu
  const forwardRef: typeof import('react').forwardRef
  const gMessage: typeof import('./utils/antd').gMessage
  const generateAesKey: typeof import('./utils/encrypt').generateAesKey
  const getMenu: typeof import('./utils/menu').getMenu
  const getOrder: typeof import('./utils/menu').getOrder
  const globalZodValidator: typeof import('./utils/zod').globalZodValidator
  const groupByParentId: typeof import('./utils/menu').groupByParentId
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const rsaEncrypt: typeof import('./utils/encrypt').rsaEncrypt
  const sortByOrder: typeof import('./utils/menu').sortByOrder
  const startTransition: typeof import('react').startTransition
  const t: typeof import('./config/themes/t').default
  const uriSort: typeof import('./utils/encrypt').uriSort
  const use: typeof import('react').use
  const useAccountStore: typeof import('./stores/account').useAccountStore
  const useActionState: typeof import('react').useActionState
  const useAntTheme: typeof import('./stores/theme').useAntTheme
  const useAntdTable: typeof import('ahooks').useAntdTable
  const useAsyncEffect: typeof import('ahooks').useAsyncEffect
  const useBoolean: typeof import('ahooks').useBoolean
  const useCallback: typeof import('react').useCallback
  const useCartoonTheme: typeof import('./config/themes/useCartoonTheme').default
  const useClickAway: typeof import('ahooks').useClickAway
  const useContext: typeof import('react').useContext
  const useControllableValue: typeof import('ahooks').useControllableValue
  const useCookieState: typeof import('ahooks').useCookieState
  const useCountDown: typeof import('ahooks').useCountDown
  const useCounter: typeof import('ahooks').useCounter
  const useCreation: typeof import('ahooks').useCreation
  const useDebounce: typeof import('ahooks').useDebounce
  const useDebounceEffect: typeof import('ahooks').useDebounceEffect
  const useDebounceFn: typeof import('ahooks').useDebounceFn
  const useDebugValue: typeof import('react').useDebugValue
  const useDeepCompareEffect: typeof import('ahooks').useDeepCompareEffect
  const useDeepCompareLayoutEffect: typeof import('ahooks').useDeepCompareLayoutEffect
  const useDefaultTheme: typeof import('./config/themes/useDefaultTheme').default
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDeviceStore: typeof import('./stores/device').useDeviceStore
  const useDocumentVisibility: typeof import('ahooks').useDocumentVisibility
  const useDrag: typeof import('ahooks').useDrag
  const useDrop: typeof import('ahooks').useDrop
  const useDynamicList: typeof import('ahooks').useDynamicList
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useEventEmitter: typeof import('ahooks').useEventEmitter
  const useEventListener: typeof import('ahooks').useEventListener
  const useEventTarget: typeof import('ahooks').useEventTarget
  const useExternal: typeof import('ahooks').useExternal
  const useFavicon: typeof import('ahooks').useFavicon
  const useFocusWithin: typeof import('ahooks').useFocusWithin
  const useFullscreen: typeof import('ahooks').useFullscreen
  const useFusionTable: typeof import('ahooks').useFusionTable
  const useGetState: typeof import('ahooks').useGetState
  const useHistoryTravel: typeof import('ahooks').useHistoryTravel
  const useHover: typeof import('ahooks').useHover
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInViewport: typeof import('ahooks').useInViewport
  const useInfiniteScroll: typeof import('ahooks').useInfiniteScroll
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useInterval: typeof import('ahooks').useInterval
  const useIsomorphicLayoutEffect: typeof import('ahooks').useIsomorphicLayoutEffect
  const useKeyPress: typeof import('ahooks').useKeyPress
  const useLatest: typeof import('ahooks').useLatest
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocalStorageState: typeof import('ahooks').useLocalStorageState
  const useLockFn: typeof import('ahooks').useLockFn
  const useLongPress: typeof import('ahooks').useLongPress
  const useMap: typeof import('ahooks').useMap
  const useMemo: typeof import('react').useMemo
  const useMemoizedFn: typeof import('ahooks').useMemoizedFn
  const useMenuTabsStore: typeof import('./stores/menuTabs').useMenuTabsStore
  const useMockStore: typeof import('./stores/mock').useMockStore
  const useMount: typeof import('ahooks').useMount
  const useMouse: typeof import('ahooks').useMouse
  const useMutationObserver: typeof import('ahooks').useMutationObserver
  const useNetwork: typeof import('ahooks').useNetwork
  const useOptimistic: typeof import('react').useOptimistic
  const usePagination: typeof import('ahooks').usePagination
  const usePrevious: typeof import('ahooks').usePrevious
  const useRafInterval: typeof import('ahooks').useRafInterval
  const useRafState: typeof import('ahooks').useRafState
  const useRafTimeout: typeof import('ahooks').useRafTimeout
  const useReactive: typeof import('ahooks').useReactive
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRequest: typeof import('ahooks').useRequest
  const useResetState: typeof import('ahooks').useResetState
  const useResponsive: typeof import('ahooks').useResponsive
  const useSafeState: typeof import('ahooks').useSafeState
  const useScroll: typeof import('ahooks').useScroll
  const useSelections: typeof import('ahooks').useSelections
  const useSessionStorageState: typeof import('ahooks').useSessionStorageState
  const useSet: typeof import('ahooks').useSet
  const useSetState: typeof import('ahooks').useSetState
  const useShadcnTheme: typeof import('./config/themes/useShadcnTheme').default
  const useSize: typeof import('ahooks').useSize
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTextSelection: typeof import('ahooks').useTextSelection
  const useTheme: typeof import('ahooks').useTheme
  const useThemeStore: typeof import('./stores/theme').useThemeStore
  const useThrottle: typeof import('ahooks').useThrottle
  const useThrottleEffect: typeof import('ahooks').useThrottleEffect
  const useThrottleFn: typeof import('ahooks').useThrottleFn
  const useTimeout: typeof import('ahooks').useTimeout
  const useTitle: typeof import('ahooks').useTitle
  const useToggle: typeof import('ahooks').useToggle
  const useTrackedEffect: typeof import('ahooks').useTrackedEffect
  const useTransition: typeof import('react').useTransition
  const useTranslation: typeof import('react-i18next').useTranslation
  const useUnmount: typeof import('ahooks').useUnmount
  const useUnmountedRef: typeof import('ahooks').useUnmountedRef
  const useUpdate: typeof import('ahooks').useUpdate
  const useUpdateEffect: typeof import('ahooks').useUpdateEffect
  const useUpdateLayoutEffect: typeof import('ahooks').useUpdateLayoutEffect
  const useVirtualList: typeof import('ahooks').useVirtualList
  const useWebSocket: typeof import('ahooks').useWebSocket
  const useWhyDidYouUpdate: typeof import('ahooks').useWhyDidYouUpdate
  const useZodForm: typeof import('./utils/zod').useZodForm
  const waitForHydration: typeof import('./stores/mock').waitForHydration
}
// for type re-export
declare global {
  // @ts-ignore
  export type { MenuTabsItemProps, TargetKey } from './stores/menuTabs'
  import('./stores/menuTabs')
  // @ts-ignore
  export type { ThemeType } from './stores/theme'
  import('./stores/theme')
  // @ts-ignore
  export type { ReqPwdLogin, ResLogin, ReqChangePwd } from './domains/account'
  import('./domains/account')
  // @ts-ignore
  export type { CodeType } from './domains/constant'
  import('./domains/constant')
  // @ts-ignore
  export type { ResPublicKey } from './domains/encrypt'
  import('./domains/encrypt')
  // @ts-ignore
  export type { PagingRequest, PagingResult } from './domains/page'
  import('./domains/page')
  // @ts-ignore
  export type { ChangePwdFormValues } from './components/business/account/changePwdModal'
  import('./components/business/account/changePwdModal')
  // @ts-ignore
  export type { DictType, DictEntry, ReqDictTypeCreate, ReqDictTypeUpdate, ReqDictTypeSwitchStatus, ReqDictTypeBatchDelete, ReqDictEntryCreate, ReqDictEntryUpdate, ReqDictEntrySwitchStatus, ReqDictEntryBatchDelete, ReqDictEntryBatchCopy } from './api/dict'
  import('./api/dict')
}
