/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as loginLoginRouteImport } from './routes/(login)/login'
import { Route as AppSystemDictRouteImport } from './routes/_app/system/dict'
import { Route as AppAccountRoleRouteImport } from './routes/_app/account/role'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const loginLoginRoute = loginLoginRouteImport.update({
  id: '/(login)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSystemDictRoute = AppSystemDictRouteImport.update({
  id: '/dict',
  path: '/dict',
  getParentRoute: () => AppSystemRoute,
} as any)
const AppAccountRoleRoute = AppAccountRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AppAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof loginLoginRoute
  '/account': typeof AppAccountRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/system': typeof AppSystemRouteWithChildren
  '/account/role': typeof AppAccountRoleRoute
  '/system/dict': typeof AppSystemDictRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginLoginRoute
  '/account': typeof AppAccountRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/system': typeof AppSystemRouteWithChildren
  '/': typeof AppIndexRoute
  '/account/role': typeof AppAccountRoleRoute
  '/system/dict': typeof AppSystemDictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/(login)/login': typeof loginLoginRoute
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/system': typeof AppSystemRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/account/role': typeof AppAccountRoleRoute
  '/_app/system/dict': typeof AppSystemDictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/system'
    | '/account/role'
    | '/system/dict'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/dashboard'
    | '/system'
    | '/'
    | '/account/role'
    | '/system/dict'
  id:
    | '__root__'
    | '/_app'
    | '/(login)/login'
    | '/_app/account'
    | '/_app/dashboard'
    | '/_app/system'
    | '/_app/'
    | '/_app/account/role'
    | '/_app/system/dict'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  loginLoginRoute: typeof loginLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/(login)/login': {
      id: '/(login)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/system/dict': {
      id: '/_app/system/dict'
      path: '/dict'
      fullPath: '/system/dict'
      preLoaderRoute: typeof AppSystemDictRouteImport
      parentRoute: typeof AppSystemRoute
    }
    '/_app/account/role': {
      id: '/_app/account/role'
      path: '/role'
      fullPath: '/account/role'
      preLoaderRoute: typeof AppAccountRoleRouteImport
      parentRoute: typeof AppAccountRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountRoleRoute: typeof AppAccountRoleRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountRoleRoute: AppAccountRoleRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppSystemRouteChildren {
  AppSystemDictRoute: typeof AppSystemDictRoute
}

const AppSystemRouteChildren: AppSystemRouteChildren = {
  AppSystemDictRoute: AppSystemDictRoute,
}

const AppSystemRouteWithChildren = AppSystemRoute._addFileChildren(
  AppSystemRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppSystemRoute: typeof AppSystemRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppSystemRoute: AppSystemRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  loginLoginRoute: loginLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
