/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppLoggerRouteImport } from './routes/_app/logger'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as loginLoginRouteImport } from './routes/(login)/login'
import { Route as AppSystemLanguageRouteImport } from './routes/_app/system/language'
import { Route as AppSystemDictRouteImport } from './routes/_app/system/dict'
import { Route as AppAccountUserRouteImport } from './routes/_app/account/user'
import { Route as AppAccountRoleRouteImport } from './routes/_app/account/role'
import { Route as AppSystemResourceMenuRouteImport } from './routes/_app/system/resource.menu'
import { Route as AppSystemResourceApiRouteImport } from './routes/_app/system/resource.api'
import { Route as AppLoggerApiLogRouteImport } from './routes/_app/logger/api.log'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppLoggerRoute = AppLoggerRouteImport.update({
  id: '/logger',
  path: '/logger',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const loginLoginRoute = loginLoginRouteImport.update({
  id: '/(login)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSystemLanguageRoute = AppSystemLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppSystemRoute,
} as any)
const AppSystemDictRoute = AppSystemDictRouteImport.update({
  id: '/dict',
  path: '/dict',
  getParentRoute: () => AppSystemRoute,
} as any)
const AppAccountUserRoute = AppAccountUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountRoleRoute = AppAccountRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppSystemResourceMenuRoute = AppSystemResourceMenuRouteImport.update({
  id: '/resource/menu',
  path: '/resource/menu',
  getParentRoute: () => AppSystemRoute,
} as any)
const AppSystemResourceApiRoute = AppSystemResourceApiRouteImport.update({
  id: '/resource/api',
  path: '/resource/api',
  getParentRoute: () => AppSystemRoute,
} as any)
const AppLoggerApiLogRoute = AppLoggerApiLogRouteImport.update({
  id: '/api/log',
  path: '/api/log',
  getParentRoute: () => AppLoggerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof loginLoginRoute
  '/account': typeof AppAccountRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/logger': typeof AppLoggerRouteWithChildren
  '/system': typeof AppSystemRouteWithChildren
  '/account/role': typeof AppAccountRoleRoute
  '/account/user': typeof AppAccountUserRoute
  '/system/dict': typeof AppSystemDictRoute
  '/system/language': typeof AppSystemLanguageRoute
  '/logger/api/log': typeof AppLoggerApiLogRoute
  '/system/resource/api': typeof AppSystemResourceApiRoute
  '/system/resource/menu': typeof AppSystemResourceMenuRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginLoginRoute
  '/account': typeof AppAccountRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/logger': typeof AppLoggerRouteWithChildren
  '/system': typeof AppSystemRouteWithChildren
  '/': typeof AppIndexRoute
  '/account/role': typeof AppAccountRoleRoute
  '/account/user': typeof AppAccountUserRoute
  '/system/dict': typeof AppSystemDictRoute
  '/system/language': typeof AppSystemLanguageRoute
  '/logger/api/log': typeof AppLoggerApiLogRoute
  '/system/resource/api': typeof AppSystemResourceApiRoute
  '/system/resource/menu': typeof AppSystemResourceMenuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/(login)/login': typeof loginLoginRoute
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/logger': typeof AppLoggerRouteWithChildren
  '/_app/system': typeof AppSystemRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/account/role': typeof AppAccountRoleRoute
  '/_app/account/user': typeof AppAccountUserRoute
  '/_app/system/dict': typeof AppSystemDictRoute
  '/_app/system/language': typeof AppSystemLanguageRoute
  '/_app/logger/api/log': typeof AppLoggerApiLogRoute
  '/_app/system/resource/api': typeof AppSystemResourceApiRoute
  '/_app/system/resource/menu': typeof AppSystemResourceMenuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/logger'
    | '/system'
    | '/account/role'
    | '/account/user'
    | '/system/dict'
    | '/system/language'
    | '/logger/api/log'
    | '/system/resource/api'
    | '/system/resource/menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/dashboard'
    | '/logger'
    | '/system'
    | '/'
    | '/account/role'
    | '/account/user'
    | '/system/dict'
    | '/system/language'
    | '/logger/api/log'
    | '/system/resource/api'
    | '/system/resource/menu'
  id:
    | '__root__'
    | '/_app'
    | '/(login)/login'
    | '/_app/account'
    | '/_app/dashboard'
    | '/_app/logger'
    | '/_app/system'
    | '/_app/'
    | '/_app/account/role'
    | '/_app/account/user'
    | '/_app/system/dict'
    | '/_app/system/language'
    | '/_app/logger/api/log'
    | '/_app/system/resource/api'
    | '/_app/system/resource/menu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  loginLoginRoute: typeof loginLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logger': {
      id: '/_app/logger'
      path: '/logger'
      fullPath: '/logger'
      preLoaderRoute: typeof AppLoggerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/(login)/login': {
      id: '/(login)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/system/language': {
      id: '/_app/system/language'
      path: '/language'
      fullPath: '/system/language'
      preLoaderRoute: typeof AppSystemLanguageRouteImport
      parentRoute: typeof AppSystemRoute
    }
    '/_app/system/dict': {
      id: '/_app/system/dict'
      path: '/dict'
      fullPath: '/system/dict'
      preLoaderRoute: typeof AppSystemDictRouteImport
      parentRoute: typeof AppSystemRoute
    }
    '/_app/account/user': {
      id: '/_app/account/user'
      path: '/user'
      fullPath: '/account/user'
      preLoaderRoute: typeof AppAccountUserRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/role': {
      id: '/_app/account/role'
      path: '/role'
      fullPath: '/account/role'
      preLoaderRoute: typeof AppAccountRoleRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/system/resource/menu': {
      id: '/_app/system/resource/menu'
      path: '/resource/menu'
      fullPath: '/system/resource/menu'
      preLoaderRoute: typeof AppSystemResourceMenuRouteImport
      parentRoute: typeof AppSystemRoute
    }
    '/_app/system/resource/api': {
      id: '/_app/system/resource/api'
      path: '/resource/api'
      fullPath: '/system/resource/api'
      preLoaderRoute: typeof AppSystemResourceApiRouteImport
      parentRoute: typeof AppSystemRoute
    }
    '/_app/logger/api/log': {
      id: '/_app/logger/api/log'
      path: '/api/log'
      fullPath: '/logger/api/log'
      preLoaderRoute: typeof AppLoggerApiLogRouteImport
      parentRoute: typeof AppLoggerRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountRoleRoute: typeof AppAccountRoleRoute
  AppAccountUserRoute: typeof AppAccountUserRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountRoleRoute: AppAccountRoleRoute,
  AppAccountUserRoute: AppAccountUserRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppLoggerRouteChildren {
  AppLoggerApiLogRoute: typeof AppLoggerApiLogRoute
}

const AppLoggerRouteChildren: AppLoggerRouteChildren = {
  AppLoggerApiLogRoute: AppLoggerApiLogRoute,
}

const AppLoggerRouteWithChildren = AppLoggerRoute._addFileChildren(
  AppLoggerRouteChildren,
)

interface AppSystemRouteChildren {
  AppSystemDictRoute: typeof AppSystemDictRoute
  AppSystemLanguageRoute: typeof AppSystemLanguageRoute
  AppSystemResourceApiRoute: typeof AppSystemResourceApiRoute
  AppSystemResourceMenuRoute: typeof AppSystemResourceMenuRoute
}

const AppSystemRouteChildren: AppSystemRouteChildren = {
  AppSystemDictRoute: AppSystemDictRoute,
  AppSystemLanguageRoute: AppSystemLanguageRoute,
  AppSystemResourceApiRoute: AppSystemResourceApiRoute,
  AppSystemResourceMenuRoute: AppSystemResourceMenuRoute,
}

const AppSystemRouteWithChildren = AppSystemRoute._addFileChildren(
  AppSystemRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppLoggerRoute: typeof AppLoggerRouteWithChildren
  AppSystemRoute: typeof AppSystemRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppLoggerRoute: AppLoggerRouteWithChildren,
  AppSystemRoute: AppSystemRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  loginLoginRoute: loginLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
