// Code generated by MockGen. DO NOT EDIT.
// Source: casbin_service.go
//
// Generated by this command:
//
//	mockgen -source=casbin_service.go -destination=../mock/mock_casbin_service.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	models "admin/internal/services/orm/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCasbinService is a mock of CasbinService interface.
type MockCasbinService struct {
	ctrl     *gomock.Controller
	recorder *MockCasbinServiceMockRecorder
	isgomock struct{}
}

// MockCasbinServiceMockRecorder is the mock recorder for MockCasbinService.
type MockCasbinServiceMockRecorder struct {
	mock *MockCasbinService
}

// NewMockCasbinService creates a new mock instance.
func NewMockCasbinService(ctrl *gomock.Controller) *MockCasbinService {
	mock := &MockCasbinService{ctrl: ctrl}
	mock.recorder = &MockCasbinServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCasbinService) EXPECT() *MockCasbinServiceMockRecorder {
	return m.recorder
}

// RemoveAPIResourcePolicies mocks base method.
func (m *MockCasbinService) RemoveAPIResourcePolicies(api *models.SysResourceApi) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAPIResourcePolicies", api)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAPIResourcePolicies indicates an expected call of RemoveAPIResourcePolicies.
func (mr *MockCasbinServiceMockRecorder) RemoveAPIResourcePolicies(api any) *MockCasbinServiceRemoveAPIResourcePoliciesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAPIResourcePolicies", reflect.TypeOf((*MockCasbinService)(nil).RemoveAPIResourcePolicies), api)
	return &MockCasbinServiceRemoveAPIResourcePoliciesCall{Call: call}
}

// MockCasbinServiceRemoveAPIResourcePoliciesCall wrap *gomock.Call
type MockCasbinServiceRemoveAPIResourcePoliciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCasbinServiceRemoveAPIResourcePoliciesCall) Return(arg0 error) *MockCasbinServiceRemoveAPIResourcePoliciesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCasbinServiceRemoveAPIResourcePoliciesCall) Do(f func(*models.SysResourceApi) error) *MockCasbinServiceRemoveAPIResourcePoliciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCasbinServiceRemoveAPIResourcePoliciesCall) DoAndReturn(f func(*models.SysResourceApi) error) *MockCasbinServiceRemoveAPIResourcePoliciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SyncAPIResourcePolicies mocks base method.
func (m *MockCasbinService) SyncAPIResourcePolicies(oldAPI, newAPI *models.SysResourceApi) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncAPIResourcePolicies", oldAPI, newAPI)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncAPIResourcePolicies indicates an expected call of SyncAPIResourcePolicies.
func (mr *MockCasbinServiceMockRecorder) SyncAPIResourcePolicies(oldAPI, newAPI any) *MockCasbinServiceSyncAPIResourcePoliciesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncAPIResourcePolicies", reflect.TypeOf((*MockCasbinService)(nil).SyncAPIResourcePolicies), oldAPI, newAPI)
	return &MockCasbinServiceSyncAPIResourcePoliciesCall{Call: call}
}

// MockCasbinServiceSyncAPIResourcePoliciesCall wrap *gomock.Call
type MockCasbinServiceSyncAPIResourcePoliciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCasbinServiceSyncAPIResourcePoliciesCall) Return(arg0 error) *MockCasbinServiceSyncAPIResourcePoliciesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCasbinServiceSyncAPIResourcePoliciesCall) Do(f func(*models.SysResourceApi, *models.SysResourceApi) error) *MockCasbinServiceSyncAPIResourcePoliciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCasbinServiceSyncAPIResourcePoliciesCall) DoAndReturn(f func(*models.SysResourceApi, *models.SysResourceApi) error) *MockCasbinServiceSyncAPIResourcePoliciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SyncRoleAPIPermissions mocks base method.
func (m *MockCasbinService) SyncRoleAPIPermissions(roleCode string, oldAPIIDs, newAPIIDs []uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncRoleAPIPermissions", roleCode, oldAPIIDs, newAPIIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncRoleAPIPermissions indicates an expected call of SyncRoleAPIPermissions.
func (mr *MockCasbinServiceMockRecorder) SyncRoleAPIPermissions(roleCode, oldAPIIDs, newAPIIDs any) *MockCasbinServiceSyncRoleAPIPermissionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncRoleAPIPermissions", reflect.TypeOf((*MockCasbinService)(nil).SyncRoleAPIPermissions), roleCode, oldAPIIDs, newAPIIDs)
	return &MockCasbinServiceSyncRoleAPIPermissionsCall{Call: call}
}

// MockCasbinServiceSyncRoleAPIPermissionsCall wrap *gomock.Call
type MockCasbinServiceSyncRoleAPIPermissionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCasbinServiceSyncRoleAPIPermissionsCall) Return(arg0 error) *MockCasbinServiceSyncRoleAPIPermissionsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCasbinServiceSyncRoleAPIPermissionsCall) Do(f func(string, []uint64, []uint64) error) *MockCasbinServiceSyncRoleAPIPermissionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCasbinServiceSyncRoleAPIPermissionsCall) DoAndReturn(f func(string, []uint64, []uint64) error) *MockCasbinServiceSyncRoleAPIPermissionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SyncRoleState mocks base method.
func (m *MockCasbinService) SyncRoleState(roleID uint64, oldCode string, oldEnabled bool, newCode string, newEnabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncRoleState", roleID, oldCode, oldEnabled, newCode, newEnabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncRoleState indicates an expected call of SyncRoleState.
func (mr *MockCasbinServiceMockRecorder) SyncRoleState(roleID, oldCode, oldEnabled, newCode, newEnabled any) *MockCasbinServiceSyncRoleStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncRoleState", reflect.TypeOf((*MockCasbinService)(nil).SyncRoleState), roleID, oldCode, oldEnabled, newCode, newEnabled)
	return &MockCasbinServiceSyncRoleStateCall{Call: call}
}

// MockCasbinServiceSyncRoleStateCall wrap *gomock.Call
type MockCasbinServiceSyncRoleStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCasbinServiceSyncRoleStateCall) Return(arg0 error) *MockCasbinServiceSyncRoleStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCasbinServiceSyncRoleStateCall) Do(f func(uint64, string, bool, string, bool) error) *MockCasbinServiceSyncRoleStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCasbinServiceSyncRoleStateCall) DoAndReturn(f func(uint64, string, bool, string, bool) error) *MockCasbinServiceSyncRoleStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
