// Code generated by MockGen. DO NOT EDIT.
// Source: login_logger.go
//
// Generated by this command:
//
//	mockgen -source=login_logger.go -destination=../mock/mock_login_logger.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	handler "admin/internal/fiberc/handler"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginLogger is a mock of LoginLogger interface.
type MockLoginLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoginLoggerMockRecorder
	isgomock struct{}
}

// MockLoginLoggerMockRecorder is the mock recorder for MockLoginLogger.
type MockLoginLoggerMockRecorder struct {
	mock *MockLoginLogger
}

// NewMockLoginLogger creates a new mock instance.
func NewMockLoginLogger(ctrl *gomock.Controller) *MockLoginLogger {
	mock := &MockLoginLogger{ctrl: ctrl}
	mock.recorder = &MockLoginLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginLogger) EXPECT() *MockLoginLoggerMockRecorder {
	return m.recorder
}

// RecordPwdLogin mocks base method.
func (m *MockLoginLogger) RecordPwdLogin(ctx *handler.Ctx, username string, userID *uint64, statusCode int, success bool, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordPwdLogin", ctx, username, userID, statusCode, success, reason)
}

// RecordPwdLogin indicates an expected call of RecordPwdLogin.
func (mr *MockLoginLoggerMockRecorder) RecordPwdLogin(ctx, username, userID, statusCode, success, reason any) *MockLoginLoggerRecordPwdLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPwdLogin", reflect.TypeOf((*MockLoginLogger)(nil).RecordPwdLogin), ctx, username, userID, statusCode, success, reason)
	return &MockLoginLoggerRecordPwdLoginCall{Call: call}
}

// MockLoginLoggerRecordPwdLoginCall wrap *gomock.Call
type MockLoginLoggerRecordPwdLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoginLoggerRecordPwdLoginCall) Return() *MockLoginLoggerRecordPwdLoginCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoginLoggerRecordPwdLoginCall) Do(f func(*handler.Ctx, string, *uint64, int, bool, string)) *MockLoginLoggerRecordPwdLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoginLoggerRecordPwdLoginCall) DoAndReturn(f func(*handler.Ctx, string, *uint64, int, bool, string)) *MockLoginLoggerRecordPwdLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
