// Code generated by MockGen. DO NOT EDIT.
// Source: redis_cache.go
//
// Generated by this command:
//
//	mockgen -source=redis_cache.go -destination=../mock/mock_redis_cache.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRedisCache is a mock of RedisCache interface.
type MockRedisCache struct {
	ctrl     *gomock.Controller
	recorder *MockRedisCacheMockRecorder
	isgomock struct{}
}

// MockRedisCacheMockRecorder is the mock recorder for MockRedisCache.
type MockRedisCacheMockRecorder struct {
	mock *MockRedisCache
}

// NewMockRedisCache creates a new mock instance.
func NewMockRedisCache(ctrl *gomock.Controller) *MockRedisCache {
	mock := &MockRedisCache{ctrl: ctrl}
	mock.recorder = &MockRedisCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisCache) EXPECT() *MockRedisCacheMockRecorder {
	return m.recorder
}

// GetEncryptKeyPair mocks base method.
func (m *MockRedisCache) GetEncryptKeyPair(ctx context.Context) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptKeyPair", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetEncryptKeyPair indicates an expected call of GetEncryptKeyPair.
func (mr *MockRedisCacheMockRecorder) GetEncryptKeyPair(ctx any) *MockRedisCacheGetEncryptKeyPairCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptKeyPair", reflect.TypeOf((*MockRedisCache)(nil).GetEncryptKeyPair), ctx)
	return &MockRedisCacheGetEncryptKeyPairCall{Call: call}
}

// MockRedisCacheGetEncryptKeyPairCall wrap *gomock.Call
type MockRedisCacheGetEncryptKeyPairCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisCacheGetEncryptKeyPairCall) Return(publicKey, privateKey string, err error) *MockRedisCacheGetEncryptKeyPairCall {
	c.Call = c.Call.Return(publicKey, privateKey, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisCacheGetEncryptKeyPairCall) Do(f func(context.Context) (string, string, error)) *MockRedisCacheGetEncryptKeyPairCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisCacheGetEncryptKeyPairCall) DoAndReturn(f func(context.Context) (string, string, error)) *MockRedisCacheGetEncryptKeyPairCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetEncryptKeyPair mocks base method.
func (m *MockRedisCache) SetEncryptKeyPair(ctx context.Context, publicKey, privateKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEncryptKeyPair", ctx, publicKey, privateKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEncryptKeyPair indicates an expected call of SetEncryptKeyPair.
func (mr *MockRedisCacheMockRecorder) SetEncryptKeyPair(ctx, publicKey, privateKey any) *MockRedisCacheSetEncryptKeyPairCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEncryptKeyPair", reflect.TypeOf((*MockRedisCache)(nil).SetEncryptKeyPair), ctx, publicKey, privateKey)
	return &MockRedisCacheSetEncryptKeyPairCall{Call: call}
}

// MockRedisCacheSetEncryptKeyPairCall wrap *gomock.Call
type MockRedisCacheSetEncryptKeyPairCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRedisCacheSetEncryptKeyPairCall) Return(arg0 error) *MockRedisCacheSetEncryptKeyPairCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRedisCacheSetEncryptKeyPairCall) Do(f func(context.Context, string, string) error) *MockRedisCacheSetEncryptKeyPairCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRedisCacheSetEncryptKeyPairCall) DoAndReturn(f func(context.Context, string, string) error) *MockRedisCacheSetEncryptKeyPairCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
