// Code generated by MockGen. DO NOT EDIT.
// Source: auth_service.go
//
// Generated by this command:
//
//	mockgen -source=auth_service.go -destination=../mock/mock_auth_service.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	auth "admin/internal/auth"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// GetLoginID mocks base method.
func (m *MockAuthService) GetLoginID(token string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginID", token)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginID indicates an expected call of GetLoginID.
func (mr *MockAuthServiceMockRecorder) GetLoginID(token any) *MockAuthServiceGetLoginIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginID", reflect.TypeOf((*MockAuthService)(nil).GetLoginID), token)
	return &MockAuthServiceGetLoginIDCall{Call: call}
}

// MockAuthServiceGetLoginIDCall wrap *gomock.Call
type MockAuthServiceGetLoginIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthServiceGetLoginIDCall) Return(arg0 any, arg1 error) *MockAuthServiceGetLoginIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthServiceGetLoginIDCall) Do(f func(string) (any, error)) *MockAuthServiceGetLoginIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthServiceGetLoginIDCall) DoAndReturn(f func(string) (any, error)) *MockAuthServiceGetLoginIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Login mocks base method.
func (m *MockAuthService) Login(id uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(id any) *MockAuthServiceLoginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), id)
	return &MockAuthServiceLoginCall{Call: call}
}

// MockAuthServiceLoginCall wrap *gomock.Call
type MockAuthServiceLoginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthServiceLoginCall) Return(token string, err error) *MockAuthServiceLoginCall {
	c.Call = c.Call.Return(token, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthServiceLoginCall) Do(f func(uint64) (string, error)) *MockAuthServiceLoginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthServiceLoginCall) DoAndReturn(f func(uint64) (string, error)) *MockAuthServiceLoginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Logout mocks base method.
func (m *MockAuthService) Logout(loginID any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", loginID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(loginID any) *MockAuthServiceLogoutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), loginID)
	return &MockAuthServiceLogoutCall{Call: call}
}

// MockAuthServiceLogoutCall wrap *gomock.Call
type MockAuthServiceLogoutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthServiceLogoutCall) Return(arg0 error) *MockAuthServiceLogoutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthServiceLogoutCall) Do(f func(any) error) *MockAuthServiceLogoutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthServiceLogoutCall) DoAndReturn(f func(any) error) *MockAuthServiceLogoutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveSession mocks base method.
func (m *MockAuthService) SaveSession(loginID uint64, info *auth.SessionInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSession", loginID, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSession indicates an expected call of SaveSession.
func (mr *MockAuthServiceMockRecorder) SaveSession(loginID, info any) *MockAuthServiceSaveSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSession", reflect.TypeOf((*MockAuthService)(nil).SaveSession), loginID, info)
	return &MockAuthServiceSaveSessionCall{Call: call}
}

// MockAuthServiceSaveSessionCall wrap *gomock.Call
type MockAuthServiceSaveSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthServiceSaveSessionCall) Return(arg0 error) *MockAuthServiceSaveSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthServiceSaveSessionCall) Do(f func(uint64, *auth.SessionInfo) error) *MockAuthServiceSaveSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthServiceSaveSessionCall) DoAndReturn(f func(uint64, *auth.SessionInfo) error) *MockAuthServiceSaveSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
