// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newJobExecution(db *gorm.DB, opts ...gen.DOOption) jobExecution {
	_jobExecution := jobExecution{}

	_jobExecution.jobExecutionDo.UseDB(db, opts...)
	_jobExecution.jobExecutionDo.UseModel(&models.JobExecution{})

	tableName := _jobExecution.jobExecutionDo.TableName()
	_jobExecution.ALL = field.NewAsterisk(tableName)
	_jobExecution.ID = field.NewUint64(tableName, "id")
	_jobExecution.CreatedAt = field.NewTime(tableName, "created_at")
	_jobExecution.UpdatedAt = field.NewTime(tableName, "updated_at")
	_jobExecution.JobCode = field.NewString(tableName, "job_code")
	_jobExecution.TemporalWorkflowID = field.NewString(tableName, "temporal_workflow_id")
	_jobExecution.TemporalRunID = field.NewString(tableName, "temporal_run_id")
	_jobExecution.TriggerTime = field.NewTime(tableName, "trigger_time")
	_jobExecution.StartTime = field.NewTime(tableName, "start_time")
	_jobExecution.EndTime = field.NewTime(tableName, "end_time")
	_jobExecution.Status = field.NewString(tableName, "status")
	_jobExecution.InputJSON = field.NewField(tableName, "input_json")
	_jobExecution.ResultJSON = field.NewField(tableName, "result_json")
	_jobExecution.ErrorMessage = field.NewString(tableName, "error_message")
	_jobExecution.RetryCount = field.NewInt(tableName, "retry_count")

	_jobExecution.fillFieldMap()

	return _jobExecution
}

type jobExecution struct {
	jobExecutionDo

	ALL                field.Asterisk
	ID                 field.Uint64
	CreatedAt          field.Time
	UpdatedAt          field.Time
	JobCode            field.String
	TemporalWorkflowID field.String
	TemporalRunID      field.String
	TriggerTime        field.Time // 计划触发时间
	StartTime          field.Time
	EndTime            field.Time
	Status             field.String // RUNNING/SUCCESS/FAILED/CANCELED/TIMEOUT
	InputJSON          field.Field
	ResultJSON         field.Field
	ErrorMessage       field.String
	RetryCount         field.Int

	fieldMap map[string]field.Expr
}

func (j jobExecution) Table(newTableName string) *jobExecution {
	j.jobExecutionDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobExecution) As(alias string) *jobExecution {
	j.jobExecutionDo.DO = *(j.jobExecutionDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobExecution) updateTableName(table string) *jobExecution {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewUint64(table, "id")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")
	j.JobCode = field.NewString(table, "job_code")
	j.TemporalWorkflowID = field.NewString(table, "temporal_workflow_id")
	j.TemporalRunID = field.NewString(table, "temporal_run_id")
	j.TriggerTime = field.NewTime(table, "trigger_time")
	j.StartTime = field.NewTime(table, "start_time")
	j.EndTime = field.NewTime(table, "end_time")
	j.Status = field.NewString(table, "status")
	j.InputJSON = field.NewField(table, "input_json")
	j.ResultJSON = field.NewField(table, "result_json")
	j.ErrorMessage = field.NewString(table, "error_message")
	j.RetryCount = field.NewInt(table, "retry_count")

	j.fillFieldMap()

	return j
}

func (j *jobExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobExecution) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 14)
	j.fieldMap["id"] = j.ID
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
	j.fieldMap["job_code"] = j.JobCode
	j.fieldMap["temporal_workflow_id"] = j.TemporalWorkflowID
	j.fieldMap["temporal_run_id"] = j.TemporalRunID
	j.fieldMap["trigger_time"] = j.TriggerTime
	j.fieldMap["start_time"] = j.StartTime
	j.fieldMap["end_time"] = j.EndTime
	j.fieldMap["status"] = j.Status
	j.fieldMap["input_json"] = j.InputJSON
	j.fieldMap["result_json"] = j.ResultJSON
	j.fieldMap["error_message"] = j.ErrorMessage
	j.fieldMap["retry_count"] = j.RetryCount
}

func (j jobExecution) clone(db *gorm.DB) jobExecution {
	j.jobExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobExecution) replaceDB(db *gorm.DB) jobExecution {
	j.jobExecutionDo.ReplaceDB(db)
	return j
}

type jobExecutionDo struct{ gen.DO }

type IJobExecutionDo interface {
	gen.SubQuery
	Debug() IJobExecutionDo
	WithContext(ctx context.Context) IJobExecutionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobExecutionDo
	WriteDB() IJobExecutionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobExecutionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobExecutionDo
	Not(conds ...gen.Condition) IJobExecutionDo
	Or(conds ...gen.Condition) IJobExecutionDo
	Select(conds ...field.Expr) IJobExecutionDo
	Where(conds ...gen.Condition) IJobExecutionDo
	Order(conds ...field.Expr) IJobExecutionDo
	Distinct(cols ...field.Expr) IJobExecutionDo
	Omit(cols ...field.Expr) IJobExecutionDo
	Join(table schema.Tabler, on ...field.Expr) IJobExecutionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobExecutionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobExecutionDo
	Group(cols ...field.Expr) IJobExecutionDo
	Having(conds ...gen.Condition) IJobExecutionDo
	Limit(limit int) IJobExecutionDo
	Offset(offset int) IJobExecutionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobExecutionDo
	Unscoped() IJobExecutionDo
	Create(values ...*models.JobExecution) error
	CreateInBatches(values []*models.JobExecution, batchSize int) error
	Save(values ...*models.JobExecution) error
	First() (*models.JobExecution, error)
	Take() (*models.JobExecution, error)
	Last() (*models.JobExecution, error)
	Find() ([]*models.JobExecution, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobExecution, err error)
	FindInBatches(result *[]*models.JobExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.JobExecution) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobExecutionDo
	Assign(attrs ...field.AssignExpr) IJobExecutionDo
	Joins(fields ...field.RelationField) IJobExecutionDo
	Preload(fields ...field.RelationField) IJobExecutionDo
	FirstOrInit() (*models.JobExecution, error)
	FirstOrCreate() (*models.JobExecution, error)
	FindByPage(offset int, limit int) (result []*models.JobExecution, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobExecutionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobExecutionDo) Debug() IJobExecutionDo {
	return j.withDO(j.DO.Debug())
}

func (j jobExecutionDo) WithContext(ctx context.Context) IJobExecutionDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobExecutionDo) ReadDB() IJobExecutionDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobExecutionDo) WriteDB() IJobExecutionDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobExecutionDo) Session(config *gorm.Session) IJobExecutionDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobExecutionDo) Clauses(conds ...clause.Expression) IJobExecutionDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobExecutionDo) Returning(value interface{}, columns ...string) IJobExecutionDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobExecutionDo) Not(conds ...gen.Condition) IJobExecutionDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobExecutionDo) Or(conds ...gen.Condition) IJobExecutionDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobExecutionDo) Select(conds ...field.Expr) IJobExecutionDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobExecutionDo) Where(conds ...gen.Condition) IJobExecutionDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobExecutionDo) Order(conds ...field.Expr) IJobExecutionDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobExecutionDo) Distinct(cols ...field.Expr) IJobExecutionDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobExecutionDo) Omit(cols ...field.Expr) IJobExecutionDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobExecutionDo) Join(table schema.Tabler, on ...field.Expr) IJobExecutionDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobExecutionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobExecutionDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobExecutionDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobExecutionDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobExecutionDo) Group(cols ...field.Expr) IJobExecutionDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobExecutionDo) Having(conds ...gen.Condition) IJobExecutionDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobExecutionDo) Limit(limit int) IJobExecutionDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobExecutionDo) Offset(offset int) IJobExecutionDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobExecutionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobExecutionDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobExecutionDo) Unscoped() IJobExecutionDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobExecutionDo) Create(values ...*models.JobExecution) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobExecutionDo) CreateInBatches(values []*models.JobExecution, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobExecutionDo) Save(values ...*models.JobExecution) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobExecutionDo) First() (*models.JobExecution, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobExecution), nil
	}
}

func (j jobExecutionDo) Take() (*models.JobExecution, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobExecution), nil
	}
}

func (j jobExecutionDo) Last() (*models.JobExecution, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobExecution), nil
	}
}

func (j jobExecutionDo) Find() ([]*models.JobExecution, error) {
	result, err := j.DO.Find()
	return result.([]*models.JobExecution), err
}

func (j jobExecutionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobExecution, err error) {
	buf := make([]*models.JobExecution, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobExecutionDo) FindInBatches(result *[]*models.JobExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobExecutionDo) Attrs(attrs ...field.AssignExpr) IJobExecutionDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobExecutionDo) Assign(attrs ...field.AssignExpr) IJobExecutionDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobExecutionDo) Joins(fields ...field.RelationField) IJobExecutionDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobExecutionDo) Preload(fields ...field.RelationField) IJobExecutionDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobExecutionDo) FirstOrInit() (*models.JobExecution, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobExecution), nil
	}
}

func (j jobExecutionDo) FirstOrCreate() (*models.JobExecution, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobExecution), nil
	}
}

func (j jobExecutionDo) FindByPage(offset int, limit int) (result []*models.JobExecution, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobExecutionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobExecutionDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobExecutionDo) Delete(models ...*models.JobExecution) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobExecutionDo) withDO(do gen.Dao) *jobExecutionDo {
	j.DO = *do.(*gen.DO)
	return j
}
