// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	field2 "gorm.io/gen/field"
	"orm-crud/gormc/field"
	"orm-crud/gormc/filter"
	paging "orm-crud/gormc/pagination"
	"orm-crud/gormc/sorting"
	paginationSorting "orm-crud/pagination/sorting"
)

var (
	structuredSorting      = sorting.NewStructuredSorting()
	offsetPaginator        = paging.NewOffsetPaginator()
	pagePaginator          = paging.NewPagePaginator()
	tokenPaginator         = paging.NewTokenPaginator()
	structuredFilter       = filter.NewStructuredFilter()
	orderByStringConverter = paginationSorting.NewOrderByStringConverter()
	fieldSelector          = field.NewFieldSelector()
)

func ExprAppendSelf[T any](s1 *[]field2.AssignExpr, v *T, fn func(T) field2.AssignExpr) {
	if s1 == nil {
		return
	}
	if v != nil {
		*s1 = append(*s1, fn(*v))
	}
}
