// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysDictEntry(db *gorm.DB, opts ...gen.DOOption) sysDictEntry {
	_sysDictEntry := sysDictEntry{}

	_sysDictEntry.sysDictEntryDo.UseDB(db, opts...)
	_sysDictEntry.sysDictEntryDo.UseModel(&models.SysDictEntry{})

	tableName := _sysDictEntry.sysDictEntryDo.TableName()
	_sysDictEntry.ALL = field.NewAsterisk(tableName)
	_sysDictEntry.ID = field.NewUint64(tableName, "id")
	_sysDictEntry.CreatedAt = field.NewTime(tableName, "created_at")
	_sysDictEntry.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysDictEntry.DeletedAt = field.NewTime(tableName, "deleted_at")
	_sysDictEntry.CreatedBy = field.NewUint64(tableName, "created_by")
	_sysDictEntry.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_sysDictEntry.SortOrder = field.NewInt32(tableName, "sort_order")
	_sysDictEntry.IsEnabled = field.NewBool(tableName, "is_enabled")
	_sysDictEntry.Remark = field.NewString(tableName, "remark")
	_sysDictEntry.EntryLabel = field.NewString(tableName, "entry_label")
	_sysDictEntry.EntryValue = field.NewString(tableName, "entry_value")
	_sysDictEntry.LanguageCode = field.NewString(tableName, "language_code")
	_sysDictEntry.SysDictTypeId = field.NewUint64(tableName, "sys_dict_type_id")
	_sysDictEntry.SysDictType = sysDictEntryBelongsToSysDictType{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SysDictType", "models.SysDictType"),
		Entries: struct {
			field.RelationField
			SysDictType struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("SysDictType.Entries", "models.SysDictEntry"),
			SysDictType: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("SysDictType.Entries.SysDictType", "models.SysDictType"),
			},
		},
	}

	_sysDictEntry.fillFieldMap()

	return _sysDictEntry
}

type sysDictEntry struct {
	sysDictEntryDo

	ALL           field.Asterisk
	ID            field.Uint64
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Time
	CreatedBy     field.Uint64
	UpdatedBy     field.Uint64
	SortOrder     field.Int32
	IsEnabled     field.Bool
	Remark        field.String
	EntryLabel    field.String // 字典项的显示标签
	EntryValue    field.String // 字典项的实际值
	LanguageCode  field.String // 语言代码
	SysDictTypeId field.Uint64 // 字典类型ID
	SysDictType   sysDictEntryBelongsToSysDictType

	fieldMap map[string]field.Expr
}

func (s sysDictEntry) Table(newTableName string) *sysDictEntry {
	s.sysDictEntryDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysDictEntry) As(alias string) *sysDictEntry {
	s.sysDictEntryDo.DO = *(s.sysDictEntryDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysDictEntry) updateTableName(table string) *sysDictEntry {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewTime(table, "deleted_at")
	s.CreatedBy = field.NewUint64(table, "created_by")
	s.UpdatedBy = field.NewUint64(table, "updated_by")
	s.SortOrder = field.NewInt32(table, "sort_order")
	s.IsEnabled = field.NewBool(table, "is_enabled")
	s.Remark = field.NewString(table, "remark")
	s.EntryLabel = field.NewString(table, "entry_label")
	s.EntryValue = field.NewString(table, "entry_value")
	s.LanguageCode = field.NewString(table, "language_code")
	s.SysDictTypeId = field.NewUint64(table, "sys_dict_type_id")

	s.fillFieldMap()

	return s
}

func (s *sysDictEntry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysDictEntry) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["sort_order"] = s.SortOrder
	s.fieldMap["is_enabled"] = s.IsEnabled
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["entry_label"] = s.EntryLabel
	s.fieldMap["entry_value"] = s.EntryValue
	s.fieldMap["language_code"] = s.LanguageCode
	s.fieldMap["sys_dict_type_id"] = s.SysDictTypeId

}

func (s sysDictEntry) clone(db *gorm.DB) sysDictEntry {
	s.sysDictEntryDo.ReplaceConnPool(db.Statement.ConnPool)
	s.SysDictType.db = db.Session(&gorm.Session{Initialized: true})
	s.SysDictType.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sysDictEntry) replaceDB(db *gorm.DB) sysDictEntry {
	s.sysDictEntryDo.ReplaceDB(db)
	s.SysDictType.db = db.Session(&gorm.Session{})
	return s
}

type sysDictEntryBelongsToSysDictType struct {
	db *gorm.DB

	field.RelationField

	Entries struct {
		field.RelationField
		SysDictType struct {
			field.RelationField
		}
	}
}

func (a sysDictEntryBelongsToSysDictType) Where(conds ...field.Expr) *sysDictEntryBelongsToSysDictType {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysDictEntryBelongsToSysDictType) WithContext(ctx context.Context) *sysDictEntryBelongsToSysDictType {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysDictEntryBelongsToSysDictType) Session(session *gorm.Session) *sysDictEntryBelongsToSysDictType {
	a.db = a.db.Session(session)
	return &a
}

func (a sysDictEntryBelongsToSysDictType) Model(m *models.SysDictEntry) *sysDictEntryBelongsToSysDictTypeTx {
	return &sysDictEntryBelongsToSysDictTypeTx{a.db.Model(m).Association(a.Name())}
}

func (a sysDictEntryBelongsToSysDictType) Unscoped() *sysDictEntryBelongsToSysDictType {
	a.db = a.db.Unscoped()
	return &a
}

type sysDictEntryBelongsToSysDictTypeTx struct{ tx *gorm.Association }

func (a sysDictEntryBelongsToSysDictTypeTx) Find() (result *models.SysDictType, err error) {
	return result, a.tx.Find(&result)
}

func (a sysDictEntryBelongsToSysDictTypeTx) Append(values ...*models.SysDictType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysDictEntryBelongsToSysDictTypeTx) Replace(values ...*models.SysDictType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysDictEntryBelongsToSysDictTypeTx) Delete(values ...*models.SysDictType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysDictEntryBelongsToSysDictTypeTx) Clear() error {
	return a.tx.Clear()
}

func (a sysDictEntryBelongsToSysDictTypeTx) Count() int64 {
	return a.tx.Count()
}

func (a sysDictEntryBelongsToSysDictTypeTx) Unscoped() *sysDictEntryBelongsToSysDictTypeTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysDictEntryDo struct{ gen.DO }

type ISysDictEntryDo interface {
	gen.SubQuery
	Debug() ISysDictEntryDo
	WithContext(ctx context.Context) ISysDictEntryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysDictEntryDo
	WriteDB() ISysDictEntryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysDictEntryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysDictEntryDo
	Not(conds ...gen.Condition) ISysDictEntryDo
	Or(conds ...gen.Condition) ISysDictEntryDo
	Select(conds ...field.Expr) ISysDictEntryDo
	Where(conds ...gen.Condition) ISysDictEntryDo
	Order(conds ...field.Expr) ISysDictEntryDo
	Distinct(cols ...field.Expr) ISysDictEntryDo
	Omit(cols ...field.Expr) ISysDictEntryDo
	Join(table schema.Tabler, on ...field.Expr) ISysDictEntryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysDictEntryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysDictEntryDo
	Group(cols ...field.Expr) ISysDictEntryDo
	Having(conds ...gen.Condition) ISysDictEntryDo
	Limit(limit int) ISysDictEntryDo
	Offset(offset int) ISysDictEntryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDictEntryDo
	Unscoped() ISysDictEntryDo
	Create(values ...*models.SysDictEntry) error
	CreateInBatches(values []*models.SysDictEntry, batchSize int) error
	Save(values ...*models.SysDictEntry) error
	First() (*models.SysDictEntry, error)
	Take() (*models.SysDictEntry, error)
	Last() (*models.SysDictEntry, error)
	Find() ([]*models.SysDictEntry, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysDictEntry, err error)
	FindInBatches(result *[]*models.SysDictEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysDictEntry) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysDictEntryDo
	Assign(attrs ...field.AssignExpr) ISysDictEntryDo
	Joins(fields ...field.RelationField) ISysDictEntryDo
	Preload(fields ...field.RelationField) ISysDictEntryDo
	FirstOrInit() (*models.SysDictEntry, error)
	FirstOrCreate() (*models.SysDictEntry, error)
	FindByPage(offset int, limit int) (result []*models.SysDictEntry, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysDictEntryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysDictEntryDo) Debug() ISysDictEntryDo {
	return s.withDO(s.DO.Debug())
}

func (s sysDictEntryDo) WithContext(ctx context.Context) ISysDictEntryDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysDictEntryDo) ReadDB() ISysDictEntryDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysDictEntryDo) WriteDB() ISysDictEntryDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysDictEntryDo) Session(config *gorm.Session) ISysDictEntryDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysDictEntryDo) Clauses(conds ...clause.Expression) ISysDictEntryDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysDictEntryDo) Returning(value interface{}, columns ...string) ISysDictEntryDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysDictEntryDo) Not(conds ...gen.Condition) ISysDictEntryDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysDictEntryDo) Or(conds ...gen.Condition) ISysDictEntryDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysDictEntryDo) Select(conds ...field.Expr) ISysDictEntryDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysDictEntryDo) Where(conds ...gen.Condition) ISysDictEntryDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysDictEntryDo) Order(conds ...field.Expr) ISysDictEntryDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysDictEntryDo) Distinct(cols ...field.Expr) ISysDictEntryDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysDictEntryDo) Omit(cols ...field.Expr) ISysDictEntryDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysDictEntryDo) Join(table schema.Tabler, on ...field.Expr) ISysDictEntryDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysDictEntryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysDictEntryDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysDictEntryDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysDictEntryDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysDictEntryDo) Group(cols ...field.Expr) ISysDictEntryDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysDictEntryDo) Having(conds ...gen.Condition) ISysDictEntryDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysDictEntryDo) Limit(limit int) ISysDictEntryDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysDictEntryDo) Offset(offset int) ISysDictEntryDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysDictEntryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDictEntryDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysDictEntryDo) Unscoped() ISysDictEntryDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysDictEntryDo) Create(values ...*models.SysDictEntry) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysDictEntryDo) CreateInBatches(values []*models.SysDictEntry, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysDictEntryDo) Save(values ...*models.SysDictEntry) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysDictEntryDo) First() (*models.SysDictEntry, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysDictEntry), nil
	}
}

func (s sysDictEntryDo) Take() (*models.SysDictEntry, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysDictEntry), nil
	}
}

func (s sysDictEntryDo) Last() (*models.SysDictEntry, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysDictEntry), nil
	}
}

func (s sysDictEntryDo) Find() ([]*models.SysDictEntry, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysDictEntry), err
}

func (s sysDictEntryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysDictEntry, err error) {
	buf := make([]*models.SysDictEntry, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysDictEntryDo) FindInBatches(result *[]*models.SysDictEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysDictEntryDo) Attrs(attrs ...field.AssignExpr) ISysDictEntryDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysDictEntryDo) Assign(attrs ...field.AssignExpr) ISysDictEntryDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysDictEntryDo) Joins(fields ...field.RelationField) ISysDictEntryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysDictEntryDo) Preload(fields ...field.RelationField) ISysDictEntryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysDictEntryDo) FirstOrInit() (*models.SysDictEntry, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysDictEntry), nil
	}
}

func (s sysDictEntryDo) FirstOrCreate() (*models.SysDictEntry, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysDictEntry), nil
	}
}

func (s sysDictEntryDo) FindByPage(offset int, limit int) (result []*models.SysDictEntry, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysDictEntryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysDictEntryDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysDictEntryDo) Delete(models ...*models.SysDictEntry) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysDictEntryDo) withDO(do gen.Dao) *sysDictEntryDo {
	s.DO = *do.(*gen.DO)
	return s
}
