// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysApiLog(db *gorm.DB, opts ...gen.DOOption) sysApiLog {
	_sysApiLog := sysApiLog{}

	_sysApiLog.sysApiLogDo.UseDB(db, opts...)
	_sysApiLog.sysApiLogDo.UseModel(&models.SysApiLog{})

	tableName := _sysApiLog.sysApiLogDo.TableName()
	_sysApiLog.ALL = field.NewAsterisk(tableName)
	_sysApiLog.ID = field.NewUint64(tableName, "id")
	_sysApiLog.CreatedAt = field.NewTime(tableName, "created_at")
	_sysApiLog.RequestID = field.NewString(tableName, "request_id")
	_sysApiLog.Method = field.NewString(tableName, "method")
	_sysApiLog.Module = field.NewString(tableName, "module")
	_sysApiLog.Path = field.NewString(tableName, "path")
	_sysApiLog.Referer = field.NewString(tableName, "referer")
	_sysApiLog.BeforeChange = field.NewString(tableName, "before_change")
	_sysApiLog.AfterChange = field.NewString(tableName, "after_change")
	_sysApiLog.FormatChange = field.NewString(tableName, "format_change")
	_sysApiLog.RequestURI = field.NewString(tableName, "request_uri")
	_sysApiLog.RequestBody = field.NewString(tableName, "request_body")
	_sysApiLog.RequestHeader = field.NewString(tableName, "request_header")
	_sysApiLog.Response = field.NewString(tableName, "response")
	_sysApiLog.CostTime = field.NewInt64(tableName, "cost_time")
	_sysApiLog.SysUserID = field.NewUint64(tableName, "sys_user_id")
	_sysApiLog.ClientIP = field.NewString(tableName, "client_ip")
	_sysApiLog.StatusCode = field.NewInt(tableName, "status_code")
	_sysApiLog.Reason = field.NewString(tableName, "reason")
	_sysApiLog.Success = field.NewBool(tableName, "success")
	_sysApiLog.Location = field.NewString(tableName, "location")
	_sysApiLog.UserAgent = field.NewString(tableName, "user_agent")
	_sysApiLog.BrowserName = field.NewString(tableName, "browser_name")
	_sysApiLog.BrowserVersion = field.NewString(tableName, "browser_version")
	_sysApiLog.ClientID = field.NewString(tableName, "client_id")
	_sysApiLog.ClientName = field.NewString(tableName, "client_name")
	_sysApiLog.OSName = field.NewString(tableName, "os_name")
	_sysApiLog.OSVersion = field.NewString(tableName, "os_version")
	_sysApiLog.SysUser = sysApiLogBelongsToSysUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SysUser", "models.SysUser"),
	}

	_sysApiLog.fillFieldMap()

	return _sysApiLog
}

type sysApiLog struct {
	sysApiLogDo

	ALL            field.Asterisk
	ID             field.Uint64
	CreatedAt      field.Time
	RequestID      field.String // 请求ID
	Method         field.String // 请求方法
	Module         field.String // 模块
	Path           field.String // 请求路径
	Referer        field.String // 请求源
	BeforeChange   field.String // 变更前内容
	AfterChange    field.String // 变更后内容
	FormatChange   field.String // 格式化变化内容
	RequestURI     field.String // 请求URI
	RequestBody    field.String // 请求体
	RequestHeader  field.String // 请求头
	Response       field.String // 响应信息
	CostTime       field.Int64  // 操作耗时
	SysUserID      field.Uint64 // 操作者用户ID
	ClientIP       field.String // 操作者IP
	StatusCode     field.Int    // 状态码
	Reason         field.String // 操作失败原因
	Success        field.Bool   // 操作成功
	Location       field.String // 操作地理位置
	UserAgent      field.String // 浏览器的用户代理信息
	BrowserName    field.String // 浏览器名称
	BrowserVersion field.String // 浏览器版本
	ClientID       field.String // 客户端ID
	ClientName     field.String // 客户端名称
	OSName         field.String // 操作系统名称
	OSVersion      field.String // 操作系统版本
	SysUser        sysApiLogBelongsToSysUser

	fieldMap map[string]field.Expr
}

func (s sysApiLog) Table(newTableName string) *sysApiLog {
	s.sysApiLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysApiLog) As(alias string) *sysApiLog {
	s.sysApiLogDo.DO = *(s.sysApiLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysApiLog) updateTableName(table string) *sysApiLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.RequestID = field.NewString(table, "request_id")
	s.Method = field.NewString(table, "method")
	s.Module = field.NewString(table, "module")
	s.Path = field.NewString(table, "path")
	s.Referer = field.NewString(table, "referer")
	s.BeforeChange = field.NewString(table, "before_change")
	s.AfterChange = field.NewString(table, "after_change")
	s.FormatChange = field.NewString(table, "format_change")
	s.RequestURI = field.NewString(table, "request_uri")
	s.RequestBody = field.NewString(table, "request_body")
	s.RequestHeader = field.NewString(table, "request_header")
	s.Response = field.NewString(table, "response")
	s.CostTime = field.NewInt64(table, "cost_time")
	s.SysUserID = field.NewUint64(table, "sys_user_id")
	s.ClientIP = field.NewString(table, "client_ip")
	s.StatusCode = field.NewInt(table, "status_code")
	s.Reason = field.NewString(table, "reason")
	s.Success = field.NewBool(table, "success")
	s.Location = field.NewString(table, "location")
	s.UserAgent = field.NewString(table, "user_agent")
	s.BrowserName = field.NewString(table, "browser_name")
	s.BrowserVersion = field.NewString(table, "browser_version")
	s.ClientID = field.NewString(table, "client_id")
	s.ClientName = field.NewString(table, "client_name")
	s.OSName = field.NewString(table, "os_name")
	s.OSVersion = field.NewString(table, "os_version")

	s.fillFieldMap()

	return s
}

func (s *sysApiLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysApiLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 29)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["request_id"] = s.RequestID
	s.fieldMap["method"] = s.Method
	s.fieldMap["module"] = s.Module
	s.fieldMap["path"] = s.Path
	s.fieldMap["referer"] = s.Referer
	s.fieldMap["before_change"] = s.BeforeChange
	s.fieldMap["after_change"] = s.AfterChange
	s.fieldMap["format_change"] = s.FormatChange
	s.fieldMap["request_uri"] = s.RequestURI
	s.fieldMap["request_body"] = s.RequestBody
	s.fieldMap["request_header"] = s.RequestHeader
	s.fieldMap["response"] = s.Response
	s.fieldMap["cost_time"] = s.CostTime
	s.fieldMap["sys_user_id"] = s.SysUserID
	s.fieldMap["client_ip"] = s.ClientIP
	s.fieldMap["status_code"] = s.StatusCode
	s.fieldMap["reason"] = s.Reason
	s.fieldMap["success"] = s.Success
	s.fieldMap["location"] = s.Location
	s.fieldMap["user_agent"] = s.UserAgent
	s.fieldMap["browser_name"] = s.BrowserName
	s.fieldMap["browser_version"] = s.BrowserVersion
	s.fieldMap["client_id"] = s.ClientID
	s.fieldMap["client_name"] = s.ClientName
	s.fieldMap["os_name"] = s.OSName
	s.fieldMap["os_version"] = s.OSVersion

}

func (s sysApiLog) clone(db *gorm.DB) sysApiLog {
	s.sysApiLogDo.ReplaceConnPool(db.Statement.ConnPool)
	s.SysUser.db = db.Session(&gorm.Session{Initialized: true})
	s.SysUser.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sysApiLog) replaceDB(db *gorm.DB) sysApiLog {
	s.sysApiLogDo.ReplaceDB(db)
	s.SysUser.db = db.Session(&gorm.Session{})
	return s
}

type sysApiLogBelongsToSysUser struct {
	db *gorm.DB

	field.RelationField
}

func (a sysApiLogBelongsToSysUser) Where(conds ...field.Expr) *sysApiLogBelongsToSysUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysApiLogBelongsToSysUser) WithContext(ctx context.Context) *sysApiLogBelongsToSysUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysApiLogBelongsToSysUser) Session(session *gorm.Session) *sysApiLogBelongsToSysUser {
	a.db = a.db.Session(session)
	return &a
}

func (a sysApiLogBelongsToSysUser) Model(m *models.SysApiLog) *sysApiLogBelongsToSysUserTx {
	return &sysApiLogBelongsToSysUserTx{a.db.Model(m).Association(a.Name())}
}

func (a sysApiLogBelongsToSysUser) Unscoped() *sysApiLogBelongsToSysUser {
	a.db = a.db.Unscoped()
	return &a
}

type sysApiLogBelongsToSysUserTx struct{ tx *gorm.Association }

func (a sysApiLogBelongsToSysUserTx) Find() (result *models.SysUser, err error) {
	return result, a.tx.Find(&result)
}

func (a sysApiLogBelongsToSysUserTx) Append(values ...*models.SysUser) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysApiLogBelongsToSysUserTx) Replace(values ...*models.SysUser) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysApiLogBelongsToSysUserTx) Delete(values ...*models.SysUser) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysApiLogBelongsToSysUserTx) Clear() error {
	return a.tx.Clear()
}

func (a sysApiLogBelongsToSysUserTx) Count() int64 {
	return a.tx.Count()
}

func (a sysApiLogBelongsToSysUserTx) Unscoped() *sysApiLogBelongsToSysUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysApiLogDo struct{ gen.DO }

type ISysApiLogDo interface {
	gen.SubQuery
	Debug() ISysApiLogDo
	WithContext(ctx context.Context) ISysApiLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysApiLogDo
	WriteDB() ISysApiLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysApiLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysApiLogDo
	Not(conds ...gen.Condition) ISysApiLogDo
	Or(conds ...gen.Condition) ISysApiLogDo
	Select(conds ...field.Expr) ISysApiLogDo
	Where(conds ...gen.Condition) ISysApiLogDo
	Order(conds ...field.Expr) ISysApiLogDo
	Distinct(cols ...field.Expr) ISysApiLogDo
	Omit(cols ...field.Expr) ISysApiLogDo
	Join(table schema.Tabler, on ...field.Expr) ISysApiLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysApiLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysApiLogDo
	Group(cols ...field.Expr) ISysApiLogDo
	Having(conds ...gen.Condition) ISysApiLogDo
	Limit(limit int) ISysApiLogDo
	Offset(offset int) ISysApiLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysApiLogDo
	Unscoped() ISysApiLogDo
	Create(values ...*models.SysApiLog) error
	CreateInBatches(values []*models.SysApiLog, batchSize int) error
	Save(values ...*models.SysApiLog) error
	First() (*models.SysApiLog, error)
	Take() (*models.SysApiLog, error)
	Last() (*models.SysApiLog, error)
	Find() ([]*models.SysApiLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysApiLog, err error)
	FindInBatches(result *[]*models.SysApiLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysApiLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysApiLogDo
	Assign(attrs ...field.AssignExpr) ISysApiLogDo
	Joins(fields ...field.RelationField) ISysApiLogDo
	Preload(fields ...field.RelationField) ISysApiLogDo
	FirstOrInit() (*models.SysApiLog, error)
	FirstOrCreate() (*models.SysApiLog, error)
	FindByPage(offset int, limit int) (result []*models.SysApiLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysApiLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysApiLogDo) Debug() ISysApiLogDo {
	return s.withDO(s.DO.Debug())
}

func (s sysApiLogDo) WithContext(ctx context.Context) ISysApiLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysApiLogDo) ReadDB() ISysApiLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysApiLogDo) WriteDB() ISysApiLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysApiLogDo) Session(config *gorm.Session) ISysApiLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysApiLogDo) Clauses(conds ...clause.Expression) ISysApiLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysApiLogDo) Returning(value interface{}, columns ...string) ISysApiLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysApiLogDo) Not(conds ...gen.Condition) ISysApiLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysApiLogDo) Or(conds ...gen.Condition) ISysApiLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysApiLogDo) Select(conds ...field.Expr) ISysApiLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysApiLogDo) Where(conds ...gen.Condition) ISysApiLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysApiLogDo) Order(conds ...field.Expr) ISysApiLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysApiLogDo) Distinct(cols ...field.Expr) ISysApiLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysApiLogDo) Omit(cols ...field.Expr) ISysApiLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysApiLogDo) Join(table schema.Tabler, on ...field.Expr) ISysApiLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysApiLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysApiLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysApiLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysApiLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysApiLogDo) Group(cols ...field.Expr) ISysApiLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysApiLogDo) Having(conds ...gen.Condition) ISysApiLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysApiLogDo) Limit(limit int) ISysApiLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysApiLogDo) Offset(offset int) ISysApiLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysApiLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysApiLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysApiLogDo) Unscoped() ISysApiLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysApiLogDo) Create(values ...*models.SysApiLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysApiLogDo) CreateInBatches(values []*models.SysApiLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysApiLogDo) Save(values ...*models.SysApiLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysApiLogDo) First() (*models.SysApiLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysApiLog), nil
	}
}

func (s sysApiLogDo) Take() (*models.SysApiLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysApiLog), nil
	}
}

func (s sysApiLogDo) Last() (*models.SysApiLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysApiLog), nil
	}
}

func (s sysApiLogDo) Find() ([]*models.SysApiLog, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysApiLog), err
}

func (s sysApiLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysApiLog, err error) {
	buf := make([]*models.SysApiLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysApiLogDo) FindInBatches(result *[]*models.SysApiLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysApiLogDo) Attrs(attrs ...field.AssignExpr) ISysApiLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysApiLogDo) Assign(attrs ...field.AssignExpr) ISysApiLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysApiLogDo) Joins(fields ...field.RelationField) ISysApiLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysApiLogDo) Preload(fields ...field.RelationField) ISysApiLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysApiLogDo) FirstOrInit() (*models.SysApiLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysApiLog), nil
	}
}

func (s sysApiLogDo) FirstOrCreate() (*models.SysApiLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysApiLog), nil
	}
}

func (s sysApiLogDo) FindByPage(offset int, limit int) (result []*models.SysApiLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysApiLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysApiLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysApiLogDo) Delete(models ...*models.SysApiLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysApiLogDo) withDO(do gen.Dao) *sysApiLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
