// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysRoleMenu(db *gorm.DB, opts ...gen.DOOption) sysRoleMenu {
	_sysRoleMenu := sysRoleMenu{}

	_sysRoleMenu.sysRoleMenuDo.UseDB(db, opts...)
	_sysRoleMenu.sysRoleMenuDo.UseModel(&models.SysRoleMenu{})

	tableName := _sysRoleMenu.sysRoleMenuDo.TableName()
	_sysRoleMenu.ALL = field.NewAsterisk(tableName)
	_sysRoleMenu.ID = field.NewUint64(tableName, "id")
	_sysRoleMenu.CreatedAt = field.NewTime(tableName, "created_at")
	_sysRoleMenu.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysRoleMenu.CreatedBy = field.NewUint64(tableName, "created_by")
	_sysRoleMenu.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_sysRoleMenu.DeletedBy = field.NewUint64(tableName, "deleted_by")
	_sysRoleMenu.RoleID = field.NewUint64(tableName, "role_id")
	_sysRoleMenu.MenuID = field.NewUint64(tableName, "menu_id")
	_sysRoleMenu.DeletedAt = field.NewUint(tableName, "deleted_at")
	_sysRoleMenu.SysRole = sysRoleMenuBelongsToSysRole{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SysRole", "models.SysRole"),
		ParentSysRole: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("SysRole.ParentSysRole", "models.SysRole"),
		},
		Children: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("SysRole.Children", "models.SysRole"),
		},
	}

	_sysRoleMenu.SysResourceMenu = sysRoleMenuBelongsToSysResourceMenu{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SysResourceMenu", "models.SysResourceMenu"),
		ParentSysResourceMenu: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("SysResourceMenu.ParentSysResourceMenu", "models.SysResourceMenu"),
		},
	}

	_sysRoleMenu.fillFieldMap()

	return _sysRoleMenu
}

type sysRoleMenu struct {
	sysRoleMenuDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	CreatedBy field.Uint64
	UpdatedBy field.Uint64
	DeletedBy field.Uint64
	RoleID    field.Uint64 // 角色ID
	MenuID    field.Uint64 // 菜单资源ID
	DeletedAt field.Uint
	SysRole   sysRoleMenuBelongsToSysRole

	SysResourceMenu sysRoleMenuBelongsToSysResourceMenu

	fieldMap map[string]field.Expr
}

func (s sysRoleMenu) Table(newTableName string) *sysRoleMenu {
	s.sysRoleMenuDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRoleMenu) As(alias string) *sysRoleMenu {
	s.sysRoleMenuDo.DO = *(s.sysRoleMenuDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRoleMenu) updateTableName(table string) *sysRoleMenu {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CreatedBy = field.NewUint64(table, "created_by")
	s.UpdatedBy = field.NewUint64(table, "updated_by")
	s.DeletedBy = field.NewUint64(table, "deleted_by")
	s.RoleID = field.NewUint64(table, "role_id")
	s.MenuID = field.NewUint64(table, "menu_id")
	s.DeletedAt = field.NewUint(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sysRoleMenu) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRoleMenu) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["deleted_by"] = s.DeletedBy
	s.fieldMap["role_id"] = s.RoleID
	s.fieldMap["menu_id"] = s.MenuID
	s.fieldMap["deleted_at"] = s.DeletedAt

}

func (s sysRoleMenu) clone(db *gorm.DB) sysRoleMenu {
	s.sysRoleMenuDo.ReplaceConnPool(db.Statement.ConnPool)
	s.SysRole.db = db.Session(&gorm.Session{Initialized: true})
	s.SysRole.db.Statement.ConnPool = db.Statement.ConnPool
	s.SysResourceMenu.db = db.Session(&gorm.Session{Initialized: true})
	s.SysResourceMenu.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sysRoleMenu) replaceDB(db *gorm.DB) sysRoleMenu {
	s.sysRoleMenuDo.ReplaceDB(db)
	s.SysRole.db = db.Session(&gorm.Session{})
	s.SysResourceMenu.db = db.Session(&gorm.Session{})
	return s
}

type sysRoleMenuBelongsToSysRole struct {
	db *gorm.DB

	field.RelationField

	ParentSysRole struct {
		field.RelationField
	}
	Children struct {
		field.RelationField
	}
}

func (a sysRoleMenuBelongsToSysRole) Where(conds ...field.Expr) *sysRoleMenuBelongsToSysRole {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysRoleMenuBelongsToSysRole) WithContext(ctx context.Context) *sysRoleMenuBelongsToSysRole {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysRoleMenuBelongsToSysRole) Session(session *gorm.Session) *sysRoleMenuBelongsToSysRole {
	a.db = a.db.Session(session)
	return &a
}

func (a sysRoleMenuBelongsToSysRole) Model(m *models.SysRoleMenu) *sysRoleMenuBelongsToSysRoleTx {
	return &sysRoleMenuBelongsToSysRoleTx{a.db.Model(m).Association(a.Name())}
}

func (a sysRoleMenuBelongsToSysRole) Unscoped() *sysRoleMenuBelongsToSysRole {
	a.db = a.db.Unscoped()
	return &a
}

type sysRoleMenuBelongsToSysRoleTx struct{ tx *gorm.Association }

func (a sysRoleMenuBelongsToSysRoleTx) Find() (result *models.SysRole, err error) {
	return result, a.tx.Find(&result)
}

func (a sysRoleMenuBelongsToSysRoleTx) Append(values ...*models.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysRoleMenuBelongsToSysRoleTx) Replace(values ...*models.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysRoleMenuBelongsToSysRoleTx) Delete(values ...*models.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysRoleMenuBelongsToSysRoleTx) Clear() error {
	return a.tx.Clear()
}

func (a sysRoleMenuBelongsToSysRoleTx) Count() int64 {
	return a.tx.Count()
}

func (a sysRoleMenuBelongsToSysRoleTx) Unscoped() *sysRoleMenuBelongsToSysRoleTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysRoleMenuBelongsToSysResourceMenu struct {
	db *gorm.DB

	field.RelationField

	ParentSysResourceMenu struct {
		field.RelationField
	}
}

func (a sysRoleMenuBelongsToSysResourceMenu) Where(conds ...field.Expr) *sysRoleMenuBelongsToSysResourceMenu {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysRoleMenuBelongsToSysResourceMenu) WithContext(ctx context.Context) *sysRoleMenuBelongsToSysResourceMenu {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysRoleMenuBelongsToSysResourceMenu) Session(session *gorm.Session) *sysRoleMenuBelongsToSysResourceMenu {
	a.db = a.db.Session(session)
	return &a
}

func (a sysRoleMenuBelongsToSysResourceMenu) Model(m *models.SysRoleMenu) *sysRoleMenuBelongsToSysResourceMenuTx {
	return &sysRoleMenuBelongsToSysResourceMenuTx{a.db.Model(m).Association(a.Name())}
}

func (a sysRoleMenuBelongsToSysResourceMenu) Unscoped() *sysRoleMenuBelongsToSysResourceMenu {
	a.db = a.db.Unscoped()
	return &a
}

type sysRoleMenuBelongsToSysResourceMenuTx struct{ tx *gorm.Association }

func (a sysRoleMenuBelongsToSysResourceMenuTx) Find() (result *models.SysResourceMenu, err error) {
	return result, a.tx.Find(&result)
}

func (a sysRoleMenuBelongsToSysResourceMenuTx) Append(values ...*models.SysResourceMenu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysRoleMenuBelongsToSysResourceMenuTx) Replace(values ...*models.SysResourceMenu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysRoleMenuBelongsToSysResourceMenuTx) Delete(values ...*models.SysResourceMenu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysRoleMenuBelongsToSysResourceMenuTx) Clear() error {
	return a.tx.Clear()
}

func (a sysRoleMenuBelongsToSysResourceMenuTx) Count() int64 {
	return a.tx.Count()
}

func (a sysRoleMenuBelongsToSysResourceMenuTx) Unscoped() *sysRoleMenuBelongsToSysResourceMenuTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysRoleMenuDo struct{ gen.DO }

type ISysRoleMenuDo interface {
	gen.SubQuery
	Debug() ISysRoleMenuDo
	WithContext(ctx context.Context) ISysRoleMenuDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysRoleMenuDo
	WriteDB() ISysRoleMenuDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysRoleMenuDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysRoleMenuDo
	Not(conds ...gen.Condition) ISysRoleMenuDo
	Or(conds ...gen.Condition) ISysRoleMenuDo
	Select(conds ...field.Expr) ISysRoleMenuDo
	Where(conds ...gen.Condition) ISysRoleMenuDo
	Order(conds ...field.Expr) ISysRoleMenuDo
	Distinct(cols ...field.Expr) ISysRoleMenuDo
	Omit(cols ...field.Expr) ISysRoleMenuDo
	Join(table schema.Tabler, on ...field.Expr) ISysRoleMenuDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleMenuDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleMenuDo
	Group(cols ...field.Expr) ISysRoleMenuDo
	Having(conds ...gen.Condition) ISysRoleMenuDo
	Limit(limit int) ISysRoleMenuDo
	Offset(offset int) ISysRoleMenuDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleMenuDo
	Unscoped() ISysRoleMenuDo
	Create(values ...*models.SysRoleMenu) error
	CreateInBatches(values []*models.SysRoleMenu, batchSize int) error
	Save(values ...*models.SysRoleMenu) error
	First() (*models.SysRoleMenu, error)
	Take() (*models.SysRoleMenu, error)
	Last() (*models.SysRoleMenu, error)
	Find() ([]*models.SysRoleMenu, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysRoleMenu, err error)
	FindInBatches(result *[]*models.SysRoleMenu, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysRoleMenu) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysRoleMenuDo
	Assign(attrs ...field.AssignExpr) ISysRoleMenuDo
	Joins(fields ...field.RelationField) ISysRoleMenuDo
	Preload(fields ...field.RelationField) ISysRoleMenuDo
	FirstOrInit() (*models.SysRoleMenu, error)
	FirstOrCreate() (*models.SysRoleMenu, error)
	FindByPage(offset int, limit int) (result []*models.SysRoleMenu, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysRoleMenuDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysRoleMenuDo) Debug() ISysRoleMenuDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRoleMenuDo) WithContext(ctx context.Context) ISysRoleMenuDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRoleMenuDo) ReadDB() ISysRoleMenuDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRoleMenuDo) WriteDB() ISysRoleMenuDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRoleMenuDo) Session(config *gorm.Session) ISysRoleMenuDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysRoleMenuDo) Clauses(conds ...clause.Expression) ISysRoleMenuDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRoleMenuDo) Returning(value interface{}, columns ...string) ISysRoleMenuDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRoleMenuDo) Not(conds ...gen.Condition) ISysRoleMenuDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRoleMenuDo) Or(conds ...gen.Condition) ISysRoleMenuDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRoleMenuDo) Select(conds ...field.Expr) ISysRoleMenuDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRoleMenuDo) Where(conds ...gen.Condition) ISysRoleMenuDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRoleMenuDo) Order(conds ...field.Expr) ISysRoleMenuDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRoleMenuDo) Distinct(cols ...field.Expr) ISysRoleMenuDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRoleMenuDo) Omit(cols ...field.Expr) ISysRoleMenuDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRoleMenuDo) Join(table schema.Tabler, on ...field.Expr) ISysRoleMenuDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRoleMenuDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleMenuDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRoleMenuDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleMenuDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRoleMenuDo) Group(cols ...field.Expr) ISysRoleMenuDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRoleMenuDo) Having(conds ...gen.Condition) ISysRoleMenuDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRoleMenuDo) Limit(limit int) ISysRoleMenuDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRoleMenuDo) Offset(offset int) ISysRoleMenuDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRoleMenuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleMenuDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRoleMenuDo) Unscoped() ISysRoleMenuDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRoleMenuDo) Create(values ...*models.SysRoleMenu) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRoleMenuDo) CreateInBatches(values []*models.SysRoleMenu, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRoleMenuDo) Save(values ...*models.SysRoleMenu) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRoleMenuDo) First() (*models.SysRoleMenu, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysRoleMenu), nil
	}
}

func (s sysRoleMenuDo) Take() (*models.SysRoleMenu, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysRoleMenu), nil
	}
}

func (s sysRoleMenuDo) Last() (*models.SysRoleMenu, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysRoleMenu), nil
	}
}

func (s sysRoleMenuDo) Find() ([]*models.SysRoleMenu, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysRoleMenu), err
}

func (s sysRoleMenuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysRoleMenu, err error) {
	buf := make([]*models.SysRoleMenu, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRoleMenuDo) FindInBatches(result *[]*models.SysRoleMenu, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRoleMenuDo) Attrs(attrs ...field.AssignExpr) ISysRoleMenuDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRoleMenuDo) Assign(attrs ...field.AssignExpr) ISysRoleMenuDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRoleMenuDo) Joins(fields ...field.RelationField) ISysRoleMenuDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRoleMenuDo) Preload(fields ...field.RelationField) ISysRoleMenuDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRoleMenuDo) FirstOrInit() (*models.SysRoleMenu, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysRoleMenu), nil
	}
}

func (s sysRoleMenuDo) FirstOrCreate() (*models.SysRoleMenu, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysRoleMenu), nil
	}
}

func (s sysRoleMenuDo) FindByPage(offset int, limit int) (result []*models.SysRoleMenu, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRoleMenuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRoleMenuDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRoleMenuDo) Delete(models ...*models.SysRoleMenu) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRoleMenuDo) withDO(do gen.Dao) *sysRoleMenuDo {
	s.DO = *do.(*gen.DO)
	return s
}
