// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysLanguageType(db *gorm.DB, opts ...gen.DOOption) sysLanguageType {
	_sysLanguageType := sysLanguageType{}

	_sysLanguageType.sysLanguageTypeDo.UseDB(db, opts...)
	_sysLanguageType.sysLanguageTypeDo.UseModel(&models.SysLanguageType{})

	tableName := _sysLanguageType.sysLanguageTypeDo.TableName()
	_sysLanguageType.ALL = field.NewAsterisk(tableName)
	_sysLanguageType.ID = field.NewUint64(tableName, "id")
	_sysLanguageType.CreatedAt = field.NewTime(tableName, "created_at")
	_sysLanguageType.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysLanguageType.CreatedBy = field.NewUint64(tableName, "created_by")
	_sysLanguageType.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_sysLanguageType.SortOrder = field.NewInt32(tableName, "sort_order")
	_sysLanguageType.IsEnabled = field.NewBool(tableName, "is_enabled")
	_sysLanguageType.DeletedAt = field.NewUint(tableName, "deleted_at")
	_sysLanguageType.TypeCode = field.NewString(tableName, "type_code")
	_sysLanguageType.TypeName = field.NewString(tableName, "type_name")
	_sysLanguageType.IsDefault = field.NewBool(tableName, "is_default")
	_sysLanguageType.Entries = sysLanguageTypeHasManyEntries{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Entries", "models.SysLanguageEntry"),
		SysLanguageType: struct {
			field.RelationField
			Entries struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Entries.SysLanguageType", "models.SysLanguageType"),
			Entries: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Entries.SysLanguageType.Entries", "models.SysLanguageEntry"),
			},
		},
	}

	_sysLanguageType.fillFieldMap()

	return _sysLanguageType
}

type sysLanguageType struct {
	sysLanguageTypeDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	CreatedBy field.Uint64
	UpdatedBy field.Uint64
	SortOrder field.Int32
	IsEnabled field.Bool
	DeletedAt field.Uint
	TypeCode  field.String // 标准语言代码
	TypeName  field.String // 语言名称
	IsDefault field.Bool   // 是否为默认语言
	Entries   sysLanguageTypeHasManyEntries

	fieldMap map[string]field.Expr
}

func (s sysLanguageType) Table(newTableName string) *sysLanguageType {
	s.sysLanguageTypeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysLanguageType) As(alias string) *sysLanguageType {
	s.sysLanguageTypeDo.DO = *(s.sysLanguageTypeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysLanguageType) updateTableName(table string) *sysLanguageType {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CreatedBy = field.NewUint64(table, "created_by")
	s.UpdatedBy = field.NewUint64(table, "updated_by")
	s.SortOrder = field.NewInt32(table, "sort_order")
	s.IsEnabled = field.NewBool(table, "is_enabled")
	s.DeletedAt = field.NewUint(table, "deleted_at")
	s.TypeCode = field.NewString(table, "type_code")
	s.TypeName = field.NewString(table, "type_name")
	s.IsDefault = field.NewBool(table, "is_default")

	s.fillFieldMap()

	return s
}

func (s *sysLanguageType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysLanguageType) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["sort_order"] = s.SortOrder
	s.fieldMap["is_enabled"] = s.IsEnabled
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["type_code"] = s.TypeCode
	s.fieldMap["type_name"] = s.TypeName
	s.fieldMap["is_default"] = s.IsDefault

}

func (s sysLanguageType) clone(db *gorm.DB) sysLanguageType {
	s.sysLanguageTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Entries.db = db.Session(&gorm.Session{Initialized: true})
	s.Entries.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sysLanguageType) replaceDB(db *gorm.DB) sysLanguageType {
	s.sysLanguageTypeDo.ReplaceDB(db)
	s.Entries.db = db.Session(&gorm.Session{})
	return s
}

type sysLanguageTypeHasManyEntries struct {
	db *gorm.DB

	field.RelationField

	SysLanguageType struct {
		field.RelationField
		Entries struct {
			field.RelationField
		}
	}
}

func (a sysLanguageTypeHasManyEntries) Where(conds ...field.Expr) *sysLanguageTypeHasManyEntries {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysLanguageTypeHasManyEntries) WithContext(ctx context.Context) *sysLanguageTypeHasManyEntries {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysLanguageTypeHasManyEntries) Session(session *gorm.Session) *sysLanguageTypeHasManyEntries {
	a.db = a.db.Session(session)
	return &a
}

func (a sysLanguageTypeHasManyEntries) Model(m *models.SysLanguageType) *sysLanguageTypeHasManyEntriesTx {
	return &sysLanguageTypeHasManyEntriesTx{a.db.Model(m).Association(a.Name())}
}

func (a sysLanguageTypeHasManyEntries) Unscoped() *sysLanguageTypeHasManyEntries {
	a.db = a.db.Unscoped()
	return &a
}

type sysLanguageTypeHasManyEntriesTx struct{ tx *gorm.Association }

func (a sysLanguageTypeHasManyEntriesTx) Find() (result []*models.SysLanguageEntry, err error) {
	return result, a.tx.Find(&result)
}

func (a sysLanguageTypeHasManyEntriesTx) Append(values ...*models.SysLanguageEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysLanguageTypeHasManyEntriesTx) Replace(values ...*models.SysLanguageEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysLanguageTypeHasManyEntriesTx) Delete(values ...*models.SysLanguageEntry) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysLanguageTypeHasManyEntriesTx) Clear() error {
	return a.tx.Clear()
}

func (a sysLanguageTypeHasManyEntriesTx) Count() int64 {
	return a.tx.Count()
}

func (a sysLanguageTypeHasManyEntriesTx) Unscoped() *sysLanguageTypeHasManyEntriesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysLanguageTypeDo struct{ gen.DO }

type ISysLanguageTypeDo interface {
	gen.SubQuery
	Debug() ISysLanguageTypeDo
	WithContext(ctx context.Context) ISysLanguageTypeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysLanguageTypeDo
	WriteDB() ISysLanguageTypeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysLanguageTypeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysLanguageTypeDo
	Not(conds ...gen.Condition) ISysLanguageTypeDo
	Or(conds ...gen.Condition) ISysLanguageTypeDo
	Select(conds ...field.Expr) ISysLanguageTypeDo
	Where(conds ...gen.Condition) ISysLanguageTypeDo
	Order(conds ...field.Expr) ISysLanguageTypeDo
	Distinct(cols ...field.Expr) ISysLanguageTypeDo
	Omit(cols ...field.Expr) ISysLanguageTypeDo
	Join(table schema.Tabler, on ...field.Expr) ISysLanguageTypeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysLanguageTypeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysLanguageTypeDo
	Group(cols ...field.Expr) ISysLanguageTypeDo
	Having(conds ...gen.Condition) ISysLanguageTypeDo
	Limit(limit int) ISysLanguageTypeDo
	Offset(offset int) ISysLanguageTypeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLanguageTypeDo
	Unscoped() ISysLanguageTypeDo
	Create(values ...*models.SysLanguageType) error
	CreateInBatches(values []*models.SysLanguageType, batchSize int) error
	Save(values ...*models.SysLanguageType) error
	First() (*models.SysLanguageType, error)
	Take() (*models.SysLanguageType, error)
	Last() (*models.SysLanguageType, error)
	Find() ([]*models.SysLanguageType, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysLanguageType, err error)
	FindInBatches(result *[]*models.SysLanguageType, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysLanguageType) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysLanguageTypeDo
	Assign(attrs ...field.AssignExpr) ISysLanguageTypeDo
	Joins(fields ...field.RelationField) ISysLanguageTypeDo
	Preload(fields ...field.RelationField) ISysLanguageTypeDo
	FirstOrInit() (*models.SysLanguageType, error)
	FirstOrCreate() (*models.SysLanguageType, error)
	FindByPage(offset int, limit int) (result []*models.SysLanguageType, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysLanguageTypeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysLanguageTypeDo) Debug() ISysLanguageTypeDo {
	return s.withDO(s.DO.Debug())
}

func (s sysLanguageTypeDo) WithContext(ctx context.Context) ISysLanguageTypeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysLanguageTypeDo) ReadDB() ISysLanguageTypeDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysLanguageTypeDo) WriteDB() ISysLanguageTypeDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysLanguageTypeDo) Session(config *gorm.Session) ISysLanguageTypeDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysLanguageTypeDo) Clauses(conds ...clause.Expression) ISysLanguageTypeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysLanguageTypeDo) Returning(value interface{}, columns ...string) ISysLanguageTypeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysLanguageTypeDo) Not(conds ...gen.Condition) ISysLanguageTypeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysLanguageTypeDo) Or(conds ...gen.Condition) ISysLanguageTypeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysLanguageTypeDo) Select(conds ...field.Expr) ISysLanguageTypeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysLanguageTypeDo) Where(conds ...gen.Condition) ISysLanguageTypeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysLanguageTypeDo) Order(conds ...field.Expr) ISysLanguageTypeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysLanguageTypeDo) Distinct(cols ...field.Expr) ISysLanguageTypeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysLanguageTypeDo) Omit(cols ...field.Expr) ISysLanguageTypeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysLanguageTypeDo) Join(table schema.Tabler, on ...field.Expr) ISysLanguageTypeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysLanguageTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysLanguageTypeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysLanguageTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysLanguageTypeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysLanguageTypeDo) Group(cols ...field.Expr) ISysLanguageTypeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysLanguageTypeDo) Having(conds ...gen.Condition) ISysLanguageTypeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysLanguageTypeDo) Limit(limit int) ISysLanguageTypeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysLanguageTypeDo) Offset(offset int) ISysLanguageTypeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysLanguageTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLanguageTypeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysLanguageTypeDo) Unscoped() ISysLanguageTypeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysLanguageTypeDo) Create(values ...*models.SysLanguageType) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysLanguageTypeDo) CreateInBatches(values []*models.SysLanguageType, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysLanguageTypeDo) Save(values ...*models.SysLanguageType) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysLanguageTypeDo) First() (*models.SysLanguageType, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguageType), nil
	}
}

func (s sysLanguageTypeDo) Take() (*models.SysLanguageType, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguageType), nil
	}
}

func (s sysLanguageTypeDo) Last() (*models.SysLanguageType, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguageType), nil
	}
}

func (s sysLanguageTypeDo) Find() ([]*models.SysLanguageType, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysLanguageType), err
}

func (s sysLanguageTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysLanguageType, err error) {
	buf := make([]*models.SysLanguageType, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysLanguageTypeDo) FindInBatches(result *[]*models.SysLanguageType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysLanguageTypeDo) Attrs(attrs ...field.AssignExpr) ISysLanguageTypeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysLanguageTypeDo) Assign(attrs ...field.AssignExpr) ISysLanguageTypeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysLanguageTypeDo) Joins(fields ...field.RelationField) ISysLanguageTypeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysLanguageTypeDo) Preload(fields ...field.RelationField) ISysLanguageTypeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysLanguageTypeDo) FirstOrInit() (*models.SysLanguageType, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguageType), nil
	}
}

func (s sysLanguageTypeDo) FirstOrCreate() (*models.SysLanguageType, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguageType), nil
	}
}

func (s sysLanguageTypeDo) FindByPage(offset int, limit int) (result []*models.SysLanguageType, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysLanguageTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysLanguageTypeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysLanguageTypeDo) Delete(models ...*models.SysLanguageType) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysLanguageTypeDo) withDO(do gen.Dao) *sysLanguageTypeDo {
	s.DO = *do.(*gen.DO)
	return s
}
