// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysResourceMenu(db *gorm.DB, opts ...gen.DOOption) sysResourceMenu {
	_sysResourceMenu := sysResourceMenu{}

	_sysResourceMenu.sysResourceMenuDo.UseDB(db, opts...)
	_sysResourceMenu.sysResourceMenuDo.UseModel(&models.SysResourceMenu{})

	tableName := _sysResourceMenu.sysResourceMenuDo.TableName()
	_sysResourceMenu.ALL = field.NewAsterisk(tableName)
	_sysResourceMenu.ID = field.NewUint64(tableName, "id")
	_sysResourceMenu.CreatedAt = field.NewTime(tableName, "created_at")
	_sysResourceMenu.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysResourceMenu.CreatedBy = field.NewUint64(tableName, "created_by")
	_sysResourceMenu.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_sysResourceMenu.DeletedBy = field.NewUint64(tableName, "deleted_by")
	_sysResourceMenu.Remark = field.NewString(tableName, "remark")
	_sysResourceMenu.SortOrder = field.NewInt32(tableName, "sort_order")
	_sysResourceMenu.Metadata = field.NewField(tableName, "metadata")
	_sysResourceMenu.IsEnabled = field.NewBool(tableName, "is_enabled")
	_sysResourceMenu.DeletedAt = field.NewUint(tableName, "deleted_at")
	_sysResourceMenu.MenuType = field.NewString(tableName, "menu_type")
	_sysResourceMenu.Path = field.NewString(tableName, "path")
	_sysResourceMenu.Redirect = field.NewString(tableName, "redirect")
	_sysResourceMenu.Alias_ = field.NewString(tableName, "alias")
	_sysResourceMenu.Name = field.NewString(tableName, "name")
	_sysResourceMenu.Component = field.NewString(tableName, "component")
	_sysResourceMenu.ParentID = field.NewUint64(tableName, "parent_id")
	_sysResourceMenu.TreePath = field.NewString(tableName, "tree_path")

	_sysResourceMenu.fillFieldMap()

	return _sysResourceMenu
}

type sysResourceMenu struct {
	sysResourceMenuDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	CreatedBy field.Uint64
	UpdatedBy field.Uint64
	DeletedBy field.Uint64
	Remark    field.String
	SortOrder field.Int32
	Metadata  field.Field
	IsEnabled field.Bool
	DeletedAt field.Uint
	MenuType  field.String // 菜单类型 CATALOG: 目录 MENU: 菜单 BUTTON: 按钮 EMBEDDED: 内嵌 LINK: 外链
	Path      field.String // 路径，类型为按钮时为操作名
	Redirect  field.String // 重定向地址
	Alias_    field.String // 路由别名
	Name      field.String // 路由命名
	Component field.String // 前端页面组件
	ParentID  field.Uint64 // 父级ID
	TreePath  field.String // 节点路径

	fieldMap map[string]field.Expr
}

func (s sysResourceMenu) Table(newTableName string) *sysResourceMenu {
	s.sysResourceMenuDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysResourceMenu) As(alias string) *sysResourceMenu {
	s.sysResourceMenuDo.DO = *(s.sysResourceMenuDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysResourceMenu) updateTableName(table string) *sysResourceMenu {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CreatedBy = field.NewUint64(table, "created_by")
	s.UpdatedBy = field.NewUint64(table, "updated_by")
	s.DeletedBy = field.NewUint64(table, "deleted_by")
	s.Remark = field.NewString(table, "remark")
	s.SortOrder = field.NewInt32(table, "sort_order")
	s.Metadata = field.NewField(table, "metadata")
	s.IsEnabled = field.NewBool(table, "is_enabled")
	s.DeletedAt = field.NewUint(table, "deleted_at")
	s.MenuType = field.NewString(table, "menu_type")
	s.Path = field.NewString(table, "path")
	s.Redirect = field.NewString(table, "redirect")
	s.Alias_ = field.NewString(table, "alias")
	s.Name = field.NewString(table, "name")
	s.Component = field.NewString(table, "component")
	s.ParentID = field.NewUint64(table, "parent_id")
	s.TreePath = field.NewString(table, "tree_path")

	s.fillFieldMap()

	return s
}

func (s *sysResourceMenu) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysResourceMenu) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 19)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["deleted_by"] = s.DeletedBy
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["sort_order"] = s.SortOrder
	s.fieldMap["metadata"] = s.Metadata
	s.fieldMap["is_enabled"] = s.IsEnabled
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["menu_type"] = s.MenuType
	s.fieldMap["path"] = s.Path
	s.fieldMap["redirect"] = s.Redirect
	s.fieldMap["alias"] = s.Alias_
	s.fieldMap["name"] = s.Name
	s.fieldMap["component"] = s.Component
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["tree_path"] = s.TreePath
}

func (s sysResourceMenu) clone(db *gorm.DB) sysResourceMenu {
	s.sysResourceMenuDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysResourceMenu) replaceDB(db *gorm.DB) sysResourceMenu {
	s.sysResourceMenuDo.ReplaceDB(db)
	return s
}

type sysResourceMenuDo struct{ gen.DO }

type ISysResourceMenuDo interface {
	gen.SubQuery
	Debug() ISysResourceMenuDo
	WithContext(ctx context.Context) ISysResourceMenuDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysResourceMenuDo
	WriteDB() ISysResourceMenuDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysResourceMenuDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysResourceMenuDo
	Not(conds ...gen.Condition) ISysResourceMenuDo
	Or(conds ...gen.Condition) ISysResourceMenuDo
	Select(conds ...field.Expr) ISysResourceMenuDo
	Where(conds ...gen.Condition) ISysResourceMenuDo
	Order(conds ...field.Expr) ISysResourceMenuDo
	Distinct(cols ...field.Expr) ISysResourceMenuDo
	Omit(cols ...field.Expr) ISysResourceMenuDo
	Join(table schema.Tabler, on ...field.Expr) ISysResourceMenuDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysResourceMenuDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysResourceMenuDo
	Group(cols ...field.Expr) ISysResourceMenuDo
	Having(conds ...gen.Condition) ISysResourceMenuDo
	Limit(limit int) ISysResourceMenuDo
	Offset(offset int) ISysResourceMenuDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysResourceMenuDo
	Unscoped() ISysResourceMenuDo
	Create(values ...*models.SysResourceMenu) error
	CreateInBatches(values []*models.SysResourceMenu, batchSize int) error
	Save(values ...*models.SysResourceMenu) error
	First() (*models.SysResourceMenu, error)
	Take() (*models.SysResourceMenu, error)
	Last() (*models.SysResourceMenu, error)
	Find() ([]*models.SysResourceMenu, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysResourceMenu, err error)
	FindInBatches(result *[]*models.SysResourceMenu, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysResourceMenu) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysResourceMenuDo
	Assign(attrs ...field.AssignExpr) ISysResourceMenuDo
	Joins(fields ...field.RelationField) ISysResourceMenuDo
	Preload(fields ...field.RelationField) ISysResourceMenuDo
	FirstOrInit() (*models.SysResourceMenu, error)
	FirstOrCreate() (*models.SysResourceMenu, error)
	FindByPage(offset int, limit int) (result []*models.SysResourceMenu, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysResourceMenuDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysResourceMenuDo) Debug() ISysResourceMenuDo {
	return s.withDO(s.DO.Debug())
}

func (s sysResourceMenuDo) WithContext(ctx context.Context) ISysResourceMenuDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysResourceMenuDo) ReadDB() ISysResourceMenuDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysResourceMenuDo) WriteDB() ISysResourceMenuDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysResourceMenuDo) Session(config *gorm.Session) ISysResourceMenuDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysResourceMenuDo) Clauses(conds ...clause.Expression) ISysResourceMenuDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysResourceMenuDo) Returning(value interface{}, columns ...string) ISysResourceMenuDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysResourceMenuDo) Not(conds ...gen.Condition) ISysResourceMenuDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysResourceMenuDo) Or(conds ...gen.Condition) ISysResourceMenuDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysResourceMenuDo) Select(conds ...field.Expr) ISysResourceMenuDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysResourceMenuDo) Where(conds ...gen.Condition) ISysResourceMenuDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysResourceMenuDo) Order(conds ...field.Expr) ISysResourceMenuDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysResourceMenuDo) Distinct(cols ...field.Expr) ISysResourceMenuDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysResourceMenuDo) Omit(cols ...field.Expr) ISysResourceMenuDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysResourceMenuDo) Join(table schema.Tabler, on ...field.Expr) ISysResourceMenuDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysResourceMenuDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysResourceMenuDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysResourceMenuDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysResourceMenuDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysResourceMenuDo) Group(cols ...field.Expr) ISysResourceMenuDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysResourceMenuDo) Having(conds ...gen.Condition) ISysResourceMenuDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysResourceMenuDo) Limit(limit int) ISysResourceMenuDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysResourceMenuDo) Offset(offset int) ISysResourceMenuDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysResourceMenuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysResourceMenuDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysResourceMenuDo) Unscoped() ISysResourceMenuDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysResourceMenuDo) Create(values ...*models.SysResourceMenu) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysResourceMenuDo) CreateInBatches(values []*models.SysResourceMenu, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysResourceMenuDo) Save(values ...*models.SysResourceMenu) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysResourceMenuDo) First() (*models.SysResourceMenu, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceMenu), nil
	}
}

func (s sysResourceMenuDo) Take() (*models.SysResourceMenu, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceMenu), nil
	}
}

func (s sysResourceMenuDo) Last() (*models.SysResourceMenu, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceMenu), nil
	}
}

func (s sysResourceMenuDo) Find() ([]*models.SysResourceMenu, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysResourceMenu), err
}

func (s sysResourceMenuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysResourceMenu, err error) {
	buf := make([]*models.SysResourceMenu, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysResourceMenuDo) FindInBatches(result *[]*models.SysResourceMenu, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysResourceMenuDo) Attrs(attrs ...field.AssignExpr) ISysResourceMenuDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysResourceMenuDo) Assign(attrs ...field.AssignExpr) ISysResourceMenuDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysResourceMenuDo) Joins(fields ...field.RelationField) ISysResourceMenuDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysResourceMenuDo) Preload(fields ...field.RelationField) ISysResourceMenuDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysResourceMenuDo) FirstOrInit() (*models.SysResourceMenu, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceMenu), nil
	}
}

func (s sysResourceMenuDo) FirstOrCreate() (*models.SysResourceMenu, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceMenu), nil
	}
}

func (s sysResourceMenuDo) FindByPage(offset int, limit int) (result []*models.SysResourceMenu, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysResourceMenuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysResourceMenuDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysResourceMenuDo) Delete(models ...*models.SysResourceMenu) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysResourceMenuDo) withDO(do gen.Dao) *sysResourceMenuDo {
	s.DO = *do.(*gen.DO)
	return s
}
