// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysResource(db *gorm.DB, opts ...gen.DOOption) sysResource {
	_sysResource := sysResource{}

	_sysResource.sysResourceDo.UseDB(db, opts...)
	_sysResource.sysResourceDo.UseModel(&models.SysResource{})

	tableName := _sysResource.sysResourceDo.TableName()
	_sysResource.ALL = field.NewAsterisk(tableName)
	_sysResource.ID = field.NewUint64(tableName, "id")
	_sysResource.CreatedAt = field.NewTime(tableName, "created_at")
	_sysResource.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysResource.CreatedBy = field.NewUint64(tableName, "created_by")
	_sysResource.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_sysResource.IsEnabled = field.NewBool(tableName, "is_enabled")
	_sysResource.Remark = field.NewString(tableName, "remark")
	_sysResource.Metadata = field.NewField(tableName, "metadata")
	_sysResource.DeletedAt = field.NewUint(tableName, "deleted_at")
	_sysResource.ResourceType = field.NewString(tableName, "resource_type")
	_sysResource.ResourceCode = field.NewString(tableName, "resource_code")

	_sysResource.fillFieldMap()

	return _sysResource
}

type sysResource struct {
	sysResourceDo

	ALL          field.Asterisk
	ID           field.Uint64
	CreatedAt    field.Time
	UpdatedAt    field.Time
	CreatedBy    field.Uint64
	UpdatedBy    field.Uint64
	IsEnabled    field.Bool
	Remark       field.String
	Metadata     field.Field
	DeletedAt    field.Uint
	ResourceType field.String // 资源类型: api / data / menu / component
	ResourceCode field.String // 资源唯一标识

	fieldMap map[string]field.Expr
}

func (s sysResource) Table(newTableName string) *sysResource {
	s.sysResourceDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysResource) As(alias string) *sysResource {
	s.sysResourceDo.DO = *(s.sysResourceDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysResource) updateTableName(table string) *sysResource {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CreatedBy = field.NewUint64(table, "created_by")
	s.UpdatedBy = field.NewUint64(table, "updated_by")
	s.IsEnabled = field.NewBool(table, "is_enabled")
	s.Remark = field.NewString(table, "remark")
	s.Metadata = field.NewField(table, "metadata")
	s.DeletedAt = field.NewUint(table, "deleted_at")
	s.ResourceType = field.NewString(table, "resource_type")
	s.ResourceCode = field.NewString(table, "resource_code")

	s.fillFieldMap()

	return s
}

func (s *sysResource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysResource) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["is_enabled"] = s.IsEnabled
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["metadata"] = s.Metadata
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["resource_type"] = s.ResourceType
	s.fieldMap["resource_code"] = s.ResourceCode
}

func (s sysResource) clone(db *gorm.DB) sysResource {
	s.sysResourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysResource) replaceDB(db *gorm.DB) sysResource {
	s.sysResourceDo.ReplaceDB(db)
	return s
}

type sysResourceDo struct{ gen.DO }

type ISysResourceDo interface {
	gen.SubQuery
	Debug() ISysResourceDo
	WithContext(ctx context.Context) ISysResourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysResourceDo
	WriteDB() ISysResourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysResourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysResourceDo
	Not(conds ...gen.Condition) ISysResourceDo
	Or(conds ...gen.Condition) ISysResourceDo
	Select(conds ...field.Expr) ISysResourceDo
	Where(conds ...gen.Condition) ISysResourceDo
	Order(conds ...field.Expr) ISysResourceDo
	Distinct(cols ...field.Expr) ISysResourceDo
	Omit(cols ...field.Expr) ISysResourceDo
	Join(table schema.Tabler, on ...field.Expr) ISysResourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysResourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysResourceDo
	Group(cols ...field.Expr) ISysResourceDo
	Having(conds ...gen.Condition) ISysResourceDo
	Limit(limit int) ISysResourceDo
	Offset(offset int) ISysResourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysResourceDo
	Unscoped() ISysResourceDo
	Create(values ...*models.SysResource) error
	CreateInBatches(values []*models.SysResource, batchSize int) error
	Save(values ...*models.SysResource) error
	First() (*models.SysResource, error)
	Take() (*models.SysResource, error)
	Last() (*models.SysResource, error)
	Find() ([]*models.SysResource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysResource, err error)
	FindInBatches(result *[]*models.SysResource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysResource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysResourceDo
	Assign(attrs ...field.AssignExpr) ISysResourceDo
	Joins(fields ...field.RelationField) ISysResourceDo
	Preload(fields ...field.RelationField) ISysResourceDo
	FirstOrInit() (*models.SysResource, error)
	FirstOrCreate() (*models.SysResource, error)
	FindByPage(offset int, limit int) (result []*models.SysResource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysResourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysResourceDo) Debug() ISysResourceDo {
	return s.withDO(s.DO.Debug())
}

func (s sysResourceDo) WithContext(ctx context.Context) ISysResourceDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysResourceDo) ReadDB() ISysResourceDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysResourceDo) WriteDB() ISysResourceDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysResourceDo) Session(config *gorm.Session) ISysResourceDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysResourceDo) Clauses(conds ...clause.Expression) ISysResourceDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysResourceDo) Returning(value interface{}, columns ...string) ISysResourceDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysResourceDo) Not(conds ...gen.Condition) ISysResourceDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysResourceDo) Or(conds ...gen.Condition) ISysResourceDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysResourceDo) Select(conds ...field.Expr) ISysResourceDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysResourceDo) Where(conds ...gen.Condition) ISysResourceDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysResourceDo) Order(conds ...field.Expr) ISysResourceDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysResourceDo) Distinct(cols ...field.Expr) ISysResourceDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysResourceDo) Omit(cols ...field.Expr) ISysResourceDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysResourceDo) Join(table schema.Tabler, on ...field.Expr) ISysResourceDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysResourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysResourceDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysResourceDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysResourceDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysResourceDo) Group(cols ...field.Expr) ISysResourceDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysResourceDo) Having(conds ...gen.Condition) ISysResourceDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysResourceDo) Limit(limit int) ISysResourceDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysResourceDo) Offset(offset int) ISysResourceDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysResourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysResourceDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysResourceDo) Unscoped() ISysResourceDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysResourceDo) Create(values ...*models.SysResource) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysResourceDo) CreateInBatches(values []*models.SysResource, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysResourceDo) Save(values ...*models.SysResource) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysResourceDo) First() (*models.SysResource, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResource), nil
	}
}

func (s sysResourceDo) Take() (*models.SysResource, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResource), nil
	}
}

func (s sysResourceDo) Last() (*models.SysResource, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResource), nil
	}
}

func (s sysResourceDo) Find() ([]*models.SysResource, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysResource), err
}

func (s sysResourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysResource, err error) {
	buf := make([]*models.SysResource, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysResourceDo) FindInBatches(result *[]*models.SysResource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysResourceDo) Attrs(attrs ...field.AssignExpr) ISysResourceDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysResourceDo) Assign(attrs ...field.AssignExpr) ISysResourceDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysResourceDo) Joins(fields ...field.RelationField) ISysResourceDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysResourceDo) Preload(fields ...field.RelationField) ISysResourceDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysResourceDo) FirstOrInit() (*models.SysResource, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResource), nil
	}
}

func (s sysResourceDo) FirstOrCreate() (*models.SysResource, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResource), nil
	}
}

func (s sysResourceDo) FindByPage(offset int, limit int) (result []*models.SysResource, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysResourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysResourceDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysResourceDo) Delete(models ...*models.SysResource) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysResourceDo) withDO(do gen.Dao) *sysResourceDo {
	s.DO = *do.(*gen.DO)
	return s
}
