// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysResourceApi(db *gorm.DB, opts ...gen.DOOption) sysResourceApi {
	_sysResourceApi := sysResourceApi{}

	_sysResourceApi.sysResourceApiDo.UseDB(db, opts...)
	_sysResourceApi.sysResourceApiDo.UseModel(&models.SysResourceApi{})

	tableName := _sysResourceApi.sysResourceApiDo.TableName()
	_sysResourceApi.ALL = field.NewAsterisk(tableName)
	_sysResourceApi.ID = field.NewUint64(tableName, "id")
	_sysResourceApi.CreatedAt = field.NewTime(tableName, "created_at")
	_sysResourceApi.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysResourceApi.SortOrder = field.NewInt32(tableName, "sort_order")
	_sysResourceApi.CreatedBy = field.NewUint64(tableName, "created_by")
	_sysResourceApi.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_sysResourceApi.DeletedBy = field.NewUint64(tableName, "deleted_by")
	_sysResourceApi.Remark = field.NewString(tableName, "remark")
	_sysResourceApi.IsEnabled = field.NewBool(tableName, "is_enabled")
	_sysResourceApi.DeletedAt = field.NewUint(tableName, "deleted_at")
	_sysResourceApi.Module = field.NewString(tableName, "module")
	_sysResourceApi.Path = field.NewString(tableName, "path")
	_sysResourceApi.Method = field.NewString(tableName, "method")

	_sysResourceApi.fillFieldMap()

	return _sysResourceApi
}

type sysResourceApi struct {
	sysResourceApiDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	SortOrder field.Int32
	CreatedBy field.Uint64
	UpdatedBy field.Uint64
	DeletedBy field.Uint64
	Remark    field.String
	IsEnabled field.Bool
	DeletedAt field.Uint
	Module    field.String // 所属业务模块
	Path      field.String // 接口路径模板
	Method    field.String // 请求方法

	fieldMap map[string]field.Expr
}

func (s sysResourceApi) Table(newTableName string) *sysResourceApi {
	s.sysResourceApiDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysResourceApi) As(alias string) *sysResourceApi {
	s.sysResourceApiDo.DO = *(s.sysResourceApiDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysResourceApi) updateTableName(table string) *sysResourceApi {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.SortOrder = field.NewInt32(table, "sort_order")
	s.CreatedBy = field.NewUint64(table, "created_by")
	s.UpdatedBy = field.NewUint64(table, "updated_by")
	s.DeletedBy = field.NewUint64(table, "deleted_by")
	s.Remark = field.NewString(table, "remark")
	s.IsEnabled = field.NewBool(table, "is_enabled")
	s.DeletedAt = field.NewUint(table, "deleted_at")
	s.Module = field.NewString(table, "module")
	s.Path = field.NewString(table, "path")
	s.Method = field.NewString(table, "method")

	s.fillFieldMap()

	return s
}

func (s *sysResourceApi) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysResourceApi) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["sort_order"] = s.SortOrder
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["deleted_by"] = s.DeletedBy
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["is_enabled"] = s.IsEnabled
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["module"] = s.Module
	s.fieldMap["path"] = s.Path
	s.fieldMap["method"] = s.Method
}

func (s sysResourceApi) clone(db *gorm.DB) sysResourceApi {
	s.sysResourceApiDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysResourceApi) replaceDB(db *gorm.DB) sysResourceApi {
	s.sysResourceApiDo.ReplaceDB(db)
	return s
}

type sysResourceApiDo struct{ gen.DO }

type ISysResourceApiDo interface {
	gen.SubQuery
	Debug() ISysResourceApiDo
	WithContext(ctx context.Context) ISysResourceApiDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysResourceApiDo
	WriteDB() ISysResourceApiDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysResourceApiDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysResourceApiDo
	Not(conds ...gen.Condition) ISysResourceApiDo
	Or(conds ...gen.Condition) ISysResourceApiDo
	Select(conds ...field.Expr) ISysResourceApiDo
	Where(conds ...gen.Condition) ISysResourceApiDo
	Order(conds ...field.Expr) ISysResourceApiDo
	Distinct(cols ...field.Expr) ISysResourceApiDo
	Omit(cols ...field.Expr) ISysResourceApiDo
	Join(table schema.Tabler, on ...field.Expr) ISysResourceApiDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysResourceApiDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysResourceApiDo
	Group(cols ...field.Expr) ISysResourceApiDo
	Having(conds ...gen.Condition) ISysResourceApiDo
	Limit(limit int) ISysResourceApiDo
	Offset(offset int) ISysResourceApiDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysResourceApiDo
	Unscoped() ISysResourceApiDo
	Create(values ...*models.SysResourceApi) error
	CreateInBatches(values []*models.SysResourceApi, batchSize int) error
	Save(values ...*models.SysResourceApi) error
	First() (*models.SysResourceApi, error)
	Take() (*models.SysResourceApi, error)
	Last() (*models.SysResourceApi, error)
	Find() ([]*models.SysResourceApi, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysResourceApi, err error)
	FindInBatches(result *[]*models.SysResourceApi, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysResourceApi) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysResourceApiDo
	Assign(attrs ...field.AssignExpr) ISysResourceApiDo
	Joins(fields ...field.RelationField) ISysResourceApiDo
	Preload(fields ...field.RelationField) ISysResourceApiDo
	FirstOrInit() (*models.SysResourceApi, error)
	FirstOrCreate() (*models.SysResourceApi, error)
	FindByPage(offset int, limit int) (result []*models.SysResourceApi, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysResourceApiDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysResourceApiDo) Debug() ISysResourceApiDo {
	return s.withDO(s.DO.Debug())
}

func (s sysResourceApiDo) WithContext(ctx context.Context) ISysResourceApiDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysResourceApiDo) ReadDB() ISysResourceApiDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysResourceApiDo) WriteDB() ISysResourceApiDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysResourceApiDo) Session(config *gorm.Session) ISysResourceApiDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysResourceApiDo) Clauses(conds ...clause.Expression) ISysResourceApiDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysResourceApiDo) Returning(value interface{}, columns ...string) ISysResourceApiDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysResourceApiDo) Not(conds ...gen.Condition) ISysResourceApiDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysResourceApiDo) Or(conds ...gen.Condition) ISysResourceApiDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysResourceApiDo) Select(conds ...field.Expr) ISysResourceApiDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysResourceApiDo) Where(conds ...gen.Condition) ISysResourceApiDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysResourceApiDo) Order(conds ...field.Expr) ISysResourceApiDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysResourceApiDo) Distinct(cols ...field.Expr) ISysResourceApiDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysResourceApiDo) Omit(cols ...field.Expr) ISysResourceApiDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysResourceApiDo) Join(table schema.Tabler, on ...field.Expr) ISysResourceApiDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysResourceApiDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysResourceApiDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysResourceApiDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysResourceApiDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysResourceApiDo) Group(cols ...field.Expr) ISysResourceApiDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysResourceApiDo) Having(conds ...gen.Condition) ISysResourceApiDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysResourceApiDo) Limit(limit int) ISysResourceApiDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysResourceApiDo) Offset(offset int) ISysResourceApiDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysResourceApiDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysResourceApiDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysResourceApiDo) Unscoped() ISysResourceApiDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysResourceApiDo) Create(values ...*models.SysResourceApi) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysResourceApiDo) CreateInBatches(values []*models.SysResourceApi, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysResourceApiDo) Save(values ...*models.SysResourceApi) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysResourceApiDo) First() (*models.SysResourceApi, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceApi), nil
	}
}

func (s sysResourceApiDo) Take() (*models.SysResourceApi, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceApi), nil
	}
}

func (s sysResourceApiDo) Last() (*models.SysResourceApi, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceApi), nil
	}
}

func (s sysResourceApiDo) Find() ([]*models.SysResourceApi, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysResourceApi), err
}

func (s sysResourceApiDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysResourceApi, err error) {
	buf := make([]*models.SysResourceApi, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysResourceApiDo) FindInBatches(result *[]*models.SysResourceApi, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysResourceApiDo) Attrs(attrs ...field.AssignExpr) ISysResourceApiDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysResourceApiDo) Assign(attrs ...field.AssignExpr) ISysResourceApiDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysResourceApiDo) Joins(fields ...field.RelationField) ISysResourceApiDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysResourceApiDo) Preload(fields ...field.RelationField) ISysResourceApiDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysResourceApiDo) FirstOrInit() (*models.SysResourceApi, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceApi), nil
	}
}

func (s sysResourceApiDo) FirstOrCreate() (*models.SysResourceApi, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceApi), nil
	}
}

func (s sysResourceApiDo) FindByPage(offset int, limit int) (result []*models.SysResourceApi, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysResourceApiDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysResourceApiDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysResourceApiDo) Delete(models ...*models.SysResourceApi) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysResourceApiDo) withDO(do gen.Dao) *sysResourceApiDo {
	s.DO = *do.(*gen.DO)
	return s
}
