// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysLanguageEntry(db *gorm.DB, opts ...gen.DOOption) sysLanguageEntry {
	_sysLanguageEntry := sysLanguageEntry{}

	_sysLanguageEntry.sysLanguageEntryDo.UseDB(db, opts...)
	_sysLanguageEntry.sysLanguageEntryDo.UseModel(&models.SysLanguageEntry{})

	tableName := _sysLanguageEntry.sysLanguageEntryDo.TableName()
	_sysLanguageEntry.ALL = field.NewAsterisk(tableName)
	_sysLanguageEntry.ID = field.NewUint64(tableName, "id")
	_sysLanguageEntry.CreatedAt = field.NewTime(tableName, "created_at")
	_sysLanguageEntry.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysLanguageEntry.CreatedBy = field.NewUint64(tableName, "created_by")
	_sysLanguageEntry.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_sysLanguageEntry.SortOrder = field.NewInt32(tableName, "sort_order")
	_sysLanguageEntry.IsEnabled = field.NewBool(tableName, "is_enabled")
	_sysLanguageEntry.Remark = field.NewString(tableName, "remark")
	_sysLanguageEntry.DeletedAt = field.NewUint(tableName, "deleted_at")
	_sysLanguageEntry.EntryCode = field.NewString(tableName, "entry_code")
	_sysLanguageEntry.EntryValue = field.NewString(tableName, "entry_value")
	_sysLanguageEntry.SysLanguageTypeId = field.NewUint64(tableName, "sys_language_type_id")
	_sysLanguageEntry.SysLanguageType = sysLanguageEntryBelongsToSysLanguageType{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SysLanguageType", "models.SysLanguageType"),
		Entries: struct {
			field.RelationField
			SysLanguageType struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("SysLanguageType.Entries", "models.SysLanguageEntry"),
			SysLanguageType: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("SysLanguageType.Entries.SysLanguageType", "models.SysLanguageType"),
			},
		},
	}

	_sysLanguageEntry.fillFieldMap()

	return _sysLanguageEntry
}

type sysLanguageEntry struct {
	sysLanguageEntryDo

	ALL               field.Asterisk
	ID                field.Uint64
	CreatedAt         field.Time
	UpdatedAt         field.Time
	CreatedBy         field.Uint64
	UpdatedBy         field.Uint64
	SortOrder         field.Int32
	IsEnabled         field.Bool
	Remark            field.String
	DeletedAt         field.Uint
	EntryCode         field.String // 语言条目编码
	EntryValue        field.String // 语言值
	SysLanguageTypeId field.Uint64 // 语言类型ID
	SysLanguageType   sysLanguageEntryBelongsToSysLanguageType

	fieldMap map[string]field.Expr
}

func (s sysLanguageEntry) Table(newTableName string) *sysLanguageEntry {
	s.sysLanguageEntryDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysLanguageEntry) As(alias string) *sysLanguageEntry {
	s.sysLanguageEntryDo.DO = *(s.sysLanguageEntryDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysLanguageEntry) updateTableName(table string) *sysLanguageEntry {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CreatedBy = field.NewUint64(table, "created_by")
	s.UpdatedBy = field.NewUint64(table, "updated_by")
	s.SortOrder = field.NewInt32(table, "sort_order")
	s.IsEnabled = field.NewBool(table, "is_enabled")
	s.Remark = field.NewString(table, "remark")
	s.DeletedAt = field.NewUint(table, "deleted_at")
	s.EntryCode = field.NewString(table, "entry_code")
	s.EntryValue = field.NewString(table, "entry_value")
	s.SysLanguageTypeId = field.NewUint64(table, "sys_language_type_id")

	s.fillFieldMap()

	return s
}

func (s *sysLanguageEntry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysLanguageEntry) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["sort_order"] = s.SortOrder
	s.fieldMap["is_enabled"] = s.IsEnabled
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["entry_code"] = s.EntryCode
	s.fieldMap["entry_value"] = s.EntryValue
	s.fieldMap["sys_language_type_id"] = s.SysLanguageTypeId

}

func (s sysLanguageEntry) clone(db *gorm.DB) sysLanguageEntry {
	s.sysLanguageEntryDo.ReplaceConnPool(db.Statement.ConnPool)
	s.SysLanguageType.db = db.Session(&gorm.Session{Initialized: true})
	s.SysLanguageType.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sysLanguageEntry) replaceDB(db *gorm.DB) sysLanguageEntry {
	s.sysLanguageEntryDo.ReplaceDB(db)
	s.SysLanguageType.db = db.Session(&gorm.Session{})
	return s
}

type sysLanguageEntryBelongsToSysLanguageType struct {
	db *gorm.DB

	field.RelationField

	Entries struct {
		field.RelationField
		SysLanguageType struct {
			field.RelationField
		}
	}
}

func (a sysLanguageEntryBelongsToSysLanguageType) Where(conds ...field.Expr) *sysLanguageEntryBelongsToSysLanguageType {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysLanguageEntryBelongsToSysLanguageType) WithContext(ctx context.Context) *sysLanguageEntryBelongsToSysLanguageType {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysLanguageEntryBelongsToSysLanguageType) Session(session *gorm.Session) *sysLanguageEntryBelongsToSysLanguageType {
	a.db = a.db.Session(session)
	return &a
}

func (a sysLanguageEntryBelongsToSysLanguageType) Model(m *models.SysLanguageEntry) *sysLanguageEntryBelongsToSysLanguageTypeTx {
	return &sysLanguageEntryBelongsToSysLanguageTypeTx{a.db.Model(m).Association(a.Name())}
}

func (a sysLanguageEntryBelongsToSysLanguageType) Unscoped() *sysLanguageEntryBelongsToSysLanguageType {
	a.db = a.db.Unscoped()
	return &a
}

type sysLanguageEntryBelongsToSysLanguageTypeTx struct{ tx *gorm.Association }

func (a sysLanguageEntryBelongsToSysLanguageTypeTx) Find() (result *models.SysLanguageType, err error) {
	return result, a.tx.Find(&result)
}

func (a sysLanguageEntryBelongsToSysLanguageTypeTx) Append(values ...*models.SysLanguageType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysLanguageEntryBelongsToSysLanguageTypeTx) Replace(values ...*models.SysLanguageType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysLanguageEntryBelongsToSysLanguageTypeTx) Delete(values ...*models.SysLanguageType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysLanguageEntryBelongsToSysLanguageTypeTx) Clear() error {
	return a.tx.Clear()
}

func (a sysLanguageEntryBelongsToSysLanguageTypeTx) Count() int64 {
	return a.tx.Count()
}

func (a sysLanguageEntryBelongsToSysLanguageTypeTx) Unscoped() *sysLanguageEntryBelongsToSysLanguageTypeTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysLanguageEntryDo struct{ gen.DO }

type ISysLanguageEntryDo interface {
	gen.SubQuery
	Debug() ISysLanguageEntryDo
	WithContext(ctx context.Context) ISysLanguageEntryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysLanguageEntryDo
	WriteDB() ISysLanguageEntryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysLanguageEntryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysLanguageEntryDo
	Not(conds ...gen.Condition) ISysLanguageEntryDo
	Or(conds ...gen.Condition) ISysLanguageEntryDo
	Select(conds ...field.Expr) ISysLanguageEntryDo
	Where(conds ...gen.Condition) ISysLanguageEntryDo
	Order(conds ...field.Expr) ISysLanguageEntryDo
	Distinct(cols ...field.Expr) ISysLanguageEntryDo
	Omit(cols ...field.Expr) ISysLanguageEntryDo
	Join(table schema.Tabler, on ...field.Expr) ISysLanguageEntryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysLanguageEntryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysLanguageEntryDo
	Group(cols ...field.Expr) ISysLanguageEntryDo
	Having(conds ...gen.Condition) ISysLanguageEntryDo
	Limit(limit int) ISysLanguageEntryDo
	Offset(offset int) ISysLanguageEntryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLanguageEntryDo
	Unscoped() ISysLanguageEntryDo
	Create(values ...*models.SysLanguageEntry) error
	CreateInBatches(values []*models.SysLanguageEntry, batchSize int) error
	Save(values ...*models.SysLanguageEntry) error
	First() (*models.SysLanguageEntry, error)
	Take() (*models.SysLanguageEntry, error)
	Last() (*models.SysLanguageEntry, error)
	Find() ([]*models.SysLanguageEntry, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysLanguageEntry, err error)
	FindInBatches(result *[]*models.SysLanguageEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysLanguageEntry) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysLanguageEntryDo
	Assign(attrs ...field.AssignExpr) ISysLanguageEntryDo
	Joins(fields ...field.RelationField) ISysLanguageEntryDo
	Preload(fields ...field.RelationField) ISysLanguageEntryDo
	FirstOrInit() (*models.SysLanguageEntry, error)
	FirstOrCreate() (*models.SysLanguageEntry, error)
	FindByPage(offset int, limit int) (result []*models.SysLanguageEntry, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysLanguageEntryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysLanguageEntryDo) Debug() ISysLanguageEntryDo {
	return s.withDO(s.DO.Debug())
}

func (s sysLanguageEntryDo) WithContext(ctx context.Context) ISysLanguageEntryDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysLanguageEntryDo) ReadDB() ISysLanguageEntryDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysLanguageEntryDo) WriteDB() ISysLanguageEntryDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysLanguageEntryDo) Session(config *gorm.Session) ISysLanguageEntryDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysLanguageEntryDo) Clauses(conds ...clause.Expression) ISysLanguageEntryDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysLanguageEntryDo) Returning(value interface{}, columns ...string) ISysLanguageEntryDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysLanguageEntryDo) Not(conds ...gen.Condition) ISysLanguageEntryDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysLanguageEntryDo) Or(conds ...gen.Condition) ISysLanguageEntryDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysLanguageEntryDo) Select(conds ...field.Expr) ISysLanguageEntryDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysLanguageEntryDo) Where(conds ...gen.Condition) ISysLanguageEntryDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysLanguageEntryDo) Order(conds ...field.Expr) ISysLanguageEntryDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysLanguageEntryDo) Distinct(cols ...field.Expr) ISysLanguageEntryDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysLanguageEntryDo) Omit(cols ...field.Expr) ISysLanguageEntryDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysLanguageEntryDo) Join(table schema.Tabler, on ...field.Expr) ISysLanguageEntryDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysLanguageEntryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysLanguageEntryDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysLanguageEntryDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysLanguageEntryDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysLanguageEntryDo) Group(cols ...field.Expr) ISysLanguageEntryDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysLanguageEntryDo) Having(conds ...gen.Condition) ISysLanguageEntryDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysLanguageEntryDo) Limit(limit int) ISysLanguageEntryDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysLanguageEntryDo) Offset(offset int) ISysLanguageEntryDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysLanguageEntryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLanguageEntryDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysLanguageEntryDo) Unscoped() ISysLanguageEntryDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysLanguageEntryDo) Create(values ...*models.SysLanguageEntry) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysLanguageEntryDo) CreateInBatches(values []*models.SysLanguageEntry, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysLanguageEntryDo) Save(values ...*models.SysLanguageEntry) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysLanguageEntryDo) First() (*models.SysLanguageEntry, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguageEntry), nil
	}
}

func (s sysLanguageEntryDo) Take() (*models.SysLanguageEntry, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguageEntry), nil
	}
}

func (s sysLanguageEntryDo) Last() (*models.SysLanguageEntry, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguageEntry), nil
	}
}

func (s sysLanguageEntryDo) Find() ([]*models.SysLanguageEntry, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysLanguageEntry), err
}

func (s sysLanguageEntryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysLanguageEntry, err error) {
	buf := make([]*models.SysLanguageEntry, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysLanguageEntryDo) FindInBatches(result *[]*models.SysLanguageEntry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysLanguageEntryDo) Attrs(attrs ...field.AssignExpr) ISysLanguageEntryDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysLanguageEntryDo) Assign(attrs ...field.AssignExpr) ISysLanguageEntryDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysLanguageEntryDo) Joins(fields ...field.RelationField) ISysLanguageEntryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysLanguageEntryDo) Preload(fields ...field.RelationField) ISysLanguageEntryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysLanguageEntryDo) FirstOrInit() (*models.SysLanguageEntry, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguageEntry), nil
	}
}

func (s sysLanguageEntryDo) FirstOrCreate() (*models.SysLanguageEntry, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguageEntry), nil
	}
}

func (s sysLanguageEntryDo) FindByPage(offset int, limit int) (result []*models.SysLanguageEntry, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysLanguageEntryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysLanguageEntryDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysLanguageEntryDo) Delete(models ...*models.SysLanguageEntry) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysLanguageEntryDo) withDO(do gen.Dao) *sysLanguageEntryDo {
	s.DO = *do.(*gen.DO)
	return s
}
