// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysLanguage(db *gorm.DB, opts ...gen.DOOption) sysLanguage {
	_sysLanguage := sysLanguage{}

	_sysLanguage.sysLanguageDo.UseDB(db, opts...)
	_sysLanguage.sysLanguageDo.UseModel(&models.SysLanguage{})

	tableName := _sysLanguage.sysLanguageDo.TableName()
	_sysLanguage.ALL = field.NewAsterisk(tableName)
	_sysLanguage.ID = field.NewUint64(tableName, "id")
	_sysLanguage.CreatedAt = field.NewTime(tableName, "created_at")
	_sysLanguage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysLanguage.CreatedBy = field.NewUint64(tableName, "created_by")
	_sysLanguage.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_sysLanguage.SortOrder = field.NewInt32(tableName, "sort_order")
	_sysLanguage.IsEnabled = field.NewBool(tableName, "is_enabled")
	_sysLanguage.DeletedAt = field.NewUint(tableName, "deleted_at")
	_sysLanguage.LanguageCode = field.NewString(tableName, "language_code")
	_sysLanguage.LanguageName = field.NewString(tableName, "language_name")
	_sysLanguage.NativeName = field.NewString(tableName, "native_name")
	_sysLanguage.IsDefault = field.NewBool(tableName, "is_default")

	_sysLanguage.fillFieldMap()

	return _sysLanguage
}

type sysLanguage struct {
	sysLanguageDo

	ALL          field.Asterisk
	ID           field.Uint64
	CreatedAt    field.Time
	UpdatedAt    field.Time
	CreatedBy    field.Uint64
	UpdatedBy    field.Uint64
	SortOrder    field.Int32
	IsEnabled    field.Bool
	DeletedAt    field.Uint
	LanguageCode field.String // 标准语言代码
	LanguageName field.String // 语言名称
	NativeName   field.String // 本地语言名称
	IsDefault    field.Bool   // 是否为默认语言

	fieldMap map[string]field.Expr
}

func (s sysLanguage) Table(newTableName string) *sysLanguage {
	s.sysLanguageDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysLanguage) As(alias string) *sysLanguage {
	s.sysLanguageDo.DO = *(s.sysLanguageDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysLanguage) updateTableName(table string) *sysLanguage {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CreatedBy = field.NewUint64(table, "created_by")
	s.UpdatedBy = field.NewUint64(table, "updated_by")
	s.SortOrder = field.NewInt32(table, "sort_order")
	s.IsEnabled = field.NewBool(table, "is_enabled")
	s.DeletedAt = field.NewUint(table, "deleted_at")
	s.LanguageCode = field.NewString(table, "language_code")
	s.LanguageName = field.NewString(table, "language_name")
	s.NativeName = field.NewString(table, "native_name")
	s.IsDefault = field.NewBool(table, "is_default")

	s.fillFieldMap()

	return s
}

func (s *sysLanguage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysLanguage) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["sort_order"] = s.SortOrder
	s.fieldMap["is_enabled"] = s.IsEnabled
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["language_code"] = s.LanguageCode
	s.fieldMap["language_name"] = s.LanguageName
	s.fieldMap["native_name"] = s.NativeName
	s.fieldMap["is_default"] = s.IsDefault
}

func (s sysLanguage) clone(db *gorm.DB) sysLanguage {
	s.sysLanguageDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysLanguage) replaceDB(db *gorm.DB) sysLanguage {
	s.sysLanguageDo.ReplaceDB(db)
	return s
}

type sysLanguageDo struct{ gen.DO }

type ISysLanguageDo interface {
	gen.SubQuery
	Debug() ISysLanguageDo
	WithContext(ctx context.Context) ISysLanguageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysLanguageDo
	WriteDB() ISysLanguageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysLanguageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysLanguageDo
	Not(conds ...gen.Condition) ISysLanguageDo
	Or(conds ...gen.Condition) ISysLanguageDo
	Select(conds ...field.Expr) ISysLanguageDo
	Where(conds ...gen.Condition) ISysLanguageDo
	Order(conds ...field.Expr) ISysLanguageDo
	Distinct(cols ...field.Expr) ISysLanguageDo
	Omit(cols ...field.Expr) ISysLanguageDo
	Join(table schema.Tabler, on ...field.Expr) ISysLanguageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysLanguageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysLanguageDo
	Group(cols ...field.Expr) ISysLanguageDo
	Having(conds ...gen.Condition) ISysLanguageDo
	Limit(limit int) ISysLanguageDo
	Offset(offset int) ISysLanguageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLanguageDo
	Unscoped() ISysLanguageDo
	Create(values ...*models.SysLanguage) error
	CreateInBatches(values []*models.SysLanguage, batchSize int) error
	Save(values ...*models.SysLanguage) error
	First() (*models.SysLanguage, error)
	Take() (*models.SysLanguage, error)
	Last() (*models.SysLanguage, error)
	Find() ([]*models.SysLanguage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysLanguage, err error)
	FindInBatches(result *[]*models.SysLanguage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysLanguage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysLanguageDo
	Assign(attrs ...field.AssignExpr) ISysLanguageDo
	Joins(fields ...field.RelationField) ISysLanguageDo
	Preload(fields ...field.RelationField) ISysLanguageDo
	FirstOrInit() (*models.SysLanguage, error)
	FirstOrCreate() (*models.SysLanguage, error)
	FindByPage(offset int, limit int) (result []*models.SysLanguage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysLanguageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysLanguageDo) Debug() ISysLanguageDo {
	return s.withDO(s.DO.Debug())
}

func (s sysLanguageDo) WithContext(ctx context.Context) ISysLanguageDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysLanguageDo) ReadDB() ISysLanguageDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysLanguageDo) WriteDB() ISysLanguageDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysLanguageDo) Session(config *gorm.Session) ISysLanguageDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysLanguageDo) Clauses(conds ...clause.Expression) ISysLanguageDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysLanguageDo) Returning(value interface{}, columns ...string) ISysLanguageDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysLanguageDo) Not(conds ...gen.Condition) ISysLanguageDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysLanguageDo) Or(conds ...gen.Condition) ISysLanguageDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysLanguageDo) Select(conds ...field.Expr) ISysLanguageDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysLanguageDo) Where(conds ...gen.Condition) ISysLanguageDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysLanguageDo) Order(conds ...field.Expr) ISysLanguageDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysLanguageDo) Distinct(cols ...field.Expr) ISysLanguageDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysLanguageDo) Omit(cols ...field.Expr) ISysLanguageDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysLanguageDo) Join(table schema.Tabler, on ...field.Expr) ISysLanguageDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysLanguageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysLanguageDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysLanguageDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysLanguageDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysLanguageDo) Group(cols ...field.Expr) ISysLanguageDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysLanguageDo) Having(conds ...gen.Condition) ISysLanguageDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysLanguageDo) Limit(limit int) ISysLanguageDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysLanguageDo) Offset(offset int) ISysLanguageDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysLanguageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLanguageDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysLanguageDo) Unscoped() ISysLanguageDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysLanguageDo) Create(values ...*models.SysLanguage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysLanguageDo) CreateInBatches(values []*models.SysLanguage, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysLanguageDo) Save(values ...*models.SysLanguage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysLanguageDo) First() (*models.SysLanguage, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguage), nil
	}
}

func (s sysLanguageDo) Take() (*models.SysLanguage, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguage), nil
	}
}

func (s sysLanguageDo) Last() (*models.SysLanguage, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguage), nil
	}
}

func (s sysLanguageDo) Find() ([]*models.SysLanguage, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysLanguage), err
}

func (s sysLanguageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysLanguage, err error) {
	buf := make([]*models.SysLanguage, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysLanguageDo) FindInBatches(result *[]*models.SysLanguage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysLanguageDo) Attrs(attrs ...field.AssignExpr) ISysLanguageDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysLanguageDo) Assign(attrs ...field.AssignExpr) ISysLanguageDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysLanguageDo) Joins(fields ...field.RelationField) ISysLanguageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysLanguageDo) Preload(fields ...field.RelationField) ISysLanguageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysLanguageDo) FirstOrInit() (*models.SysLanguage, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguage), nil
	}
}

func (s sysLanguageDo) FirstOrCreate() (*models.SysLanguage, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLanguage), nil
	}
}

func (s sysLanguageDo) FindByPage(offset int, limit int) (result []*models.SysLanguage, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysLanguageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysLanguageDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysLanguageDo) Delete(models ...*models.SysLanguage) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysLanguageDo) withDO(do gen.Dao) *sysLanguageDo {
	s.DO = *do.(*gen.DO)
	return s
}
