// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysResourceMenuApi(db *gorm.DB, opts ...gen.DOOption) sysResourceMenuApi {
	_sysResourceMenuApi := sysResourceMenuApi{}

	_sysResourceMenuApi.sysResourceMenuApiDo.UseDB(db, opts...)
	_sysResourceMenuApi.sysResourceMenuApiDo.UseModel(&models.SysResourceMenuApi{})

	tableName := _sysResourceMenuApi.sysResourceMenuApiDo.TableName()
	_sysResourceMenuApi.ALL = field.NewAsterisk(tableName)
	_sysResourceMenuApi.ID = field.NewUint64(tableName, "id")
	_sysResourceMenuApi.CreatedAt = field.NewTime(tableName, "created_at")
	_sysResourceMenuApi.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysResourceMenuApi.CreatedBy = field.NewUint64(tableName, "created_by")
	_sysResourceMenuApi.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_sysResourceMenuApi.DeletedBy = field.NewUint64(tableName, "deleted_by")
	_sysResourceMenuApi.MenuID = field.NewUint64(tableName, "menu_id")
	_sysResourceMenuApi.ApiID = field.NewUint64(tableName, "api_id")
	_sysResourceMenuApi.DeletedAt = field.NewUint(tableName, "deleted_at")
	_sysResourceMenuApi.SysResourceMenu = sysResourceMenuApiBelongsToSysResourceMenu{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SysResourceMenu", "models.SysResourceMenu"),
		ParentSysResourceMenu: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("SysResourceMenu.ParentSysResourceMenu", "models.SysResourceMenu"),
		},
	}

	_sysResourceMenuApi.SysResourceApi = sysResourceMenuApiBelongsToSysResourceApi{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SysResourceApi", "models.SysResourceApi"),
	}

	_sysResourceMenuApi.fillFieldMap()

	return _sysResourceMenuApi
}

type sysResourceMenuApi struct {
	sysResourceMenuApiDo

	ALL             field.Asterisk
	ID              field.Uint64
	CreatedAt       field.Time
	UpdatedAt       field.Time
	CreatedBy       field.Uint64
	UpdatedBy       field.Uint64
	DeletedBy       field.Uint64
	MenuID          field.Uint64 // 菜单资源ID
	ApiID           field.Uint64 // API资源ID
	DeletedAt       field.Uint
	SysResourceMenu sysResourceMenuApiBelongsToSysResourceMenu

	SysResourceApi sysResourceMenuApiBelongsToSysResourceApi

	fieldMap map[string]field.Expr
}

func (s sysResourceMenuApi) Table(newTableName string) *sysResourceMenuApi {
	s.sysResourceMenuApiDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysResourceMenuApi) As(alias string) *sysResourceMenuApi {
	s.sysResourceMenuApiDo.DO = *(s.sysResourceMenuApiDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysResourceMenuApi) updateTableName(table string) *sysResourceMenuApi {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CreatedBy = field.NewUint64(table, "created_by")
	s.UpdatedBy = field.NewUint64(table, "updated_by")
	s.DeletedBy = field.NewUint64(table, "deleted_by")
	s.MenuID = field.NewUint64(table, "menu_id")
	s.ApiID = field.NewUint64(table, "api_id")
	s.DeletedAt = field.NewUint(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sysResourceMenuApi) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysResourceMenuApi) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["deleted_by"] = s.DeletedBy
	s.fieldMap["menu_id"] = s.MenuID
	s.fieldMap["api_id"] = s.ApiID
	s.fieldMap["deleted_at"] = s.DeletedAt

}

func (s sysResourceMenuApi) clone(db *gorm.DB) sysResourceMenuApi {
	s.sysResourceMenuApiDo.ReplaceConnPool(db.Statement.ConnPool)
	s.SysResourceMenu.db = db.Session(&gorm.Session{Initialized: true})
	s.SysResourceMenu.db.Statement.ConnPool = db.Statement.ConnPool
	s.SysResourceApi.db = db.Session(&gorm.Session{Initialized: true})
	s.SysResourceApi.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sysResourceMenuApi) replaceDB(db *gorm.DB) sysResourceMenuApi {
	s.sysResourceMenuApiDo.ReplaceDB(db)
	s.SysResourceMenu.db = db.Session(&gorm.Session{})
	s.SysResourceApi.db = db.Session(&gorm.Session{})
	return s
}

type sysResourceMenuApiBelongsToSysResourceMenu struct {
	db *gorm.DB

	field.RelationField

	ParentSysResourceMenu struct {
		field.RelationField
	}
}

func (a sysResourceMenuApiBelongsToSysResourceMenu) Where(conds ...field.Expr) *sysResourceMenuApiBelongsToSysResourceMenu {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysResourceMenuApiBelongsToSysResourceMenu) WithContext(ctx context.Context) *sysResourceMenuApiBelongsToSysResourceMenu {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysResourceMenuApiBelongsToSysResourceMenu) Session(session *gorm.Session) *sysResourceMenuApiBelongsToSysResourceMenu {
	a.db = a.db.Session(session)
	return &a
}

func (a sysResourceMenuApiBelongsToSysResourceMenu) Model(m *models.SysResourceMenuApi) *sysResourceMenuApiBelongsToSysResourceMenuTx {
	return &sysResourceMenuApiBelongsToSysResourceMenuTx{a.db.Model(m).Association(a.Name())}
}

func (a sysResourceMenuApiBelongsToSysResourceMenu) Unscoped() *sysResourceMenuApiBelongsToSysResourceMenu {
	a.db = a.db.Unscoped()
	return &a
}

type sysResourceMenuApiBelongsToSysResourceMenuTx struct{ tx *gorm.Association }

func (a sysResourceMenuApiBelongsToSysResourceMenuTx) Find() (result *models.SysResourceMenu, err error) {
	return result, a.tx.Find(&result)
}

func (a sysResourceMenuApiBelongsToSysResourceMenuTx) Append(values ...*models.SysResourceMenu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysResourceMenuApiBelongsToSysResourceMenuTx) Replace(values ...*models.SysResourceMenu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysResourceMenuApiBelongsToSysResourceMenuTx) Delete(values ...*models.SysResourceMenu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysResourceMenuApiBelongsToSysResourceMenuTx) Clear() error {
	return a.tx.Clear()
}

func (a sysResourceMenuApiBelongsToSysResourceMenuTx) Count() int64 {
	return a.tx.Count()
}

func (a sysResourceMenuApiBelongsToSysResourceMenuTx) Unscoped() *sysResourceMenuApiBelongsToSysResourceMenuTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysResourceMenuApiBelongsToSysResourceApi struct {
	db *gorm.DB

	field.RelationField
}

func (a sysResourceMenuApiBelongsToSysResourceApi) Where(conds ...field.Expr) *sysResourceMenuApiBelongsToSysResourceApi {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysResourceMenuApiBelongsToSysResourceApi) WithContext(ctx context.Context) *sysResourceMenuApiBelongsToSysResourceApi {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysResourceMenuApiBelongsToSysResourceApi) Session(session *gorm.Session) *sysResourceMenuApiBelongsToSysResourceApi {
	a.db = a.db.Session(session)
	return &a
}

func (a sysResourceMenuApiBelongsToSysResourceApi) Model(m *models.SysResourceMenuApi) *sysResourceMenuApiBelongsToSysResourceApiTx {
	return &sysResourceMenuApiBelongsToSysResourceApiTx{a.db.Model(m).Association(a.Name())}
}

func (a sysResourceMenuApiBelongsToSysResourceApi) Unscoped() *sysResourceMenuApiBelongsToSysResourceApi {
	a.db = a.db.Unscoped()
	return &a
}

type sysResourceMenuApiBelongsToSysResourceApiTx struct{ tx *gorm.Association }

func (a sysResourceMenuApiBelongsToSysResourceApiTx) Find() (result *models.SysResourceApi, err error) {
	return result, a.tx.Find(&result)
}

func (a sysResourceMenuApiBelongsToSysResourceApiTx) Append(values ...*models.SysResourceApi) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysResourceMenuApiBelongsToSysResourceApiTx) Replace(values ...*models.SysResourceApi) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysResourceMenuApiBelongsToSysResourceApiTx) Delete(values ...*models.SysResourceApi) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysResourceMenuApiBelongsToSysResourceApiTx) Clear() error {
	return a.tx.Clear()
}

func (a sysResourceMenuApiBelongsToSysResourceApiTx) Count() int64 {
	return a.tx.Count()
}

func (a sysResourceMenuApiBelongsToSysResourceApiTx) Unscoped() *sysResourceMenuApiBelongsToSysResourceApiTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysResourceMenuApiDo struct{ gen.DO }

type ISysResourceMenuApiDo interface {
	gen.SubQuery
	Debug() ISysResourceMenuApiDo
	WithContext(ctx context.Context) ISysResourceMenuApiDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysResourceMenuApiDo
	WriteDB() ISysResourceMenuApiDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysResourceMenuApiDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysResourceMenuApiDo
	Not(conds ...gen.Condition) ISysResourceMenuApiDo
	Or(conds ...gen.Condition) ISysResourceMenuApiDo
	Select(conds ...field.Expr) ISysResourceMenuApiDo
	Where(conds ...gen.Condition) ISysResourceMenuApiDo
	Order(conds ...field.Expr) ISysResourceMenuApiDo
	Distinct(cols ...field.Expr) ISysResourceMenuApiDo
	Omit(cols ...field.Expr) ISysResourceMenuApiDo
	Join(table schema.Tabler, on ...field.Expr) ISysResourceMenuApiDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysResourceMenuApiDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysResourceMenuApiDo
	Group(cols ...field.Expr) ISysResourceMenuApiDo
	Having(conds ...gen.Condition) ISysResourceMenuApiDo
	Limit(limit int) ISysResourceMenuApiDo
	Offset(offset int) ISysResourceMenuApiDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysResourceMenuApiDo
	Unscoped() ISysResourceMenuApiDo
	Create(values ...*models.SysResourceMenuApi) error
	CreateInBatches(values []*models.SysResourceMenuApi, batchSize int) error
	Save(values ...*models.SysResourceMenuApi) error
	First() (*models.SysResourceMenuApi, error)
	Take() (*models.SysResourceMenuApi, error)
	Last() (*models.SysResourceMenuApi, error)
	Find() ([]*models.SysResourceMenuApi, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysResourceMenuApi, err error)
	FindInBatches(result *[]*models.SysResourceMenuApi, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysResourceMenuApi) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysResourceMenuApiDo
	Assign(attrs ...field.AssignExpr) ISysResourceMenuApiDo
	Joins(fields ...field.RelationField) ISysResourceMenuApiDo
	Preload(fields ...field.RelationField) ISysResourceMenuApiDo
	FirstOrInit() (*models.SysResourceMenuApi, error)
	FirstOrCreate() (*models.SysResourceMenuApi, error)
	FindByPage(offset int, limit int) (result []*models.SysResourceMenuApi, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysResourceMenuApiDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysResourceMenuApiDo) Debug() ISysResourceMenuApiDo {
	return s.withDO(s.DO.Debug())
}

func (s sysResourceMenuApiDo) WithContext(ctx context.Context) ISysResourceMenuApiDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysResourceMenuApiDo) ReadDB() ISysResourceMenuApiDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysResourceMenuApiDo) WriteDB() ISysResourceMenuApiDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysResourceMenuApiDo) Session(config *gorm.Session) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysResourceMenuApiDo) Clauses(conds ...clause.Expression) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysResourceMenuApiDo) Returning(value interface{}, columns ...string) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysResourceMenuApiDo) Not(conds ...gen.Condition) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysResourceMenuApiDo) Or(conds ...gen.Condition) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysResourceMenuApiDo) Select(conds ...field.Expr) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysResourceMenuApiDo) Where(conds ...gen.Condition) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysResourceMenuApiDo) Order(conds ...field.Expr) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysResourceMenuApiDo) Distinct(cols ...field.Expr) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysResourceMenuApiDo) Omit(cols ...field.Expr) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysResourceMenuApiDo) Join(table schema.Tabler, on ...field.Expr) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysResourceMenuApiDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysResourceMenuApiDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysResourceMenuApiDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysResourceMenuApiDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysResourceMenuApiDo) Group(cols ...field.Expr) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysResourceMenuApiDo) Having(conds ...gen.Condition) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysResourceMenuApiDo) Limit(limit int) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysResourceMenuApiDo) Offset(offset int) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysResourceMenuApiDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysResourceMenuApiDo) Unscoped() ISysResourceMenuApiDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysResourceMenuApiDo) Create(values ...*models.SysResourceMenuApi) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysResourceMenuApiDo) CreateInBatches(values []*models.SysResourceMenuApi, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysResourceMenuApiDo) Save(values ...*models.SysResourceMenuApi) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysResourceMenuApiDo) First() (*models.SysResourceMenuApi, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceMenuApi), nil
	}
}

func (s sysResourceMenuApiDo) Take() (*models.SysResourceMenuApi, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceMenuApi), nil
	}
}

func (s sysResourceMenuApiDo) Last() (*models.SysResourceMenuApi, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceMenuApi), nil
	}
}

func (s sysResourceMenuApiDo) Find() ([]*models.SysResourceMenuApi, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysResourceMenuApi), err
}

func (s sysResourceMenuApiDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysResourceMenuApi, err error) {
	buf := make([]*models.SysResourceMenuApi, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysResourceMenuApiDo) FindInBatches(result *[]*models.SysResourceMenuApi, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysResourceMenuApiDo) Attrs(attrs ...field.AssignExpr) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysResourceMenuApiDo) Assign(attrs ...field.AssignExpr) ISysResourceMenuApiDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysResourceMenuApiDo) Joins(fields ...field.RelationField) ISysResourceMenuApiDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysResourceMenuApiDo) Preload(fields ...field.RelationField) ISysResourceMenuApiDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysResourceMenuApiDo) FirstOrInit() (*models.SysResourceMenuApi, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceMenuApi), nil
	}
}

func (s sysResourceMenuApiDo) FirstOrCreate() (*models.SysResourceMenuApi, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysResourceMenuApi), nil
	}
}

func (s sysResourceMenuApiDo) FindByPage(offset int, limit int) (result []*models.SysResourceMenuApi, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysResourceMenuApiDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysResourceMenuApiDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysResourceMenuApiDo) Delete(models ...*models.SysResourceMenuApi) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysResourceMenuApiDo) withDO(do gen.Dao) *sysResourceMenuApiDo {
	s.DO = *do.(*gen.DO)
	return s
}
