// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/internal/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysLoginLog(db *gorm.DB, opts ...gen.DOOption) sysLoginLog {
	_sysLoginLog := sysLoginLog{}

	_sysLoginLog.sysLoginLogDo.UseDB(db, opts...)
	_sysLoginLog.sysLoginLogDo.UseModel(&models.SysLoginLog{})

	tableName := _sysLoginLog.sysLoginLogDo.TableName()
	_sysLoginLog.ALL = field.NewAsterisk(tableName)
	_sysLoginLog.ID = field.NewUint64(tableName, "id")
	_sysLoginLog.CreatedAt = field.NewTime(tableName, "created_at")
	_sysLoginLog.Username = field.NewString(tableName, "username")
	_sysLoginLog.LoginIP = field.NewString(tableName, "login_ip")
	_sysLoginLog.LoginMAC = field.NewString(tableName, "login_mac")
	_sysLoginLog.LoginTime = field.NewTime(tableName, "login_time")
	_sysLoginLog.UserAgent = field.NewString(tableName, "user_agent")
	_sysLoginLog.BrowserName = field.NewString(tableName, "browser_name")
	_sysLoginLog.BrowserVersion = field.NewString(tableName, "browser_version")
	_sysLoginLog.ClientID = field.NewString(tableName, "client_id")
	_sysLoginLog.ClientName = field.NewString(tableName, "client_name")
	_sysLoginLog.OSName = field.NewString(tableName, "os_name")
	_sysLoginLog.OSVersion = field.NewString(tableName, "os_version")
	_sysLoginLog.SysUserID = field.NewUint64(tableName, "sys_user_id")
	_sysLoginLog.StatusCode = field.NewInt32(tableName, "status_code")
	_sysLoginLog.Success = field.NewBool(tableName, "success")
	_sysLoginLog.Reason = field.NewString(tableName, "reason")
	_sysLoginLog.Location = field.NewString(tableName, "location")
	_sysLoginLog.SysUser = sysLoginLogBelongsToSysUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SysUser", "models.SysUser"),
	}

	_sysLoginLog.fillFieldMap()

	return _sysLoginLog
}

type sysLoginLog struct {
	sysLoginLogDo

	ALL            field.Asterisk
	ID             field.Uint64
	CreatedAt      field.Time
	Username       field.String // 登录账号
	LoginIP        field.String // 登录IP地址
	LoginMAC       field.String // 登录MAC地址
	LoginTime      field.Time   // 登录时间
	UserAgent      field.String // 浏览器的用户代理信息
	BrowserName    field.String // 浏览器名称
	BrowserVersion field.String // 浏览器版本
	ClientID       field.String // 客户端ID
	ClientName     field.String // 客户端名称
	OSName         field.String // 操作系统名称
	OSVersion      field.String // 操作系统版本
	SysUserID      field.Uint64 // 登录用户ID
	StatusCode     field.Int32  // 状态码
	Success        field.Bool   // 登录成功
	Reason         field.String // 登录失败原因
	Location       field.String // 登录地理位置
	SysUser        sysLoginLogBelongsToSysUser

	fieldMap map[string]field.Expr
}

func (s sysLoginLog) Table(newTableName string) *sysLoginLog {
	s.sysLoginLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysLoginLog) As(alias string) *sysLoginLog {
	s.sysLoginLogDo.DO = *(s.sysLoginLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysLoginLog) updateTableName(table string) *sysLoginLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.Username = field.NewString(table, "username")
	s.LoginIP = field.NewString(table, "login_ip")
	s.LoginMAC = field.NewString(table, "login_mac")
	s.LoginTime = field.NewTime(table, "login_time")
	s.UserAgent = field.NewString(table, "user_agent")
	s.BrowserName = field.NewString(table, "browser_name")
	s.BrowserVersion = field.NewString(table, "browser_version")
	s.ClientID = field.NewString(table, "client_id")
	s.ClientName = field.NewString(table, "client_name")
	s.OSName = field.NewString(table, "os_name")
	s.OSVersion = field.NewString(table, "os_version")
	s.SysUserID = field.NewUint64(table, "sys_user_id")
	s.StatusCode = field.NewInt32(table, "status_code")
	s.Success = field.NewBool(table, "success")
	s.Reason = field.NewString(table, "reason")
	s.Location = field.NewString(table, "location")

	s.fillFieldMap()

	return s
}

func (s *sysLoginLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysLoginLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 19)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["username"] = s.Username
	s.fieldMap["login_ip"] = s.LoginIP
	s.fieldMap["login_mac"] = s.LoginMAC
	s.fieldMap["login_time"] = s.LoginTime
	s.fieldMap["user_agent"] = s.UserAgent
	s.fieldMap["browser_name"] = s.BrowserName
	s.fieldMap["browser_version"] = s.BrowserVersion
	s.fieldMap["client_id"] = s.ClientID
	s.fieldMap["client_name"] = s.ClientName
	s.fieldMap["os_name"] = s.OSName
	s.fieldMap["os_version"] = s.OSVersion
	s.fieldMap["sys_user_id"] = s.SysUserID
	s.fieldMap["status_code"] = s.StatusCode
	s.fieldMap["success"] = s.Success
	s.fieldMap["reason"] = s.Reason
	s.fieldMap["location"] = s.Location

}

func (s sysLoginLog) clone(db *gorm.DB) sysLoginLog {
	s.sysLoginLogDo.ReplaceConnPool(db.Statement.ConnPool)
	s.SysUser.db = db.Session(&gorm.Session{Initialized: true})
	s.SysUser.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sysLoginLog) replaceDB(db *gorm.DB) sysLoginLog {
	s.sysLoginLogDo.ReplaceDB(db)
	s.SysUser.db = db.Session(&gorm.Session{})
	return s
}

type sysLoginLogBelongsToSysUser struct {
	db *gorm.DB

	field.RelationField
}

func (a sysLoginLogBelongsToSysUser) Where(conds ...field.Expr) *sysLoginLogBelongsToSysUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysLoginLogBelongsToSysUser) WithContext(ctx context.Context) *sysLoginLogBelongsToSysUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysLoginLogBelongsToSysUser) Session(session *gorm.Session) *sysLoginLogBelongsToSysUser {
	a.db = a.db.Session(session)
	return &a
}

func (a sysLoginLogBelongsToSysUser) Model(m *models.SysLoginLog) *sysLoginLogBelongsToSysUserTx {
	return &sysLoginLogBelongsToSysUserTx{a.db.Model(m).Association(a.Name())}
}

func (a sysLoginLogBelongsToSysUser) Unscoped() *sysLoginLogBelongsToSysUser {
	a.db = a.db.Unscoped()
	return &a
}

type sysLoginLogBelongsToSysUserTx struct{ tx *gorm.Association }

func (a sysLoginLogBelongsToSysUserTx) Find() (result *models.SysUser, err error) {
	return result, a.tx.Find(&result)
}

func (a sysLoginLogBelongsToSysUserTx) Append(values ...*models.SysUser) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysLoginLogBelongsToSysUserTx) Replace(values ...*models.SysUser) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysLoginLogBelongsToSysUserTx) Delete(values ...*models.SysUser) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysLoginLogBelongsToSysUserTx) Clear() error {
	return a.tx.Clear()
}

func (a sysLoginLogBelongsToSysUserTx) Count() int64 {
	return a.tx.Count()
}

func (a sysLoginLogBelongsToSysUserTx) Unscoped() *sysLoginLogBelongsToSysUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysLoginLogDo struct{ gen.DO }

type ISysLoginLogDo interface {
	gen.SubQuery
	Debug() ISysLoginLogDo
	WithContext(ctx context.Context) ISysLoginLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysLoginLogDo
	WriteDB() ISysLoginLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysLoginLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysLoginLogDo
	Not(conds ...gen.Condition) ISysLoginLogDo
	Or(conds ...gen.Condition) ISysLoginLogDo
	Select(conds ...field.Expr) ISysLoginLogDo
	Where(conds ...gen.Condition) ISysLoginLogDo
	Order(conds ...field.Expr) ISysLoginLogDo
	Distinct(cols ...field.Expr) ISysLoginLogDo
	Omit(cols ...field.Expr) ISysLoginLogDo
	Join(table schema.Tabler, on ...field.Expr) ISysLoginLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysLoginLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysLoginLogDo
	Group(cols ...field.Expr) ISysLoginLogDo
	Having(conds ...gen.Condition) ISysLoginLogDo
	Limit(limit int) ISysLoginLogDo
	Offset(offset int) ISysLoginLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLoginLogDo
	Unscoped() ISysLoginLogDo
	Create(values ...*models.SysLoginLog) error
	CreateInBatches(values []*models.SysLoginLog, batchSize int) error
	Save(values ...*models.SysLoginLog) error
	First() (*models.SysLoginLog, error)
	Take() (*models.SysLoginLog, error)
	Last() (*models.SysLoginLog, error)
	Find() ([]*models.SysLoginLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysLoginLog, err error)
	FindInBatches(result *[]*models.SysLoginLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysLoginLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysLoginLogDo
	Assign(attrs ...field.AssignExpr) ISysLoginLogDo
	Joins(fields ...field.RelationField) ISysLoginLogDo
	Preload(fields ...field.RelationField) ISysLoginLogDo
	FirstOrInit() (*models.SysLoginLog, error)
	FirstOrCreate() (*models.SysLoginLog, error)
	FindByPage(offset int, limit int) (result []*models.SysLoginLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysLoginLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysLoginLogDo) Debug() ISysLoginLogDo {
	return s.withDO(s.DO.Debug())
}

func (s sysLoginLogDo) WithContext(ctx context.Context) ISysLoginLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysLoginLogDo) ReadDB() ISysLoginLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysLoginLogDo) WriteDB() ISysLoginLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysLoginLogDo) Session(config *gorm.Session) ISysLoginLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysLoginLogDo) Clauses(conds ...clause.Expression) ISysLoginLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysLoginLogDo) Returning(value interface{}, columns ...string) ISysLoginLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysLoginLogDo) Not(conds ...gen.Condition) ISysLoginLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysLoginLogDo) Or(conds ...gen.Condition) ISysLoginLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysLoginLogDo) Select(conds ...field.Expr) ISysLoginLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysLoginLogDo) Where(conds ...gen.Condition) ISysLoginLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysLoginLogDo) Order(conds ...field.Expr) ISysLoginLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysLoginLogDo) Distinct(cols ...field.Expr) ISysLoginLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysLoginLogDo) Omit(cols ...field.Expr) ISysLoginLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysLoginLogDo) Join(table schema.Tabler, on ...field.Expr) ISysLoginLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysLoginLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysLoginLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysLoginLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysLoginLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysLoginLogDo) Group(cols ...field.Expr) ISysLoginLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysLoginLogDo) Having(conds ...gen.Condition) ISysLoginLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysLoginLogDo) Limit(limit int) ISysLoginLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysLoginLogDo) Offset(offset int) ISysLoginLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysLoginLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysLoginLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysLoginLogDo) Unscoped() ISysLoginLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysLoginLogDo) Create(values ...*models.SysLoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysLoginLogDo) CreateInBatches(values []*models.SysLoginLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysLoginLogDo) Save(values ...*models.SysLoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysLoginLogDo) First() (*models.SysLoginLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLoginLog), nil
	}
}

func (s sysLoginLogDo) Take() (*models.SysLoginLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLoginLog), nil
	}
}

func (s sysLoginLogDo) Last() (*models.SysLoginLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLoginLog), nil
	}
}

func (s sysLoginLogDo) Find() ([]*models.SysLoginLog, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysLoginLog), err
}

func (s sysLoginLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysLoginLog, err error) {
	buf := make([]*models.SysLoginLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysLoginLogDo) FindInBatches(result *[]*models.SysLoginLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysLoginLogDo) Attrs(attrs ...field.AssignExpr) ISysLoginLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysLoginLogDo) Assign(attrs ...field.AssignExpr) ISysLoginLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysLoginLogDo) Joins(fields ...field.RelationField) ISysLoginLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysLoginLogDo) Preload(fields ...field.RelationField) ISysLoginLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysLoginLogDo) FirstOrInit() (*models.SysLoginLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLoginLog), nil
	}
}

func (s sysLoginLogDo) FirstOrCreate() (*models.SysLoginLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysLoginLog), nil
	}
}

func (s sysLoginLogDo) FindByPage(offset int, limit int) (result []*models.SysLoginLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysLoginLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysLoginLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysLoginLogDo) Delete(models ...*models.SysLoginLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysLoginLogDo) withDO(do gen.Dao) *sysLoginLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
