// Code generated by go generate; DO NOT EDIT.

package main

import (
	_ "admin/docs"
	_ "admin/internal/auth"
	_ "admin/internal/config"
	_ "admin/internal/domains"
	_ "admin/internal/fiberc"
	_ "admin/internal/fiberc/handler"
	_ "admin/internal/fiberc/middleware"
	_ "admin/internal/fiberc/res"
	_ "admin/internal/router"
	_ "admin/internal/router/auth_router"
	_ "admin/internal/router/logic"
	_ "admin/internal/services"
	_ "admin/internal/services/asynq"
	_ "admin/internal/services/casbin"
	_ "admin/internal/services/httpc"
	_ "admin/internal/services/orm"
	_ "admin/internal/services/orm/models"
	_ "admin/internal/services/orm/query"
	_ "admin/internal/services/redisc"
	_ "admin/internal/validator"
)
