// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysRole(db *gorm.DB, opts ...gen.DOOption) sysRole {
	_sysRole := sysRole{}

	_sysRole.sysRoleDo.UseDB(db, opts...)
	_sysRole.sysRoleDo.UseModel(&models.SysRole{})

	tableName := _sysRole.sysRoleDo.TableName()
	_sysRole.ALL = field.NewAsterisk(tableName)
	_sysRole.ID = field.NewUint64(tableName, "id")
	_sysRole.CreatedAt = field.NewTime(tableName, "created_at")
	_sysRole.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysRole.Remark = field.NewString(tableName, "remark")
	_sysRole.CreatedBy = field.NewUint64(tableName, "created_by")
	_sysRole.UpdatedBy = field.NewUint64(tableName, "updated_by")
	_sysRole.DeletedBy = field.NewUint64(tableName, "deleted_by")
	_sysRole.Status = field.NewUint8(tableName, "status")
	_sysRole.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysRole.Name = field.NewString(tableName, "name")
	_sysRole.Code = field.NewString(tableName, "code")
	_sysRole.Menus = field.NewField(tableName, "menus")
	_sysRole.Apis = field.NewField(tableName, "apis")
	_sysRole.DataScope = field.NewString(tableName, "data_scope")
	_sysRole.ParentID = field.NewUint64(tableName, "parent_id")
	_sysRole.Path = field.NewString(tableName, "path")
	_sysRole.ChildIDs = field.NewField(tableName, "child_ids")
	_sysRole.Children = sysRoleHasManyChildren{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Children", "models.SysRole"),
		ParentSysRole: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.ParentSysRole", "models.SysRole"),
		},
		Children: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Children.Children", "models.SysRole"),
		},
	}

	_sysRole.ParentSysRole = sysRoleBelongsToParentSysRole{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ParentSysRole", "models.SysRole"),
	}

	_sysRole.fillFieldMap()

	return _sysRole
}

type sysRole struct {
	sysRoleDo

	ALL       field.Asterisk
	ID        field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	Remark    field.String
	CreatedBy field.Uint64
	UpdatedBy field.Uint64
	DeletedBy field.Uint64
	Status    field.Uint8
	DeletedAt field.Field
	Name      field.String // 角色名称
	Code      field.String // 角色标识
	Menus     field.Field  // 分配的菜单列表
	Apis      field.Field  // 分配的API列表
	DataScope field.String // 数据权限范围
	ParentID  field.Uint64 // 父级ID
	Path      field.String // 节点路径
	ChildIDs  field.Field  // 所有子节点ID
	Children  sysRoleHasManyChildren

	ParentSysRole sysRoleBelongsToParentSysRole

	fieldMap map[string]field.Expr
}

func (s sysRole) Table(newTableName string) *sysRole {
	s.sysRoleDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRole) As(alias string) *sysRole {
	s.sysRoleDo.DO = *(s.sysRoleDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRole) updateTableName(table string) *sysRole {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.Remark = field.NewString(table, "remark")
	s.CreatedBy = field.NewUint64(table, "created_by")
	s.UpdatedBy = field.NewUint64(table, "updated_by")
	s.DeletedBy = field.NewUint64(table, "deleted_by")
	s.Status = field.NewUint8(table, "status")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.Name = field.NewString(table, "name")
	s.Code = field.NewString(table, "code")
	s.Menus = field.NewField(table, "menus")
	s.Apis = field.NewField(table, "apis")
	s.DataScope = field.NewString(table, "data_scope")
	s.ParentID = field.NewUint64(table, "parent_id")
	s.Path = field.NewString(table, "path")
	s.ChildIDs = field.NewField(table, "child_ids")

	s.fillFieldMap()

	return s
}

func (s *sysRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRole) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 19)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["deleted_by"] = s.DeletedBy
	s.fieldMap["status"] = s.Status
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["name"] = s.Name
	s.fieldMap["code"] = s.Code
	s.fieldMap["menus"] = s.Menus
	s.fieldMap["apis"] = s.Apis
	s.fieldMap["data_scope"] = s.DataScope
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["path"] = s.Path
	s.fieldMap["child_ids"] = s.ChildIDs

}

func (s sysRole) clone(db *gorm.DB) sysRole {
	s.sysRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	s.Children.db = db.Session(&gorm.Session{Initialized: true})
	s.Children.db.Statement.ConnPool = db.Statement.ConnPool
	s.ParentSysRole.db = db.Session(&gorm.Session{Initialized: true})
	s.ParentSysRole.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sysRole) replaceDB(db *gorm.DB) sysRole {
	s.sysRoleDo.ReplaceDB(db)
	s.Children.db = db.Session(&gorm.Session{})
	s.ParentSysRole.db = db.Session(&gorm.Session{})
	return s
}

type sysRoleHasManyChildren struct {
	db *gorm.DB

	field.RelationField

	ParentSysRole struct {
		field.RelationField
	}
	Children struct {
		field.RelationField
	}
}

func (a sysRoleHasManyChildren) Where(conds ...field.Expr) *sysRoleHasManyChildren {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysRoleHasManyChildren) WithContext(ctx context.Context) *sysRoleHasManyChildren {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysRoleHasManyChildren) Session(session *gorm.Session) *sysRoleHasManyChildren {
	a.db = a.db.Session(session)
	return &a
}

func (a sysRoleHasManyChildren) Model(m *models.SysRole) *sysRoleHasManyChildrenTx {
	return &sysRoleHasManyChildrenTx{a.db.Model(m).Association(a.Name())}
}

func (a sysRoleHasManyChildren) Unscoped() *sysRoleHasManyChildren {
	a.db = a.db.Unscoped()
	return &a
}

type sysRoleHasManyChildrenTx struct{ tx *gorm.Association }

func (a sysRoleHasManyChildrenTx) Find() (result []*models.SysRole, err error) {
	return result, a.tx.Find(&result)
}

func (a sysRoleHasManyChildrenTx) Append(values ...*models.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysRoleHasManyChildrenTx) Replace(values ...*models.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysRoleHasManyChildrenTx) Delete(values ...*models.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysRoleHasManyChildrenTx) Clear() error {
	return a.tx.Clear()
}

func (a sysRoleHasManyChildrenTx) Count() int64 {
	return a.tx.Count()
}

func (a sysRoleHasManyChildrenTx) Unscoped() *sysRoleHasManyChildrenTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysRoleBelongsToParentSysRole struct {
	db *gorm.DB

	field.RelationField
}

func (a sysRoleBelongsToParentSysRole) Where(conds ...field.Expr) *sysRoleBelongsToParentSysRole {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sysRoleBelongsToParentSysRole) WithContext(ctx context.Context) *sysRoleBelongsToParentSysRole {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sysRoleBelongsToParentSysRole) Session(session *gorm.Session) *sysRoleBelongsToParentSysRole {
	a.db = a.db.Session(session)
	return &a
}

func (a sysRoleBelongsToParentSysRole) Model(m *models.SysRole) *sysRoleBelongsToParentSysRoleTx {
	return &sysRoleBelongsToParentSysRoleTx{a.db.Model(m).Association(a.Name())}
}

func (a sysRoleBelongsToParentSysRole) Unscoped() *sysRoleBelongsToParentSysRole {
	a.db = a.db.Unscoped()
	return &a
}

type sysRoleBelongsToParentSysRoleTx struct{ tx *gorm.Association }

func (a sysRoleBelongsToParentSysRoleTx) Find() (result *models.SysRole, err error) {
	return result, a.tx.Find(&result)
}

func (a sysRoleBelongsToParentSysRoleTx) Append(values ...*models.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sysRoleBelongsToParentSysRoleTx) Replace(values ...*models.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sysRoleBelongsToParentSysRoleTx) Delete(values ...*models.SysRole) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sysRoleBelongsToParentSysRoleTx) Clear() error {
	return a.tx.Clear()
}

func (a sysRoleBelongsToParentSysRoleTx) Count() int64 {
	return a.tx.Count()
}

func (a sysRoleBelongsToParentSysRoleTx) Unscoped() *sysRoleBelongsToParentSysRoleTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sysRoleDo struct{ gen.DO }

type ISysRoleDo interface {
	gen.SubQuery
	Debug() ISysRoleDo
	WithContext(ctx context.Context) ISysRoleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysRoleDo
	WriteDB() ISysRoleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysRoleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysRoleDo
	Not(conds ...gen.Condition) ISysRoleDo
	Or(conds ...gen.Condition) ISysRoleDo
	Select(conds ...field.Expr) ISysRoleDo
	Where(conds ...gen.Condition) ISysRoleDo
	Order(conds ...field.Expr) ISysRoleDo
	Distinct(cols ...field.Expr) ISysRoleDo
	Omit(cols ...field.Expr) ISysRoleDo
	Join(table schema.Tabler, on ...field.Expr) ISysRoleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleDo
	Group(cols ...field.Expr) ISysRoleDo
	Having(conds ...gen.Condition) ISysRoleDo
	Limit(limit int) ISysRoleDo
	Offset(offset int) ISysRoleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleDo
	Unscoped() ISysRoleDo
	Create(values ...*models.SysRole) error
	CreateInBatches(values []*models.SysRole, batchSize int) error
	Save(values ...*models.SysRole) error
	First() (*models.SysRole, error)
	Take() (*models.SysRole, error)
	Last() (*models.SysRole, error)
	Find() ([]*models.SysRole, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysRole, err error)
	FindInBatches(result *[]*models.SysRole, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysRole) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysRoleDo
	Assign(attrs ...field.AssignExpr) ISysRoleDo
	Joins(fields ...field.RelationField) ISysRoleDo
	Preload(fields ...field.RelationField) ISysRoleDo
	FirstOrInit() (*models.SysRole, error)
	FirstOrCreate() (*models.SysRole, error)
	FindByPage(offset int, limit int) (result []*models.SysRole, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysRoleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysRoleDo) Debug() ISysRoleDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRoleDo) WithContext(ctx context.Context) ISysRoleDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRoleDo) ReadDB() ISysRoleDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRoleDo) WriteDB() ISysRoleDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRoleDo) Session(config *gorm.Session) ISysRoleDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysRoleDo) Clauses(conds ...clause.Expression) ISysRoleDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRoleDo) Returning(value interface{}, columns ...string) ISysRoleDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRoleDo) Not(conds ...gen.Condition) ISysRoleDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRoleDo) Or(conds ...gen.Condition) ISysRoleDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRoleDo) Select(conds ...field.Expr) ISysRoleDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRoleDo) Where(conds ...gen.Condition) ISysRoleDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRoleDo) Order(conds ...field.Expr) ISysRoleDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRoleDo) Distinct(cols ...field.Expr) ISysRoleDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRoleDo) Omit(cols ...field.Expr) ISysRoleDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRoleDo) Join(table schema.Tabler, on ...field.Expr) ISysRoleDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRoleDo) Group(cols ...field.Expr) ISysRoleDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRoleDo) Having(conds ...gen.Condition) ISysRoleDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRoleDo) Limit(limit int) ISysRoleDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRoleDo) Offset(offset int) ISysRoleDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRoleDo) Unscoped() ISysRoleDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRoleDo) Create(values ...*models.SysRole) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRoleDo) CreateInBatches(values []*models.SysRole, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRoleDo) Save(values ...*models.SysRole) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRoleDo) First() (*models.SysRole, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysRole), nil
	}
}

func (s sysRoleDo) Take() (*models.SysRole, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysRole), nil
	}
}

func (s sysRoleDo) Last() (*models.SysRole, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysRole), nil
	}
}

func (s sysRoleDo) Find() ([]*models.SysRole, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysRole), err
}

func (s sysRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysRole, err error) {
	buf := make([]*models.SysRole, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRoleDo) FindInBatches(result *[]*models.SysRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRoleDo) Attrs(attrs ...field.AssignExpr) ISysRoleDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRoleDo) Assign(attrs ...field.AssignExpr) ISysRoleDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRoleDo) Joins(fields ...field.RelationField) ISysRoleDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRoleDo) Preload(fields ...field.RelationField) ISysRoleDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRoleDo) FirstOrInit() (*models.SysRole, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysRole), nil
	}
}

func (s sysRoleDo) FirstOrCreate() (*models.SysRole, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysRole), nil
	}
}

func (s sysRoleDo) FindByPage(offset int, limit int) (result []*models.SysRole, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRoleDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRoleDo) Delete(models ...*models.SysRole) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRoleDo) withDO(do gen.Dao) *sysRoleDo {
	s.DO = *do.(*gen.DO)
	return s
}
