// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"admin/services/orm/models"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysOperationLog(db *gorm.DB, opts ...gen.DOOption) sysOperationLog {
	_sysOperationLog := sysOperationLog{}

	_sysOperationLog.sysOperationLogDo.UseDB(db, opts...)
	_sysOperationLog.sysOperationLogDo.UseModel(&models.SysOperationLog{})

	tableName := _sysOperationLog.sysOperationLogDo.TableName()
	_sysOperationLog.ALL = field.NewAsterisk(tableName)
	_sysOperationLog.ID = field.NewUint64(tableName, "id")
	_sysOperationLog.CreatedAt = field.NewTime(tableName, "created_at")
	_sysOperationLog.RequestID = field.NewString(tableName, "request_id")
	_sysOperationLog.Method = field.NewString(tableName, "method")
	_sysOperationLog.Module = field.NewString(tableName, "module")
	_sysOperationLog.Path = field.NewString(tableName, "path")
	_sysOperationLog.Referer = field.NewString(tableName, "referer")
	_sysOperationLog.BeforeChange = field.NewString(tableName, "before_change")
	_sysOperationLog.AfterChange = field.NewString(tableName, "after_change")
	_sysOperationLog.FormatChange = field.NewString(tableName, "format_change")
	_sysOperationLog.RequestURI = field.NewString(tableName, "request_uri")
	_sysOperationLog.RequestBody = field.NewString(tableName, "request_body")
	_sysOperationLog.RequestHeader = field.NewString(tableName, "request_header")
	_sysOperationLog.Response = field.NewString(tableName, "response")
	_sysOperationLog.CostTime = field.NewInt64(tableName, "cost_time")
	_sysOperationLog.UserID = field.NewUint64(tableName, "user_id")
	_sysOperationLog.Username = field.NewString(tableName, "username")
	_sysOperationLog.ClientIP = field.NewString(tableName, "client_ip")
	_sysOperationLog.StatusCode = field.NewInt(tableName, "status_code")
	_sysOperationLog.Reason = field.NewString(tableName, "reason")
	_sysOperationLog.Success = field.NewBool(tableName, "success")
	_sysOperationLog.Location = field.NewString(tableName, "location")
	_sysOperationLog.UserAgent = field.NewString(tableName, "user_agent")
	_sysOperationLog.BrowserName = field.NewString(tableName, "browser_name")
	_sysOperationLog.BrowserVersion = field.NewString(tableName, "browser_version")
	_sysOperationLog.ClientID = field.NewString(tableName, "client_id")
	_sysOperationLog.ClientName = field.NewString(tableName, "client_name")
	_sysOperationLog.OSName = field.NewString(tableName, "os_name")
	_sysOperationLog.OSVersion = field.NewString(tableName, "os_version")

	_sysOperationLog.fillFieldMap()

	return _sysOperationLog
}

type sysOperationLog struct {
	sysOperationLogDo

	ALL            field.Asterisk
	ID             field.Uint64
	CreatedAt      field.Time
	RequestID      field.String // 请求ID
	Method         field.String // 请求方法
	Module         field.String // 模块
	Path           field.String // 请求路径
	Referer        field.String // 请求源
	BeforeChange   field.String // 变更前内容
	AfterChange    field.String // 变更后内容
	FormatChange   field.String // 格式化变化内容
	RequestURI     field.String // 请求URI
	RequestBody    field.String // 请求体
	RequestHeader  field.String // 请求头
	Response       field.String // 响应信息
	CostTime       field.Int64  // 操作耗时
	UserID         field.Uint64 // 操作者用户ID
	Username       field.String // 操作者账号名
	ClientIP       field.String // 操作者IP
	StatusCode     field.Int    // 状态码
	Reason         field.String // 操作失败原因
	Success        field.Bool   // 操作成功
	Location       field.String // 操作地理位置
	UserAgent      field.String // 浏览器的用户代理信息
	BrowserName    field.String // 浏览器名称
	BrowserVersion field.String // 浏览器版本
	ClientID       field.String // 客户端ID
	ClientName     field.String // 客户端名称
	OSName         field.String // 操作系统名称
	OSVersion      field.String // 操作系统版本

	fieldMap map[string]field.Expr
}

func (s sysOperationLog) Table(newTableName string) *sysOperationLog {
	s.sysOperationLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysOperationLog) As(alias string) *sysOperationLog {
	s.sysOperationLogDo.DO = *(s.sysOperationLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysOperationLog) updateTableName(table string) *sysOperationLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.RequestID = field.NewString(table, "request_id")
	s.Method = field.NewString(table, "method")
	s.Module = field.NewString(table, "module")
	s.Path = field.NewString(table, "path")
	s.Referer = field.NewString(table, "referer")
	s.BeforeChange = field.NewString(table, "before_change")
	s.AfterChange = field.NewString(table, "after_change")
	s.FormatChange = field.NewString(table, "format_change")
	s.RequestURI = field.NewString(table, "request_uri")
	s.RequestBody = field.NewString(table, "request_body")
	s.RequestHeader = field.NewString(table, "request_header")
	s.Response = field.NewString(table, "response")
	s.CostTime = field.NewInt64(table, "cost_time")
	s.UserID = field.NewUint64(table, "user_id")
	s.Username = field.NewString(table, "username")
	s.ClientIP = field.NewString(table, "client_ip")
	s.StatusCode = field.NewInt(table, "status_code")
	s.Reason = field.NewString(table, "reason")
	s.Success = field.NewBool(table, "success")
	s.Location = field.NewString(table, "location")
	s.UserAgent = field.NewString(table, "user_agent")
	s.BrowserName = field.NewString(table, "browser_name")
	s.BrowserVersion = field.NewString(table, "browser_version")
	s.ClientID = field.NewString(table, "client_id")
	s.ClientName = field.NewString(table, "client_name")
	s.OSName = field.NewString(table, "os_name")
	s.OSVersion = field.NewString(table, "os_version")

	s.fillFieldMap()

	return s
}

func (s *sysOperationLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysOperationLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 29)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["request_id"] = s.RequestID
	s.fieldMap["method"] = s.Method
	s.fieldMap["module"] = s.Module
	s.fieldMap["path"] = s.Path
	s.fieldMap["referer"] = s.Referer
	s.fieldMap["before_change"] = s.BeforeChange
	s.fieldMap["after_change"] = s.AfterChange
	s.fieldMap["format_change"] = s.FormatChange
	s.fieldMap["request_uri"] = s.RequestURI
	s.fieldMap["request_body"] = s.RequestBody
	s.fieldMap["request_header"] = s.RequestHeader
	s.fieldMap["response"] = s.Response
	s.fieldMap["cost_time"] = s.CostTime
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["username"] = s.Username
	s.fieldMap["client_ip"] = s.ClientIP
	s.fieldMap["status_code"] = s.StatusCode
	s.fieldMap["reason"] = s.Reason
	s.fieldMap["success"] = s.Success
	s.fieldMap["location"] = s.Location
	s.fieldMap["user_agent"] = s.UserAgent
	s.fieldMap["browser_name"] = s.BrowserName
	s.fieldMap["browser_version"] = s.BrowserVersion
	s.fieldMap["client_id"] = s.ClientID
	s.fieldMap["client_name"] = s.ClientName
	s.fieldMap["os_name"] = s.OSName
	s.fieldMap["os_version"] = s.OSVersion
}

func (s sysOperationLog) clone(db *gorm.DB) sysOperationLog {
	s.sysOperationLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysOperationLog) replaceDB(db *gorm.DB) sysOperationLog {
	s.sysOperationLogDo.ReplaceDB(db)
	return s
}

type sysOperationLogDo struct{ gen.DO }

type ISysOperationLogDo interface {
	gen.SubQuery
	Debug() ISysOperationLogDo
	WithContext(ctx context.Context) ISysOperationLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysOperationLogDo
	WriteDB() ISysOperationLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysOperationLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysOperationLogDo
	Not(conds ...gen.Condition) ISysOperationLogDo
	Or(conds ...gen.Condition) ISysOperationLogDo
	Select(conds ...field.Expr) ISysOperationLogDo
	Where(conds ...gen.Condition) ISysOperationLogDo
	Order(conds ...field.Expr) ISysOperationLogDo
	Distinct(cols ...field.Expr) ISysOperationLogDo
	Omit(cols ...field.Expr) ISysOperationLogDo
	Join(table schema.Tabler, on ...field.Expr) ISysOperationLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysOperationLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysOperationLogDo
	Group(cols ...field.Expr) ISysOperationLogDo
	Having(conds ...gen.Condition) ISysOperationLogDo
	Limit(limit int) ISysOperationLogDo
	Offset(offset int) ISysOperationLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysOperationLogDo
	Unscoped() ISysOperationLogDo
	Create(values ...*models.SysOperationLog) error
	CreateInBatches(values []*models.SysOperationLog, batchSize int) error
	Save(values ...*models.SysOperationLog) error
	First() (*models.SysOperationLog, error)
	Take() (*models.SysOperationLog, error)
	Last() (*models.SysOperationLog, error)
	Find() ([]*models.SysOperationLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysOperationLog, err error)
	FindInBatches(result *[]*models.SysOperationLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.SysOperationLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysOperationLogDo
	Assign(attrs ...field.AssignExpr) ISysOperationLogDo
	Joins(fields ...field.RelationField) ISysOperationLogDo
	Preload(fields ...field.RelationField) ISysOperationLogDo
	FirstOrInit() (*models.SysOperationLog, error)
	FirstOrCreate() (*models.SysOperationLog, error)
	FindByPage(offset int, limit int) (result []*models.SysOperationLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysOperationLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysOperationLogDo) Debug() ISysOperationLogDo {
	return s.withDO(s.DO.Debug())
}

func (s sysOperationLogDo) WithContext(ctx context.Context) ISysOperationLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysOperationLogDo) ReadDB() ISysOperationLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysOperationLogDo) WriteDB() ISysOperationLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysOperationLogDo) Session(config *gorm.Session) ISysOperationLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysOperationLogDo) Clauses(conds ...clause.Expression) ISysOperationLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysOperationLogDo) Returning(value interface{}, columns ...string) ISysOperationLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysOperationLogDo) Not(conds ...gen.Condition) ISysOperationLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysOperationLogDo) Or(conds ...gen.Condition) ISysOperationLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysOperationLogDo) Select(conds ...field.Expr) ISysOperationLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysOperationLogDo) Where(conds ...gen.Condition) ISysOperationLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysOperationLogDo) Order(conds ...field.Expr) ISysOperationLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysOperationLogDo) Distinct(cols ...field.Expr) ISysOperationLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysOperationLogDo) Omit(cols ...field.Expr) ISysOperationLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysOperationLogDo) Join(table schema.Tabler, on ...field.Expr) ISysOperationLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysOperationLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysOperationLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysOperationLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysOperationLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysOperationLogDo) Group(cols ...field.Expr) ISysOperationLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysOperationLogDo) Having(conds ...gen.Condition) ISysOperationLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysOperationLogDo) Limit(limit int) ISysOperationLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysOperationLogDo) Offset(offset int) ISysOperationLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysOperationLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysOperationLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysOperationLogDo) Unscoped() ISysOperationLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysOperationLogDo) Create(values ...*models.SysOperationLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysOperationLogDo) CreateInBatches(values []*models.SysOperationLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysOperationLogDo) Save(values ...*models.SysOperationLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysOperationLogDo) First() (*models.SysOperationLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysOperationLog), nil
	}
}

func (s sysOperationLogDo) Take() (*models.SysOperationLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysOperationLog), nil
	}
}

func (s sysOperationLogDo) Last() (*models.SysOperationLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysOperationLog), nil
	}
}

func (s sysOperationLogDo) Find() ([]*models.SysOperationLog, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysOperationLog), err
}

func (s sysOperationLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysOperationLog, err error) {
	buf := make([]*models.SysOperationLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysOperationLogDo) FindInBatches(result *[]*models.SysOperationLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysOperationLogDo) Attrs(attrs ...field.AssignExpr) ISysOperationLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysOperationLogDo) Assign(attrs ...field.AssignExpr) ISysOperationLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysOperationLogDo) Joins(fields ...field.RelationField) ISysOperationLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysOperationLogDo) Preload(fields ...field.RelationField) ISysOperationLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysOperationLogDo) FirstOrInit() (*models.SysOperationLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysOperationLog), nil
	}
}

func (s sysOperationLogDo) FirstOrCreate() (*models.SysOperationLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysOperationLog), nil
	}
}

func (s sysOperationLogDo) FindByPage(offset int, limit int) (result []*models.SysOperationLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysOperationLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysOperationLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysOperationLogDo) Delete(models ...*models.SysOperationLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysOperationLogDo) withDO(do gen.Dao) *sysOperationLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
