/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const DEFAULT_PAGE_SIZE: typeof import('./domains/page').DEFAULT_PAGE_SIZE
  const DictApi: typeof import('./api/business/sysDict').DictApi
  const DictCode: typeof import('./domains/dict').DictCode
  const EncryptApi: typeof import('./api/encrypt').EncryptApi
  const ErrorComponent: typeof import('./components/error').ErrorComponent
  const Fragment: typeof import('react').Fragment
  const HttpCode: typeof import('./domains/http').HttpCode
  const HttpCodeCheck: typeof import('./domains/http').HttpCodeCheck
  const NotFoundComponent: typeof import('./components/notFound').NotFoundComponent
  const Suspense: typeof import('react').Suspense
  const XHeader: typeof import('./domains/http').XHeader
  const aesDecrypt: typeof import('./utils/encrypt').aesDecrypt
  const aesDecryptCiphertextAndTag: typeof import('./utils/encrypt').aesDecryptCiphertextAndTag
  const aesEncrypt: typeof import('./utils/encrypt').aesEncrypt
  const api: typeof import('./api/index').default
  const arrayBufferToBase64: typeof import('./utils/encrypt').arrayBufferToBase64
  const base64ToArrayBuffer: typeof import('./utils/encrypt').base64ToArrayBuffer
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const cn: typeof import('./components/lib/utils').cn
  const createContext: typeof import('react').createContext
  const createEncryptedRequestConfig: typeof import('./api/encryptRequest').createEncryptedRequestConfig
  const createRef: typeof import('react').createRef
  const decryptText: typeof import('./api/encryptRequest').decryptText
  const encryptRequest: typeof import('./api/encryptRequest').encryptRequest
  const ensurePublicKey: typeof import('./api/encryptRequest').ensurePublicKey
  const formatDateYYYYMMDDHHmmss: typeof import('./utils/date').formatDateYYYYMMDDHHmmss
  const forwardRef: typeof import('react').forwardRef
  const generateAesKey: typeof import('./utils/encrypt').generateAesKey
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const rsaEncrypt: typeof import('./utils/encrypt').rsaEncrypt
  const startTransition: typeof import('react').startTransition
  const uriSort: typeof import('./utils/encrypt').uriSort
  const use: typeof import('react').use
  const useAccountStore: typeof import('./stores/account').useAccountStore
  const useActionState: typeof import('react').useActionState
  const useAntdTable: typeof import('ahooks').useAntdTable
  const useAsyncEffect: typeof import('ahooks').useAsyncEffect
  const useBoolean: typeof import('ahooks').useBoolean
  const useCallback: typeof import('react').useCallback
  const useClickAway: typeof import('ahooks').useClickAway
  const useContext: typeof import('react').useContext
  const useControllableValue: typeof import('ahooks').useControllableValue
  const useCookieState: typeof import('ahooks').useCookieState
  const useCountDown: typeof import('ahooks').useCountDown
  const useCounter: typeof import('ahooks').useCounter
  const useCreation: typeof import('ahooks').useCreation
  const useDebounce: typeof import('ahooks').useDebounce
  const useDebounceEffect: typeof import('ahooks').useDebounceEffect
  const useDebounceFn: typeof import('ahooks').useDebounceFn
  const useDebugValue: typeof import('react').useDebugValue
  const useDeepCompareEffect: typeof import('ahooks').useDeepCompareEffect
  const useDeepCompareLayoutEffect: typeof import('ahooks').useDeepCompareLayoutEffect
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDeviceStore: typeof import('./stores/device').useDeviceStore
  const useDocumentVisibility: typeof import('ahooks').useDocumentVisibility
  const useDrag: typeof import('ahooks').useDrag
  const useDrop: typeof import('ahooks').useDrop
  const useDynamicList: typeof import('ahooks').useDynamicList
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useEventEmitter: typeof import('ahooks').useEventEmitter
  const useEventListener: typeof import('ahooks').useEventListener
  const useEventTarget: typeof import('ahooks').useEventTarget
  const useExternal: typeof import('ahooks').useExternal
  const useFavicon: typeof import('ahooks').useFavicon
  const useFocusWithin: typeof import('ahooks').useFocusWithin
  const useFullscreen: typeof import('ahooks').useFullscreen
  const useFusionTable: typeof import('ahooks').useFusionTable
  const useGetState: typeof import('ahooks').useGetState
  const useHistoryTravel: typeof import('ahooks').useHistoryTravel
  const useHover: typeof import('ahooks').useHover
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInViewport: typeof import('ahooks').useInViewport
  const useInfiniteScroll: typeof import('ahooks').useInfiniteScroll
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useInterval: typeof import('ahooks').useInterval
  const useIsomorphicLayoutEffect: typeof import('ahooks').useIsomorphicLayoutEffect
  const useKeyPress: typeof import('ahooks').useKeyPress
  const useLatest: typeof import('ahooks').useLatest
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocalStorageState: typeof import('ahooks').useLocalStorageState
  const useLockFn: typeof import('ahooks').useLockFn
  const useLongPress: typeof import('ahooks').useLongPress
  const useMap: typeof import('ahooks').useMap
  const useMemo: typeof import('react').useMemo
  const useMemoizedFn: typeof import('ahooks').useMemoizedFn
  const useMockStore: typeof import('./stores/mock').useMockStore
  const useMount: typeof import('ahooks').useMount
  const useMouse: typeof import('ahooks').useMouse
  const useMutationObserver: typeof import('ahooks').useMutationObserver
  const useNetwork: typeof import('ahooks').useNetwork
  const useOptimistic: typeof import('react').useOptimistic
  const usePagination: typeof import('ahooks').usePagination
  const usePrevious: typeof import('ahooks').usePrevious
  const useRafInterval: typeof import('ahooks').useRafInterval
  const useRafState: typeof import('ahooks').useRafState
  const useRafTimeout: typeof import('ahooks').useRafTimeout
  const useReactive: typeof import('ahooks').useReactive
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRequest: typeof import('ahooks').useRequest
  const useResetState: typeof import('ahooks').useResetState
  const useResponsive: typeof import('ahooks').useResponsive
  const useSafeState: typeof import('ahooks').useSafeState
  const useScroll: typeof import('ahooks').useScroll
  const useSelections: typeof import('ahooks').useSelections
  const useSessionStorageState: typeof import('ahooks').useSessionStorageState
  const useSet: typeof import('ahooks').useSet
  const useSetState: typeof import('ahooks').useSetState
  const useSize: typeof import('ahooks').useSize
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTextSelection: typeof import('ahooks').useTextSelection
  const useTheme: typeof import('ahooks').useTheme
  const useThrottle: typeof import('ahooks').useThrottle
  const useThrottleEffect: typeof import('ahooks').useThrottleEffect
  const useThrottleFn: typeof import('ahooks').useThrottleFn
  const useTimeout: typeof import('ahooks').useTimeout
  const useTitle: typeof import('ahooks').useTitle
  const useToggle: typeof import('ahooks').useToggle
  const useTrackedEffect: typeof import('ahooks').useTrackedEffect
  const useTransition: typeof import('react').useTransition
  const useTranslation: typeof import('react-i18next').useTranslation
  const useUnmount: typeof import('ahooks').useUnmount
  const useUnmountedRef: typeof import('ahooks').useUnmountedRef
  const useUpdate: typeof import('ahooks').useUpdate
  const useUpdateEffect: typeof import('ahooks').useUpdateEffect
  const useUpdateLayoutEffect: typeof import('ahooks').useUpdateLayoutEffect
  const useVirtualList: typeof import('ahooks').useVirtualList
  const useWebSocket: typeof import('ahooks').useWebSocket
  const useWhyDidYouUpdate: typeof import('ahooks').useWhyDidYouUpdate
  const waitForHydration: typeof import('./stores/mock').waitForHydration
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ReqChangePwd, ReqPwdLogin, ResLogin } from './domains/account'
  import('./domains/account')
  // @ts-ignore
  export type { ResPublicKey } from './domains/encrypt'
  import('./domains/encrypt')
  // @ts-ignore
  export type { CodeType } from './domains/http'
  import('./domains/http')
  // @ts-ignore
  export type { PagingRequest, PagingResult } from './domains/page'
  import('./domains/page')
  // @ts-ignore
  export type { DictMatchedEntriesByCode, DictMatchedEntry, ReqDictEntryMatch } from './api/business/sysDict'
  import('./api/business/sysDict')
}
