// Code generated by go generate; DO NOT EDIT.

package main

import (
	_ "orm-crud/gormc/field"
	_ "orm-crud/gormc/filter"
	_ "orm-crud/gormc/mixin"
	_ "orm-crud/gormc/pagination"
	_ "orm-crud/gormc/sorting"
)
