/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDashboard2RouteImport } from './routes/_app/dashboard2'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as loginLoginRouteImport } from './routes/(login)/login'
import { Route as AppAccountUserRouteImport } from './routes/_app/account/user'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboard2Route = AppDashboard2RouteImport.update({
  id: '/dashboard2',
  path: '/dashboard2',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const loginLoginRoute = loginLoginRouteImport.update({
  id: '/(login)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountUserRoute = AppAccountUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof loginLoginRoute
  '/account': typeof AppAccountRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/dashboard2': typeof AppDashboard2Route
  '/account/user': typeof AppAccountUserRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginLoginRoute
  '/account': typeof AppAccountRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/dashboard2': typeof AppDashboard2Route
  '/': typeof AppIndexRoute
  '/account/user': typeof AppAccountUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/(login)/login': typeof loginLoginRoute
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dashboard2': typeof AppDashboard2Route
  '/_app/': typeof AppIndexRoute
  '/_app/account/user': typeof AppAccountUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/dashboard2'
    | '/account/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/account'
    | '/dashboard'
    | '/dashboard2'
    | '/'
    | '/account/user'
  id:
    | '__root__'
    | '/_app'
    | '/(login)/login'
    | '/_app/account'
    | '/_app/dashboard'
    | '/_app/dashboard2'
    | '/_app/'
    | '/_app/account/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  loginLoginRoute: typeof loginLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard2': {
      id: '/_app/dashboard2'
      path: '/dashboard2'
      fullPath: '/dashboard2'
      preLoaderRoute: typeof AppDashboard2RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/(login)/login': {
      id: '/(login)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account/user': {
      id: '/_app/account/user'
      path: '/user'
      fullPath: '/account/user'
      preLoaderRoute: typeof AppAccountUserRouteImport
      parentRoute: typeof AppAccountRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountUserRoute: typeof AppAccountUserRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountUserRoute: AppAccountUserRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDashboard2Route: typeof AppDashboard2Route
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDashboard2Route: AppDashboard2Route,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  loginLoginRoute: loginLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
