// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	field2 "gorm.io/gen/field"
	"gorm.io/gorm"
	"orm-crud/gormc/field"
	"orm-crud/gormc/filter"
	paging "orm-crud/gormc/pagination"
	"orm-crud/gormc/sorting"
	paginationSorting "orm-crud/pagination/sorting"
)

var (
	structuredSorting      = sorting.NewStructuredSorting()
	offsetPaginator        = paging.NewOffsetPaginator()
	pagePaginator          = paging.NewPagePaginator()
	tokenPaginator         = paging.NewTokenPaginator()
	structuredFilter       = filter.NewStructuredFilter()
	orderByStringConverter = paginationSorting.NewOrderByStringConverter()
	fieldSelector          = field.NewFieldSelector()
)

func ExprAppendSelf[T any](s1 *[]field2.AssignExpr, v *T, fn func(T) field2.AssignExpr) {
	if s1 == nil {
		return
	}
	if v != nil {
		*s1 = append(*s1, fn(*v))
	}
}

func WithDBScopes(scopes ...func(*gorm.DB) *gorm.DB) *Query {
	if Q == nil || Q.db == nil || len(scopes) == 0 {
		return Q
	}

	db := Q.db
	for _, scope := range scopes {
		if scope != nil {
			db = scope(db)
		}
	}
	return Q.ReplaceDB(db)
}
