// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/account/changePwd": {
            "post": {
                "description": "修改当前登录用户的密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "修改密码请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqAccountChangePwd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/account/login/pwd": {
            "post": {
                "description": "通过用户名和密码登录系统，并返回 token 与会话公钥",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "用户密码登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqAccountPwdLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_router_logic.ResAccountPwdLogin"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/account/logout": {
            "get": {
                "description": "使当前登录态失效",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "退出登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录 token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/dict/entry/batch/copy": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dict"
                ],
                "summary": "批量复制字典数据项",
                "parameters": [
                    {
                        "description": "批量复制参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqDictEntryBatchCopy"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/dict/entry/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dict"
                ],
                "summary": "创建字典数据项",
                "parameters": [
                    {
                        "description": "字典数据项创建参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqDictEntryCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/dict/entry/del": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dict"
                ],
                "summary": "批量删除字典数据项",
                "parameters": [
                    {
                        "description": "批量删除参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqDictEntryBatchDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/dict/entry/list": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dict"
                ],
                "summary": "获取字典数据项分页列表",
                "parameters": [
                    {
                        "description": "分页参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PagingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/gormc.PagingResult-admin_internal_services_orm_models_SysDictEntry"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/dict/entry/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dict"
                ],
                "summary": "更新字典数据项",
                "parameters": [
                    {
                        "description": "字典数据项更新参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqDictEntryUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/dict/type/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dict"
                ],
                "summary": "创建字典类型",
                "parameters": [
                    {
                        "description": "字典类型创建参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqDictTypeCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/dict/type/del": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dict"
                ],
                "summary": "批量删除字典类型",
                "parameters": [
                    {
                        "description": "批量删除参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqDictTypeBatchDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/dict/type/list": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dict"
                ],
                "summary": "获取字典类型分页列表",
                "parameters": [
                    {
                        "description": "分页参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PagingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/gormc.PagingResult-internal_router_logic_RespDictType"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/dict/type/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dict"
                ],
                "summary": "更新字典类型",
                "parameters": [
                    {
                        "description": "字典类型更新参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqDictTypeUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/encrypt/public/key": {
            "get": {
                "description": "获取用于敏感数据加密的 RSA 公钥",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Encrypt"
                ],
                "summary": "获取加密公钥",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_router_logic.ResPublicKey"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/log/detail": {
            "post": {
                "description": "根据 ID 获取操作日志详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Log"
                ],
                "summary": "获取操作日志详情",
                "parameters": [
                    {
                        "description": "日志ID",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqLogDetail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/admin_internal_services_orm_models.SysOperationLog"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/log/list": {
            "post": {
                "description": "分页查询操作日志信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Log"
                ],
                "summary": "获取操作日志分页列表",
                "parameters": [
                    {
                        "description": "分页参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PagingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/gormc.PagingResult-admin_internal_services_orm_models_SysOperationLog"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/role/create": {
            "post": {
                "description": "创建新的角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "角色创建参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqRoleCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/role/del": {
            "post": {
                "description": "根据角色 ID 删除角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "description": "角色删除参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqRoleDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/role/list": {
            "get": {
                "description": "分页查询角色信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "获取角色分页列表",
                "parameters": [
                    {
                        "description": "分页参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PagingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/gormc.PagingResult-admin_internal_services_orm_models_SysRole"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/role/switch": {
            "post": {
                "description": "根据角色 ID 修改启用状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "切换角色状态",
                "parameters": [
                    {
                        "description": "角色状态参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqRoleSwitchStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/role/update": {
            "post": {
                "description": "根据角色 ID 更新角色信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "description": "角色更新参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqRoleUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/sys/language/entry/batch/create": {
            "post": {
                "description": "根据条目编码和语言值映射批量创建语言条目，已存在的则更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "批量创建语言条目",
                "parameters": [
                    {
                        "description": "批量创建参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqLangEntryBatchCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/sys/language/entry/create": {
            "post": {
                "description": "创建新的语言条目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "创建语言条目",
                "parameters": [
                    {
                        "description": "语言条目创建参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqLangEntryCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/sys/language/entry/del": {
            "post": {
                "description": "根据 ID 列表批量删除语言条目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "批量删除语言条目",
                "parameters": [
                    {
                        "description": "批量删除参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqLangEntryBatchDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/sys/language/entry/list": {
            "post": {
                "description": "分页查询语言条目信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "获取语言条目分页列表",
                "parameters": [
                    {
                        "description": "分页参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PagingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/gormc.PagingResult-admin_internal_services_orm_models_SysLanguageEntry"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/sys/language/entry/update": {
            "post": {
                "description": "根据 ID 更新语言条目信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "更新语言条目",
                "parameters": [
                    {
                        "description": "语言条目更新参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqLangEntryUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/sys/language/type/create": {
            "post": {
                "description": "创建新的语言类型",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "创建语言类型",
                "parameters": [
                    {
                        "description": "语言类型创建参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqLangTypeCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/sys/language/type/del": {
            "post": {
                "description": "根据 ID 列表批量删除语言类型及其关联的所有语言条目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "批量删除语言类型",
                "parameters": [
                    {
                        "description": "批量删除参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqLangTypeBatchDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/sys/language/type/list": {
            "post": {
                "description": "分页查询语言类型信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "获取语言类型分页列表",
                "parameters": [
                    {
                        "description": "分页参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PagingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/gormc.PagingResult-admin_internal_services_orm_models_SysLanguageType"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/sys/language/type/update": {
            "post": {
                "description": "根据 ID 更新语言类型信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Language"
                ],
                "summary": "更新语言类型",
                "parameters": [
                    {
                        "description": "语言类型更新参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqLangTypeUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/sys/resource/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resource"
                ],
                "summary": "创建资源",
                "parameters": [
                    {
                        "description": "资源创建参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqResourceCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/sys/resource/del": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resource"
                ],
                "summary": "批量删除资源",
                "parameters": [
                    {
                        "description": "批量删除参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqResourceBatchDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/sys/resource/list": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resource"
                ],
                "summary": "获取资源分页列表",
                "parameters": [
                    {
                        "description": "分页参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PagingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/gormc.PagingResult-admin_internal_services_orm_models_SysResource"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/sys/resource/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resource"
                ],
                "summary": "更新资源",
                "parameters": [
                    {
                        "description": "资源更新参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_router_logic.ReqResourceUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_internal_fiberc_res.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin_internal_fiberc_res.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 1
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "admin_internal_services_orm_models.SysDictEntry": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "deletedAt": {
                    "type": "integer"
                },
                "deletedBy": {
                    "type": "integer"
                },
                "entryLabel": {
                    "type": "string"
                },
                "entryValue": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "languageCode": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "sysDictType": {
                    "$ref": "#/definitions/admin_internal_services_orm_models.SysDictType"
                },
                "sysDictTypeId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer"
                }
            }
        },
        "admin_internal_services_orm_models.SysDictType": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "deletedAt": {
                    "type": "integer"
                },
                "deletedBy": {
                    "type": "integer"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_internal_services_orm_models.SysDictEntry"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "typeCode": {
                    "type": "string"
                },
                "typeName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer"
                }
            }
        },
        "admin_internal_services_orm_models.SysLanguageEntry": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "deletedAt": {
                    "type": "integer"
                },
                "deletedBy": {
                    "type": "integer"
                },
                "entryCode": {
                    "type": "string"
                },
                "entryValue": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "sysLanguageType": {
                    "$ref": "#/definitions/admin_internal_services_orm_models.SysLanguageType"
                },
                "sysLanguageTypeId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer"
                }
            }
        },
        "admin_internal_services_orm_models.SysLanguageType": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "deletedAt": {
                    "type": "integer"
                },
                "deletedBy": {
                    "type": "integer"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_internal_services_orm_models.SysLanguageEntry"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "typeCode": {
                    "type": "string"
                },
                "typeName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer"
                }
            }
        },
        "admin_internal_services_orm_models.SysOperationLog": {
            "type": "object",
            "properties": {
                "afterChange": {
                    "type": "string"
                },
                "beforeChange": {
                    "type": "string"
                },
                "browserName": {
                    "type": "string"
                },
                "browserVersion": {
                    "type": "string"
                },
                "clientID": {
                    "type": "string"
                },
                "clientIP": {
                    "type": "string"
                },
                "clientName": {
                    "type": "string"
                },
                "costTime": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "formatChange": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "module": {
                    "type": "string"
                },
                "oSName": {
                    "type": "string"
                },
                "oSVersion": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "referer": {
                    "type": "string"
                },
                "requestBody": {
                    "type": "string"
                },
                "requestHeader": {
                    "type": "string"
                },
                "requestID": {
                    "type": "string"
                },
                "requestURI": {
                    "type": "string"
                },
                "response": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                },
                "userAgent": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "admin_internal_services_orm_models.SysResource": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "deletedAt": {
                    "type": "integer"
                },
                "deletedBy": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "metadata": {
                    "$ref": "#/definitions/datatypes.JSONMap"
                },
                "name": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer"
                }
            }
        },
        "admin_internal_services_orm_models.SysRole": {
            "type": "object",
            "properties": {
                "childIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_internal_services_orm_models.SysRole"
                    }
                },
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "deletedAt": {
                    "type": "integer"
                },
                "deletedBy": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentID": {
                    "description": "Menus         datatypes.JSONSlice[uint64] ` + "`" + `gorm:\"column:menus;type:json;comment:分配的菜单列表\" json:\"menus\"` + "`" + `\nApis          datatypes.JSONSlice[string] ` + "`" + `gorm:\"column:apis;type:json;comment:分配的API列表\" json:\"apis\"` + "`" + `",
                    "type": "integer"
                },
                "parentSysRole": {
                    "$ref": "#/definitions/admin_internal_services_orm_models.SysRole"
                },
                "remark": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer"
                }
            }
        },
        "datatypes.JSONMap": {
            "type": "object",
            "additionalProperties": true
        },
        "fieldmaskpb.FieldMask": {
            "type": "object",
            "properties": {
                "paths": {
                    "description": "The set of field mask paths.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "gormc.PagingResult-admin_internal_services_orm_models_SysDictEntry": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_internal_services_orm_models.SysDictEntry"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "gormc.PagingResult-admin_internal_services_orm_models_SysLanguageEntry": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_internal_services_orm_models.SysLanguageEntry"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "gormc.PagingResult-admin_internal_services_orm_models_SysLanguageType": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_internal_services_orm_models.SysLanguageType"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "gormc.PagingResult-admin_internal_services_orm_models_SysOperationLog": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_internal_services_orm_models.SysOperationLog"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "gormc.PagingResult-admin_internal_services_orm_models_SysResource": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_internal_services_orm_models.SysResource"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "gormc.PagingResult-admin_internal_services_orm_models_SysRole": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_internal_services_orm_models.SysRole"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "gormc.PagingResult-internal_router_logic_RespDictType": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_router_logic.RespDictType"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_router_logic.ReqAccountChangePwd": {
            "type": "object",
            "required": [
                "newPwd",
                "oldPwd"
            ],
            "properties": {
                "newPwd": {
                    "type": "string",
                    "minLength": 6
                },
                "oldPwd": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "internal_router_logic.ReqAccountPwdLogin": {
            "type": "object",
            "required": [
                "pwd",
                "username"
            ],
            "properties": {
                "pwd": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 24
                }
            }
        },
        "internal_router_logic.ReqDictEntryBatchCopy": {
            "type": "object",
            "required": [
                "entryIds",
                "targetTypeId"
            ],
            "properties": {
                "entryIds": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                },
                "targetTypeId": {
                    "type": "integer"
                }
            }
        },
        "internal_router_logic.ReqDictEntryBatchDelete": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_router_logic.ReqDictEntryCreate": {
            "type": "object",
            "required": [
                "entryLabel",
                "entryValue",
                "sysDictTypeId"
            ],
            "properties": {
                "entryLabel": {
                    "type": "string",
                    "maxLength": 255
                },
                "entryValue": {
                    "type": "string",
                    "maxLength": 255
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "languageCode": {
                    "type": "string",
                    "maxLength": 32
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                },
                "sortOrder": {
                    "type": "integer"
                },
                "sysDictTypeId": {
                    "type": "integer"
                }
            }
        },
        "internal_router_logic.ReqDictEntryUpdate": {
            "type": "object",
            "properties": {
                "entryLabel": {
                    "type": "string",
                    "maxLength": 255
                },
                "entryValue": {
                    "type": "string",
                    "maxLength": 255
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "languageCode": {
                    "type": "string",
                    "maxLength": 32
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                },
                "sortOrder": {
                    "type": "integer"
                },
                "sysDictTypeId": {
                    "type": "integer"
                },
                "updates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_router_logic.ReqDictEntryUpdateItem"
                    }
                }
            }
        },
        "internal_router_logic.ReqDictEntryUpdateItem": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "entryLabel": {
                    "type": "string",
                    "maxLength": 255
                },
                "entryValue": {
                    "type": "string",
                    "maxLength": 255
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "languageCode": {
                    "type": "string",
                    "maxLength": 32
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                },
                "sortOrder": {
                    "type": "integer"
                },
                "sysDictTypeId": {
                    "type": "integer"
                }
            }
        },
        "internal_router_logic.ReqDictTypeBatchDelete": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_router_logic.ReqDictTypeCreate": {
            "type": "object",
            "required": [
                "typeCode",
                "typeName"
            ],
            "properties": {
                "isEnabled": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                },
                "sortOrder": {
                    "type": "integer"
                },
                "typeCode": {
                    "type": "string",
                    "maxLength": 128
                },
                "typeName": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "internal_router_logic.ReqDictTypeUpdate": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                },
                "sortOrder": {
                    "type": "integer"
                },
                "typeCode": {
                    "type": "string",
                    "maxLength": 128
                },
                "typeName": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "internal_router_logic.ReqLangEntryBatchCreate": {
            "type": "object",
            "required": [
                "entryCode",
                "values"
            ],
            "properties": {
                "entryCode": {
                    "type": "string",
                    "maxLength": 128
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "values": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_router_logic.ReqLangEntryBatchDelete": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_router_logic.ReqLangEntryCreate": {
            "type": "object",
            "required": [
                "entryCode",
                "entryValue",
                "sysLanguageTypeId"
            ],
            "properties": {
                "entryCode": {
                    "type": "string",
                    "maxLength": 128
                },
                "entryValue": {
                    "type": "string",
                    "maxLength": 255
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                },
                "sortOrder": {
                    "type": "integer"
                },
                "sysLanguageTypeId": {
                    "type": "integer"
                }
            }
        },
        "internal_router_logic.ReqLangEntryUpdate": {
            "type": "object",
            "properties": {
                "entryCode": {
                    "type": "string",
                    "maxLength": 128
                },
                "entryValue": {
                    "type": "string",
                    "maxLength": 255
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                },
                "sortOrder": {
                    "type": "integer"
                },
                "sysLanguageTypeId": {
                    "type": "integer"
                },
                "updates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_router_logic.ReqLangEntryUpdateItem"
                    }
                }
            }
        },
        "internal_router_logic.ReqLangEntryUpdateItem": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "entryCode": {
                    "type": "string",
                    "maxLength": 128
                },
                "entryValue": {
                    "type": "string",
                    "maxLength": 255
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                },
                "sortOrder": {
                    "type": "integer"
                },
                "sysLanguageTypeId": {
                    "type": "integer"
                }
            }
        },
        "internal_router_logic.ReqLangTypeBatchDelete": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_router_logic.ReqLangTypeCreate": {
            "type": "object",
            "required": [
                "typeCode",
                "typeName"
            ],
            "properties": {
                "isDefault": {
                    "type": "boolean"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "typeCode": {
                    "type": "string",
                    "maxLength": 128
                },
                "typeName": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "internal_router_logic.ReqLangTypeUpdate": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "typeCode": {
                    "type": "string",
                    "maxLength": 128
                },
                "typeName": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "internal_router_logic.ReqLogDetail": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "internal_router_logic.ReqResourceBatchDelete": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "internal_router_logic.ReqResourceCreate": {
            "type": "object",
            "required": [
                "code",
                "name",
                "type"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                },
                "type": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 1
                }
            }
        },
        "internal_router_logic.ReqResourceUpdate": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 255
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                },
                "type": {
                    "type": "string",
                    "maxLength": 32
                }
            }
        },
        "internal_router_logic.ReqRoleCreate": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "internal_router_logic.ReqRoleDelete": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "internal_router_logic.ReqRoleSwitchStatus": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "integer"
                }
            }
        },
        "internal_router_logic.ReqRoleUpdate": {
            "type": "object",
            "required": [
                "code",
                "id",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "internal_router_logic.ResAccountPwdLogin": {
            "type": "object",
            "properties": {
                "publicKey": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_router_logic.ResPublicKey": {
            "type": "object",
            "properties": {
                "publicKey": {
                    "type": "string"
                }
            }
        },
        "internal_router_logic.RespDictType": {
            "type": "object",
            "properties": {
                "canDelete": {
                    "type": "boolean"
                },
                "canWrite": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "deletedAt": {
                    "type": "integer"
                },
                "deletedBy": {
                    "type": "integer"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_internal_services_orm_models.SysDictEntry"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "remark": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "typeCode": {
                    "type": "string"
                },
                "typeName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer"
                }
            }
        },
        "v1.PagingRequest": {
            "type": "object",
            "properties": {
                "Sorting": {
                    "description": "排序规则",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Sorting"
                    }
                },
                "fieldMask": {
                    "description": "字段掩码，其作用为SELECT中的字段，其语法为使用逗号分隔字段名，例如：id,realName,userName。如果为空则选中所有字段，即SELECT *。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/fieldmaskpb.FieldMask"
                        }
                    ]
                },
                "filteringType": {
                    "description": "Types that are valid to be assigned to FilteringType:\n\n\t*PagingRequest_Query\n\t*PagingRequest_Filter\n\t*PagingRequest_FilterExpr"
                },
                "limit": {
                    "description": "最多返回的记录数（默认10，建议设置上限如100）",
                    "type": "integer"
                },
                "noPaging": {
                    "description": "是否不分页，如果为true，则page和pageSize参数无效。",
                    "type": "boolean"
                },
                "offset": {
                    "description": "跳过的记录数（从0开始，默认0）",
                    "type": "integer"
                },
                "orderBy": {
                    "description": "排序条件",
                    "type": "string"
                },
                "page": {
                    "description": "当前页码（从1开始，默认1）",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页条数（默认10，建议设置上限如100）",
                    "type": "integer"
                },
                "token": {
                    "description": "上一页最后一条记录的游标（如ID/时间戳+ID，首次请求为空）",
                    "type": "string"
                }
            }
        },
        "v1.Sorting": {
            "type": "object",
            "properties": {
                "direction": {
                    "description": "排序方向",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.Sorting_Direction"
                        }
                    ]
                },
                "field": {
                    "description": "排序字段（如\"id\"、\"create_time\"）",
                    "type": "string"
                }
            }
        },
        "v1.Sorting_Direction": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "Sorting_ASC",
                "Sorting_DESC"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Admin API",
	Description:      "Admin 后端服务 API 文档。\n所有接口均返回 HTTP 200，通过响应体中的 code 区分业务状态：\n| Code | Msg | 说明 |\n| :--- | :--- | :--- |\n| 1 | success | 成功 |\n| 2 | 服务繁忙 | 通用失败 |\n| 3 | 请求超时 | 请求过期 |\n| 4 | 请求重放 | Nonce 校验失败 |\n| 5 | 请求错误 | 客户端请求错误 |\n| 100 | - | 登录/权限相关失败 |",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
