// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/account/changePwd": {
            "post": {
                "description": "修改当前登录用户的密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "修改密码请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/router_logic.ReqAccountChangePwd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/account/login/pwd": {
            "post": {
                "description": "通过用户名和密码登录系统，并返回 token 与会话公钥",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "用户密码登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/router_logic.ReqAccountPwdLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/router_logic.ResAccountPwdLogin"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/account/logout": {
            "get": {
                "description": "使当前登录态失效",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "退出登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录 token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/encrypt/public/key": {
            "get": {
                "description": "获取用于敏感数据加密的 RSA 公钥",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Encrypt"
                ],
                "summary": "获取加密公钥",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/router_logic.ResPublicKey"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/role/create": {
            "post": {
                "description": "创建新的角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "角色创建参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/router_logic.ReqRoleCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/role/del": {
            "post": {
                "description": "根据角色 ID 删除角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "description": "角色删除参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/router_logic.ReqRoleDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/role/list": {
            "get": {
                "description": "分页查询角色信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "获取角色分页列表",
                "parameters": [
                    {
                        "description": "分页参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PagingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/admin_fiberc_res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/gorm.PagingResult-admin_services_orm_models_SysRole"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/role/switch": {
            "post": {
                "description": "根据角色 ID 修改启用状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "切换角色状态",
                "parameters": [
                    {
                        "description": "角色状态参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/router_logic.ReqRoleSwitchStatus"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_fiberc_res.Response"
                        }
                    }
                }
            }
        },
        "/api/role/update": {
            "post": {
                "description": "根据角色 ID 更新角色信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "description": "角色更新参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/router_logic.ReqRoleUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/admin_fiberc_res.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin_fiberc_res.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 1
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "admin_services_orm_models.SysRole": {
            "type": "object",
            "properties": {
                "apis": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "childIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_services_orm_models.SysRole"
                    }
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "dataScope": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "deleted_by": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "menus": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                },
                "parentID": {
                    "type": "integer"
                },
                "parentSysRole": {
                    "$ref": "#/definitions/admin_services_orm_models.SysRole"
                },
                "path": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "fieldmaskpb.FieldMask": {
            "type": "object",
            "properties": {
                "paths": {
                    "description": "The set of field mask paths.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "gorm.PagingResult-admin_services_orm_models_SysRole": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/admin_services_orm_models.SysRole"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "router_logic.ReqAccountChangePwd": {
            "type": "object",
            "required": [
                "newPwd",
                "oldPwd"
            ],
            "properties": {
                "newPwd": {
                    "type": "string",
                    "minLength": 6
                },
                "oldPwd": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "router_logic.ReqAccountPwdLogin": {
            "type": "object",
            "required": [
                "pwd",
                "username"
            ],
            "properties": {
                "pwd": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 24
                }
            }
        },
        "router_logic.ReqRoleCreate": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "router_logic.ReqRoleDelete": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "router_logic.ReqRoleSwitchStatus": {
            "type": "object",
            "required": [
                "id",
                "status"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "router_logic.ReqRoleUpdate": {
            "type": "object",
            "required": [
                "code",
                "id",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1
                },
                "remark": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "router_logic.ResAccountPwdLogin": {
            "type": "object",
            "properties": {
                "publicKey": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "router_logic.ResPublicKey": {
            "type": "object",
            "properties": {
                "publicKey": {
                    "type": "string"
                }
            }
        },
        "v1.PagingRequest": {
            "type": "object",
            "properties": {
                "field_mask": {
                    "description": "字段掩码，其作用为SELECT中的字段，其语法为使用逗号分隔字段名，例如：id,realName,userName。如果为空则选中所有字段，即SELECT *。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/fieldmaskpb.FieldMask"
                        }
                    ]
                },
                "filteringType": {
                    "description": "Types that are valid to be assigned to FilteringType:\n\n\t*PagingRequest_Query\n\t*PagingRequest_Filter\n\t*PagingRequest_FilterExpr"
                },
                "limit": {
                    "description": "最多返回的记录数（默认10，建议设置上限如100）",
                    "type": "integer"
                },
                "no_paging": {
                    "description": "是否不分页，如果为true，则page和pageSize参数无效。",
                    "type": "boolean"
                },
                "offset": {
                    "description": "跳过的记录数（从0开始，默认0）",
                    "type": "integer"
                },
                "order_by": {
                    "description": "排序条件",
                    "type": "string"
                },
                "page": {
                    "description": "当前页码（从1开始，默认1）",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页条数（默认10，建议设置上限如100）",
                    "type": "integer"
                },
                "sorting": {
                    "description": "排序规则",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Sorting"
                    }
                },
                "token": {
                    "description": "上一页最后一条记录的游标（如ID/时间戳+ID，首次请求为空）",
                    "type": "string"
                }
            }
        },
        "v1.Sorting": {
            "type": "object",
            "properties": {
                "direction": {
                    "description": "排序方向",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.Sorting_Direction"
                        }
                    ]
                },
                "field": {
                    "description": "排序字段（如\"id\"、\"create_time\"）",
                    "type": "string"
                }
            }
        },
        "v1.Sorting_Direction": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "Sorting_ASC",
                "Sorting_DESC"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Admin API",
	Description:      "Admin 后端服务 API 文档。\n所有接口均返回 HTTP 200，通过响应体中的 code 区分业务状态：\n| Code | Msg | 说明 |\n| :--- | :--- | :--- |\n| 1 | success | 成功 |\n| 2 | 服务繁忙 | 通用失败 |\n| 3 | 请求超时 | 请求过期 |\n| 4 | 请求重放 | Nonce 校验失败 |\n| 5 | 请求错误 | 客户端请求错误 |\n| 100 | - | 登录/权限相关失败 |",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
